import type { WordDeckId } from './gameMode'
import { pickWords, type WordPools } from './wordSelection'

export { pickWords } from './wordSelection'

export type Difficulty = 'green' | 'yellow' | 'red'

export interface WordSource {
  id: string
  name: string
  url: string
  licenseNote: string
  importedAt: string
  transform: string
}

export interface WordDeck {
  id: WordDeckId
  difficulty: Difficulty | 'money'
  sourceIds: string[]
  words: string[]
}

export interface WordDeckSummary {
  id: WordDeckId
  difficulty: Difficulty | 'money'
  count: number
  sourceIds: string[]
}

export interface WordBankSummary {
  totalPlayableWords: number
  deckCounts: Record<WordDeckId, number>
  sourceCount: number
  decks: WordDeckSummary[]
}

// Runtime decks are pooled, no-tag difficulty buckets.
// Green/yellow/red are auto-classified single-word decks; money is phrase-based.
// Base candidates are sourced from CEFRJ vocabulary profile (CC-BY) + hand-curated additions.

export const WORD_BANK_SOURCES: WordSource[] = [
  {
    id: 'cefr-j-olp',
    name: 'Open Language Profiles English datasets from CEFR-J',
    url: 'https://github.com/openlanguageprofiles/olp-en-cefrj',
    licenseNote: 'CEFR-J vocabulary profile is permitted for research and commercial use with citation per repository terms.',
    importedAt: '2026-05-19',
    transform: 'Uppercased, deduped, manually filtered for party play, then pooled and auto-classified into no-tag green/yellow/red/money decks.',
  },
  {
    id: 'curated-party',
    name: 'Curated party-game additions',
    url: 'local:lib/words.ts',
    licenseNote: 'Original short list of common party-game words and phrases authored for this repo.',
    importedAt: '2026-05-19',
    transform: 'Uppercased, deduped, pooled with CEFR candidates, and auto-classified into no-tag green/yellow/red/money decks.',
  },
]

export const greenWords: string[] = [
  'ABLE', 'ACHE', 'ACID', 'AGED', 'AGREE', 'AID', 'ALLY', 'ANGST', 'ANT', 'ANTI',
  'APE', 'APPLE', 'ARCH', 'AREA', 'ARGUE', 'ARM', 'ARMY', 'ASH', 'ATOM', 'AUNT',
  'AXE', 'AXIS', 'BABY', 'BACK', 'BADGE', 'BAG', 'BAKE', 'BALD', 'BALL', 'BAND',
  'BANG', 'BANK', 'BARK', 'BARN', 'BASE', 'BATCH', 'BATH', 'BATHE', 'BAY', 'BEACH',
  'BEAK', 'BEAM', 'BEAN', 'BEANS', 'BEAR', 'BEARD', 'BEAST', 'BEAT', 'BEE', 'BEEF',
  'BEER', 'BEG', 'BEING', 'BELL', 'BELT', 'BENCH', 'BEND', 'BENT', 'BIKE', 'BILL',
  'BIN', 'BIND', 'BIO', 'BIRD', 'BIRTH', 'BITE', 'BLACK', 'BLADE', 'BLAME', 'BLANK',
  'BLAST', 'BLAZE', 'BLEED', 'BLEND', 'BLESS', 'BLIMP', 'BLIND', 'BLINK', 'BLISS', 'BLOCK',
  'BLOG', 'BLONDE', 'BLOOD', 'BLOOM', 'BLOW', 'BLUE', 'BLUR', 'BLURT', 'BLUSH', 'BOARD',
  'BOAST', 'BOAT', 'BODY', 'BOIL', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BONY', 'BOOK',
  'BOOM', 'BOOST', 'BOOT', 'BOOTH', 'BORE', 'BOSS', 'BOUNCE', 'BOUND', 'BOWL', 'BOX',
  'BRA', 'BRAG', 'BRAIN', 'BRAKE', 'BRANCH', 'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK',
  'BREAST', 'BREATH', 'BREATHE', 'BREED', 'BREEZE', 'BRICK', 'BRIDE', 'BRIDGE', 'BRIEF', 'BRIGHT',
  'BRING', 'BROAD', 'BRONZE', 'BROOK', 'BROOM', 'BROWN', 'BROWNIE', 'BROWSE', 'BRUISE', 'BRUSH',
  'BUILD', 'BULB', 'BULL', 'BUM', 'BUMP', 'BUNCH', 'BURN', 'BURST', 'BURY', 'BUS',
  'BUSH', 'BUST', 'BUYER', 'BUZZ', 'BYE', 'CAGE', 'CAKE', 'CALF', 'CALL', 'CAMP',
  'CANE', 'CANOE', 'CAR', 'CARD', 'CARE', 'CARVE', 'CASE', 'CASH', 'CAST', 'CAT',
  'CATCH', 'CAUSE', 'CAVE', 'CEASE', 'CELL', 'CENT', 'CHAIN', 'CHAIR', 'CHANGE', 'CHAOS',
  'CHARGE', 'CHARM', 'CHASE', 'CHAT', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER', 'CHEESE',
  'CHEF', 'CHEQUE', 'CHESS', 'CHEST', 'CHEW', 'CHIEF', 'CHILD', 'CHIN', 'CHIP', 'CHIRP',
  'CHOICE', 'CHOIR', 'CHOKE', 'CHOOSE', 'CHOP', 'CHUNK', 'CHURCH', 'CLAIM', 'CLAM', 'CLAP',
  'CLASS', 'CLAUSE', 'CLEAN', 'CLEAR', 'CLERK', 'CLICK', 'CLIENT', 'CLIFF', 'CLIMB', 'CLIP',
  'CLOCK', 'CLOG', 'CLONE', 'CLOSE', 'CLOTH', 'CLOUD', 'CLOWN', 'CLUB', 'CLUE', 'COACH',
  'COAL', 'COARSE', 'COAST', 'COAT', 'COD', 'CODE', 'COFFEE', 'COIN', 'COKE', 'COLA',
  'COMA', 'COMB', 'COME', 'CONE', 'COOK', 'COOKIE', 'COP', 'COPE', 'COPY', 'CORE',
  'CORN', 'COST', 'COUCH', 'COUGH', 'COUNT', 'COURSE', 'COURT', 'COW', 'CRAB', 'CRACK',
  'CRAFT', 'CRASH', 'CRAWL', 'CRAYON', 'CREAM', 'CREASE', 'CREATE', 'CREEK', 'CREW', 'CRIME',
  'CRISP', 'CROP', 'CROSS', 'CROW', 'CROWD', 'CROWN', 'CRUEL', 'CRUISE', 'CRUSH', 'CUBE',
  'CUFF', 'CUP', 'CURE', 'CURL', 'CURSE', 'CURVE', 'CUTE', 'DAD', 'DAFT', 'DAMP',
  'DARE', 'DASH', 'DATA', 'DATE', 'DAWN', 'DAZE', 'DEAF', 'DEAL', 'DEATH', 'DEBT',
  'DECK', 'DEED', 'DEEM', 'DEER', 'DEFY', 'DENSE', 'DENY', 'DEPTH', 'DESK', 'DIAL',
  'DIET', 'DIME', 'DIRT', 'DISH', 'DIVE', 'DNA', 'DOC', 'DOCK', 'DOG', 'DOLL',
  'DOOM', 'DOOR', 'DORM', 'DOSE', 'DOUBT', 'DOVE', 'DOWN', 'DOZE', 'DRAG', 'DRAIN',
  'DRAW', 'DREAD', 'DREAM', 'DRESS', 'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROOP', 'DROP',
  'DROUGHT', 'DROWN', 'DRUG', 'DRUM', 'DUCK', 'DUDE', 'DUE', 'DUEL', 'DUMB', 'DUMP',
  'DUNE', 'DUST', 'DUTY', 'DVD', 'DWARF', 'DYE', 'EAGLE', 'EAR', 'EARN', 'EARTH',
  'EASE', 'EAST', 'EASY', 'ECHO', 'ECO', 'EDGE', 'EDIT', 'EGG', 'ENVY', 'ERA',
  'EURO', 'EVEN', 'EVIL', 'EXAM', 'EXIT', 'EYE', 'FACE', 'FACT', 'FADE', 'FAIL',
  'FAINT', 'FAITH', 'FAKE', 'FALL', 'FALSE', 'FAME', 'FAMILY', 'FAR', 'FARE', 'FARM',
  'FAT', 'FATE', 'FAULT', 'FEAR', 'FEAST', 'FEAT', 'FEE', 'FEED', 'FEEL', 'FERN',
  'FETCH', 'FIELD', 'FIERCE', 'FIFTH', 'FIGHT', 'FILE', 'FILL', 'FILM', 'FIND', 'FIRE',
  'FIRM', 'FIRST', 'FISH', 'FLAG', 'FLAME', 'FLAP', 'FLASH', 'FLAW', 'FLAX', 'FLEA',
  'FLEE', 'FLEET', 'FLESH', 'FLIGHT', 'FLIP', 'FLOAT', 'FLOCK', 'FLOOD', 'FLOOR', 'FLOUR',
  'FLOW', 'FLU', 'FLUENT', 'FLUID', 'FLUNK', 'FLUTE', 'FOG', 'FOLD', 'FOLK', 'FOND',
  'FOOD', 'FOOL', 'FOOT', 'FORCE', 'FORK', 'FORM', 'FOUL', 'FOUND', 'FOX', 'FRAME',
  'FRANK', 'FRAUD', 'FREAK', 'FREEZE', 'FRESH', 'FRIDGE', 'FRIED', 'FRIEND', 'FRIGHT', 'FROG',
  'FRONT', 'FROST', 'FRUIT', 'FRY', 'FUDGE', 'FUEL', 'FUME', 'FUN', 'FUND', 'FUNK',
  'FUR', 'FUSS', 'GAIN', 'GALA', 'GALL', 'GAME', 'GANG', 'GAP', 'GARDEN', 'GAS',
  'GASP', 'GATE', 'GAZE', 'GEAR', 'GENE', 'GENRE', 'GERM', 'GHOST', 'GIANT', 'GIFT',
  'GIRL', 'GIVE', 'GLAD', 'GLARE', 'GLASS', 'GLEAM', 'GLEE', 'GLIDE', 'GLIMPSE', 'GLINT',
  'GLOBE', 'GLOVE', 'GLOW', 'GOAL', 'GOAT', 'GOD', 'GOLD', 'GOLF', 'GOODS', 'GORGE',
  'GOWN', 'GRAB', 'GRACE', 'GRADE', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP',
  'GRASS', 'GRAVE', 'GREAT', 'GREEN', 'GREET', 'GRIEF', 'GRIEVE', 'GRILL', 'GRIM', 'GRIN',
  'GRIP', 'GROOM', 'GROSS', 'GROUND', 'GROUP', 'GROW', 'GROWTH', 'GUARD', 'GUESS', 'GUEST',
  'GUIDE', 'GUILT', 'GULP', 'GUM', 'GUN', 'GUTS', 'GUY', 'GYM', 'HAIL', 'HAIR',
  'HALF', 'HALL', 'HAM', 'HAND', 'HANG', 'HAPPY', 'HARM', 'HARP', 'HASTE', 'HAT',
  'HATCH', 'HATE', 'HAUNT', 'HAWK', 'HAY', 'HEAD', 'HEAL', 'HEALTH', 'HEAP', 'HEAR',
  'HEART', 'HEAT', 'HEDGE', 'HEEL', 'HEIGHT', 'HELP', 'HEMP', 'HERB', 'HERD', 'HERO',
  'HIDE', 'HIKE', 'HILL', 'HINT', 'HIP', 'HIRE', 'HIV', 'HOLD', 'HOLE', 'HOLY',
  'HOME', 'HONE', 'HOOK', 'HOPE', 'HORN', 'HORSE', 'HOST', 'HOT', 'HOUR', 'HOUSE',
  'HUG', 'HUNT', 'HURT', 'HUSH', 'HUT', 'ICE', 'ICON', 'ICY', 'IDEA', 'IDLE',
  'IDOL', 'ILL', 'INCH', 'INK', 'IRON', 'ISLE', 'ISSUE', 'ITCH', 'ITEM', 'JADE',
  'JAM', 'JAR', 'JAW', 'JAZZ', 'JEANS', 'JET', 'JOB', 'JOG', 'JOIN', 'JOINT',
  'JOKE', 'JOY', 'JUDGE', 'JUDO', 'JUG', 'JUICE', 'JULY', 'JUMP', 'JUNE', 'JUNK',
  'JURY', 'KAYAK', 'KEEP', 'KELP', 'KEY', 'KICK', 'KID', 'KILL', 'KILO', 'KIND',
  'KING', 'KISS', 'KIT', 'KITCHEN', 'KITE', 'KNEE', 'KNEEL', 'KNIFE', 'KNIGHT', 'KNIT',
  'KNOCK', 'KNOT', 'KNOW', 'KNOWN', 'LAB', 'LACK', 'LADY', 'LAKE', 'LAMB', 'LAME',
  'LAMP', 'LAND', 'LANE', 'LAP', 'LARGE', 'LARK', 'LATTE', 'LAUGH', 'LAUNCH', 'LAVA',
  'LAW', 'LAWN', 'LAYER', 'LAZY', 'LEAD', 'LEAF', 'LEAGUE', 'LEAK', 'LEAN', 'LEAP',
  'LEARN', 'LEASE', 'LEASH', 'LEAVE', 'LEEK', 'LEG', 'LEND', 'LENGTH', 'LIAR', 'LICK',
  'LID', 'LIFE', 'LIFT', 'LILY', 'LIMB', 'LIMP', 'LINE', 'LING', 'LINK', 'LION',
  'LIP', 'LIST', 'LOAD', 'LOAF', 'LOAN', 'LOCK', 'LODGE', 'LOG', 'LOGO', 'LOOK',
  'LOOSE', 'LOSE', 'LOSS', 'LOST', 'LOT', 'LOVE', 'LOW', 'LOYAL', 'LUCK', 'LUNCH',
  'LUNG', 'LUSH', 'LYNX', 'MAD', 'MAIL', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MAN',
  'MAP', 'MARCH', 'MARK', 'MARSH', 'MASH', 'MASK', 'MASS', 'MATCH', 'MATE', 'MAX',
  'MAY', 'MAYOR', 'MEAL', 'MEAN', 'MEANS', 'MEAT', 'MEET', 'MELT', 'MEND', 'MENU',
  'MERE', 'MERGE', 'MESS', 'MIDST', 'MILE', 'MILK', 'MILL', 'MIND', 'MINE', 'MINT',
  'MISS', 'MIST', 'MOCK', 'MOM', 'MONEY', 'MONK', 'MONTH', 'MOOD', 'MOON', 'MOOSE',
  'MOSQUE', 'MOSS', 'MOTHER', 'MOUNT', 'MOUNTAIN', 'MOURN', 'MOUSE', 'MOUTH', 'MOVE', 'MOVIE',
  'MUD', 'MUG', 'MULE', 'MUM', 'MUSE', 'MUSIC', 'MYTH', 'NAAN', 'NAIL', 'NAME',
  'NANO', 'NAP', 'NAVY', 'NECK', 'NEED', 'NERVE', 'NET', 'NEWS', 'NICE', 'NIECE',
  'NIGHT', 'NOD', 'NOISE', 'NOON', 'NORTH', 'NOSE', 'NOTE', 'NOUGHT', 'NOUN', 'NURSE',
  'NUT', 'OAK', 'OATH', 'OBEY', 'ODD', 'OIL', 'OILY', 'OMEN', 'ONLY', 'ORAL',
  'OUNCE', 'OVAL', 'OVEN', 'OWE', 'OWL', 'PACE', 'PACK', 'PAD', 'PAGE', 'PAID',
  'PAIN', 'PAINT', 'PAIR', 'PAL', 'PALM', 'PAN', 'PANTS', 'PAPER', 'PARK', 'PART',
  'PARTY', 'PASS', 'PATCH', 'PATH', 'PAUSE', 'PAVE', 'PAW', 'PEA', 'PEACE', 'PEACH',
  'PEAK', 'PEAR', 'PEARL', 'PEAS', 'PEE', 'PEEL', 'PEEP', 'PEER', 'PEG', 'PEN',
  'PET', 'PHASE', 'PHONE', 'PHRASE', 'PICK', 'PIE', 'PIECE', 'PIER', 'PIG', 'PILE',
  'PILL', 'PIN', 'PINE', 'PINK', 'PINT', 'PIPE', 'PIT', 'PITCH', 'PIZZA', 'PLACE',
  'PLAGUE', 'PLAIN', 'PLAN', 'PLANE', 'PLANT', 'PLATE', 'PLAY', 'PLAYER', 'PLEAD', 'PLEASE',
  'PLIERS', 'PLOT', 'PLUCK', 'PLUG', 'PLUM', 'PLUS', 'POEM', 'POET', 'POINT', 'POLE',
  'POLO', 'POND', 'POOL', 'POP', 'PORCH', 'PORK', 'PORT', 'POSE', 'POSH', 'POST',
  'POT', 'POUND', 'POUR', 'PRAISE', 'PRAWN', 'PRAY', 'PRAYER', 'PRESS', 'PRICE', 'PRICK',
  'PRIDE', 'PRIEST', 'PRIME', 'PRINCE', 'PRINT', 'PRIOR', 'PRIZE', 'PRO', 'PROBE', 'PROM',
  'PROMPT', 'PROOF', 'PROSE', 'PROUD', 'PROVE', 'PUB', 'PULL', 'PULSE', 'PUMP', 'PUNCH',
  'PURSE', 'PURSUE', 'PUSH', 'QUAKE', 'QUEEN', 'QUEUE', 'QUICK', 'QUIET', 'QUIT', 'QUIZ',
  'QUOTE', 'RACE', 'RACK', 'RAFT', 'RAG', 'RAGE', 'RAIL', 'RAIN', 'RAISE', 'RAM',
  'RAMP', 'RANGE', 'RANK', 'RAP', 'RARE', 'RASH', 'RAT', 'RATE', 'RAW', 'RAY',
  'REACH', 'REACT', 'READ', 'REAR', 'RED', 'REDO', 'REED', 'REEF', 'REGGAE', 'RELY',
  'RENT', 'RESCUE', 'REST', 'RHYME', 'RHYTHM', 'RIB', 'RICE', 'RID', 'RIDE', 'RIDGE',
  'RIM', 'RING', 'RIP', 'RIPE', 'RISE', 'RISK', 'RITE', 'ROAD', 'ROAM', 'ROAR',
  'ROAST', 'ROB', 'ROCK', 'ROLE', 'ROLL', 'ROOF', 'ROOM', 'ROOT', 'ROPE', 'ROSE',
  'ROSY', 'ROUGH', 'ROUND', 'ROUTE', 'ROW', 'ROYAL', 'RUB', 'RUG', 'RUIN', 'RULE',
  'RUSH', 'SACK', 'SAD', 'SAG', 'SAGE', 'SAIL', 'SAKE', 'SALE', 'SALT', 'SAND',
  'SAUCE', 'SAVE', 'SAW', 'SCALE', 'SCAN', 'SCAR', 'SCARE', 'SCARF', 'SCENE', 'SCENT',
  'SCHEME', 'SCHOOL', 'SCOLD', 'SCOPE', 'SCORE', 'SCRATCH', 'SCREAM', 'SCREEN', 'SCREW', 'SCRIPT',
  'SCROOGE', 'SCYTHE', 'SEA', 'SEAL', 'SEARCH', 'SEAT', 'SEED', 'SEEK', 'SEEM', 'SEIZE',
  'SELF', 'SELL', 'SEND', 'SENSE', 'SERVE', 'SEW', 'SEX', 'SHADE', 'SHAKE', 'SHAME',
  'SHAPE', 'SHARE', 'SHARK', 'SHARP', 'SHAVE', 'SHED', 'SHEEP', 'SHEER', 'SHEET', 'SHELF',
  'SHELL', 'SHIELD', 'SHIFT', 'SHINE', 'SHIRT', 'SHOE', 'SHOOT', 'SHOP', 'SHORE', 'SHORT',
  'SHOT', 'SHOUT', 'SHOW', 'SHRIMP', 'SHRINK', 'SHRUG', 'SHUT', 'SHY', 'SICK', 'SIDE',
  'SIEVE', 'SIGH', 'SIGHT', 'SIGN', 'SILK', 'SING', 'SINK', 'SIR', 'SITE', 'SIZE',
  'SKATE', 'SKETCH', 'SKI', 'SKIING', 'SKILL', 'SKIM', 'SKIN', 'SKIP', 'SKIRT', 'SKUNK',
  'SKY', 'SLAM', 'SLANG', 'SLAP', 'SLASH', 'SLED', 'SLEEP', 'SLEEVE', 'SLICE', 'SLIDE',
  'SLIGHT', 'SLIM', 'SLIP', 'SLOPE', 'SLOT', 'SMALL', 'SMART', 'SMASH', 'SMELL', 'SMILE',
  'SMITH', 'SMOKE', 'SMOOTH', 'SNACK', 'SNAIL', 'SNAKE', 'SNAP', 'SNEAK', 'SNEER', 'SNEEZE',
  'SNIFF', 'SNORE', 'SNOW', 'SOAK', 'SOAP', 'SOAR', 'SOB', 'SOCK', 'SODA', 'SOFA',
  'SOIL', 'SOLO', 'SOLVE', 'SON', 'SONG', 'SOOTHE', 'SORE', 'SORT', 'SOUL', 'SOUND',
  'SOUP', 'SOUR', 'SOURCE', 'SOUTH', 'SPA', 'SPACE', 'SPAN', 'SPARE', 'SPARK', 'SPEAK',
  'SPEECH', 'SPEED', 'SPELL', 'SPEND', 'SPHERE', 'SPHINX', 'SPICE', 'SPILL', 'SPIN', 'SPITE',
  'SPLASH', 'SPLIT', 'SPOIL', 'SPONGE', 'SPOON', 'SPORT', 'SPORTS', 'SPOT', 'SPRAY', 'SPREAD',
  'SPRING', 'SPRINT', 'SPUR', 'SPY', 'SQUAD', 'SQUARE', 'SQUASH', 'SQUEEZE', 'STAB', 'STACK',
  'STAFF', 'STAGE', 'STAIN', 'STAIR', 'STAKE', 'STALL', 'STAMP', 'STAND', 'STAR', 'STARE',
  'START', 'STARVE', 'STATE', 'STATUE', 'STAY', 'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP',
  'STEER', 'STEM', 'STEP', 'STERN', 'STEW', 'STICK', 'STIFF', 'STILL', 'STINK', 'STIR',
  'STITCH', 'STOCK', 'STONE', 'STOOL', 'STOP', 'STORE', 'STORM', 'STOVE', 'STRAIN', 'STRAIT',
  'STRAND', 'STRANGE', 'STRAW', 'STREAM', 'STREET', 'STRESS', 'STRETCH', 'STRICT', 'STRIDE', 'STRIKE',
  'STRING', 'STRIP', 'STRIPE', 'STRIVE', 'STROKE', 'STRONG', 'STUCK', 'STUFF', 'STUN', 'STYLE',
  'SUCK', 'SUE', 'SUIT', 'SUM', 'SUN', 'SURF', 'SURGE', 'SWAMP', 'SWAN', 'SWARM',
  'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWELL', 'SWIFT', 'SWIM', 'SWING', 'SWITCH', 'SWORD',
  'TABLE', 'TACK', 'TACO', 'TAG', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TAME', 'TAN',
  'TANK', 'TAP', 'TAPE', 'TASK', 'TASTE', 'TAUNT', 'TAX', 'TAXI', 'TEA', 'TEACH',
  'TEAM', 'TEAR', 'TEASE', 'TEEN', 'TELL', 'TEMPT', 'TEND', 'TENSE', 'TENT', 'TERM',
  'TEST', 'TEXT', 'THANK', 'THANKS', 'THEFT', 'THEME', 'THIEF', 'THIGH', 'THING', 'THINK',
  'THIRD', 'THIRST', 'THORN', 'THOUGHT', 'THREAD', 'THREAT', 'THRILL', 'THROAT', 'THROW', 'THUMB',
  'THUMP', 'TICK', 'TIDE', 'TIDY', 'TIGHT', 'TIGHTS', 'TILE', 'TIME', 'TIN', 'TIP',
  'TIPTOE', 'TIRE', 'TISSUE', 'TOAST', 'TOE', 'TOFFEE', 'TOIL', 'TOLL', 'TOMB', 'TON',
  'TONE', 'TONGUE', 'TOOL', 'TOOTH', 'TORCH', 'TOSS', 'TOUCH', 'TOUGH', 'TOUR', 'TOWN',
  'TOY', 'TRACE', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN', 'TRAINEE', 'TRAIT', 'TRAM', 'TRAMP',
  'TRAP', 'TRASH', 'TRAY', 'TREAD', 'TREAT', 'TREE', 'TREK', 'TREND', 'TRIAL', 'TRIBE',
  'TRICK', 'TRIM', 'TRIO', 'TRIP', 'TRIUMPH', 'TROLL', 'TROOP', 'TRUCK', 'TRUNK', 'TRUST',
  'TRUTH', 'TUB', 'TUBE', 'TUG', 'TUNA', 'TUNE', 'TURN', 'TWIG', 'TWIN', 'TWIST',
  'TYPE', 'UGLY', 'UNDO', 'UNIT', 'UNTIE', 'URGE', 'USER', 'VAGUE', 'VAIN', 'VALUE',
  'VAN', 'VARY', 'VASE', 'VAST', 'VEIN', 'VENUE', 'VERB', 'VERSE', 'VERY', 'VET',
  'VICE', 'VIEW', 'VINE', 'VIRTUE', 'VISA', 'VOICE', 'VOID', 'VOTE', 'VOW', 'VOYAGE',
  'WAGE', 'WAIST', 'WAIT', 'WAKE', 'WALK', 'WALL', 'WANT', 'WAR', 'WARD', 'WARMTH',
  'WARN', 'WASH', 'WASP', 'WASTE', 'WATCH', 'WATER', 'WAVE', 'WAX', 'WEALTH', 'WEAR',
  'WEAVE', 'WEB', 'WED', 'WEED', 'WEEK', 'WEEP', 'WEIGH', 'WEIGHT', 'WEIRD', 'WELL',
  'WEST', 'WET', 'WHALE', 'WHEAT', 'WHEEL', 'WHILE', 'WHIP', 'WHISK', 'WHITE', 'WHOLE',
  'WIDTH', 'WIFE', 'WILL', 'WIND', 'WINE', 'WING', 'WINK', 'WIPE', 'WIRE', 'WISH',
  'WIT', 'WITCH', 'WOLF', 'WOMAN', 'WOOD', 'WOOL', 'WORD', 'WORK', 'WORLD', 'WORM',
  'WORN', 'WORSE', 'WORST', 'WORTH', 'WOUND', 'WRAP', 'WRECK', 'WRENCH', 'WRIST', 'WRITE',
  'WRONG', 'YACHT', 'YARD', 'YAWN', 'YEAR', 'YEARN', 'YELL', 'YIELD', 'YOGA', 'YOUNG',
  'YOUTH', 'ZIP', 'ZOMBIE', 'ZONE', 'ZOO', 'ZOOM',
]

export const yellowWords: string[] = [
  'ABANDON', 'ABNORMAL', 'ABOLISH', 'ABOVE', 'ABSENCE', 'ABSENT', 'ABSENTEE', 'ABSOLUTE', 'ABSORB', 'ABSTRACT',
  'ABSURD', 'ABUNDANT', 'ABUSE', 'ABYSS', 'ACADEMY', 'ACCENT', 'ACCEPT', 'ACCESS', 'ACCIDENT', 'ACCOMPLISH',
  'ACCORDION', 'ACCOUNT', 'ACCOUNTANT', 'ACCURATE', 'ACCUSE', 'ACCUSTOM', 'ACHIEVE', 'ACORN', 'ACQUIRE', 'ACROBAT',
  'ACTION', 'ACTIVE', 'ACTOR', 'ACTRESS', 'ACTUAL', 'ACUTE', 'ADAPT', 'ADDICT', 'ADDICTED', 'ADDRESS',
  'ADDRESSEE', 'ADEQUATE', 'ADJECTIVE', 'ADJUST', 'ADMIRE', 'ADMIT', 'ADOPT', 'ADOPTED', 'ADORE', 'ADORN',
  'ADULT', 'ADVANCE', 'ADVANCED', 'ADVANTAGE', 'ADVENT', 'ADVENTURE', 'ADVERB', 'ADVERBIAL', 'ADVERSE', 'ADVERT',
  'ADVERTISE', 'ADVICE', 'ADVISE', 'AEROBICS', 'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AFTERNOON', 'AGELESS',
  'AGENCY', 'AGENDA', 'AGENT', 'AGGRESSIVE', 'AGONY', 'AIRCRAFT', 'AIRCREW', 'AIRLINE', 'AIRPORT', 'AISLE',
  'ALARM', 'ALBUM', 'ALCHEMY', 'ALCOHOL', 'ALERT', 'ALIEN', 'ALIKE', 'ALIVE', 'ALLERGIC', 'ALLEY',
  'ALLOW', 'ALMOND', 'ALONE', 'ALPHABET', 'ALRIGHT', 'ALTAR', 'ALTER', 'ALTERNATE', 'ALTITUDE', 'AMAZE',
  'AMAZED', 'AMAZING', 'AMBIGUOUS', 'AMBITIOUS', 'AMMONIA', 'AMOUNT', 'AMPLE', 'AMPLIFIER', 'AMPLIFY', 'AMPLITUDE',
  'AMUSE', 'AMUSED', 'AMUSING', 'ANALOGY', 'ANALYST', 'ANARCHY', 'ANCESTOR', 'ANCHOR', 'ANCHORAGE', 'ANCHORMAN',
  'ANCHOVY', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY', 'ANGUISH', 'ANIMAL', 'ANIMATE', 'ANKLE', 'ANNOUNCE',
  'ANNOY', 'ANNOYED', 'ANNUAL', 'ANOMALY', 'ANSWER', 'ANTIQUE', 'ANTONYM', 'ANXIETY', 'ANXIOUS', 'APOSTROPHE',
  'APPARENT', 'APPEAL', 'APPEAR', 'APPETITE', 'APPLAUD', 'APPLAUSE', 'APPLICANT', 'APPOINT', 'APPRECIATE', 'APPROACH',
  'APPROVAL', 'APPROVE', 'APRIL', 'APRON', 'AQUARIUM', 'ARCADE', 'ARCHERY', 'ARCHITECT', 'ARCTIC', 'ARENA',
  'ARISE', 'ARMCHAIR', 'ARMED', 'ARMFUL', 'AROUSE', 'ARRANGE', 'ARREST', 'ARRIVAL', 'ARRIVE', 'ARROGANT',
  'ARROW', 'ARTERY', 'ARTICLE', 'ARTIST', 'ARTISTIC', 'ARTISTRY', 'ASHAMED', 'ASLEEP', 'ASPECT', 'ASPIRE',
  'ASPIRIN', 'ASSAULT', 'ASSEMBLE', 'ASSEMBLY', 'ASSERT', 'ASSESS', 'ASSIGN', 'ASSIST', 'ASSISTANT', 'ASSOCIATE',
  'ASSUME', 'ASSURE', 'ASTEROID', 'ASTONISH', 'ASTRONAUT', 'ATHLETE', 'ATHLETIC', 'ATHLETICS', 'ATLANTIC', 'ATMOSPHERE',
  'ATOMIC', 'ATROPHY', 'ATTACH', 'ATTACHED', 'ATTACK', 'ATTAIN', 'ATTEMPT', 'ATTEND', 'ATTENTIVE', 'ATTIC',
  'ATTITUDE', 'ATTRACT', 'ATTRACTIVE', 'ATTRIBUTE', 'AUBERGINE', 'AUCTION', 'AUCTIONEER', 'AUDIO', 'AUDIT', 'AUGUST',
  'AUTHOR', 'AUTUMN', 'AVALANCHE', 'AVENUE', 'AVERAGE', 'AVOCADO', 'AVOID', 'AWAIT', 'AWAKE', 'AWARD',
  'AWARE', 'AWESOME', 'AWFUL', 'AWKWARD', 'BABOON', 'BABYSIT', 'BACKACHE', 'BACKGROUND', 'BACKPACK', 'BACKPACKER',
  'BACKUP', 'BACKYARD', 'BACON', 'BADMINTON', 'BAGEL', 'BAGGAGE', 'BAKER', 'BAKERY', 'BAKING', 'BALANCE',
  'BALANCED', 'BALCONY', 'BALKY', 'BALLAD', 'BALLET', 'BALLOON', 'BALLOT', 'BAMBOO', 'BANANA', 'BANDAGE',
  'BANDIT', 'BANJO', 'BANKER', 'BANKING', 'BANKRUPT', 'BANKRUPTCY', 'BANQUET', 'BARBECUE', 'BARBER', 'BARBERSHOP',
  'BARGAIN', 'BARLEY', 'BARMAN', 'BARREL', 'BARREN', 'BARRIER', 'BARTENDER', 'BASEBALL', 'BASIC', 'BASIN',
  'BASIS', 'BASKET', 'BASKETBALL', 'BATHHOUSE', 'BATHROOM', 'BATTERY', 'BATTLE', 'BEAGLE', 'BEARING', 'BEAUTIFUL',
  'BEAUTIFY', 'BEAUTY', 'BEAVER', 'BECOME', 'BEDROOM', 'BEDSIDE', 'BEGIN', 'BEGINNER', 'BEGINNING', 'BEHALF',
  'BEHAVE', 'BELIEF', 'BELIEVE', 'BELLOW', 'BELLY', 'BELONG', 'BELONGINGS', 'BELOVED', 'BENEFIT', 'BERRY',
  'BESTOW', 'BESTSELLER', 'BETRAY', 'BETTER', 'BEWILDER', 'BICYCLE', 'BIDDING', 'BIKINI', 'BILINGUAL', 'BILLION',
  'BIRDCAGE', 'BIRTHDAY', 'BIRTHPLACE', 'BISCUIT', 'BISHOP', 'BISON', 'BITTER', 'BIZARRE', 'BLACKBOARD', 'BLACKSMITH',
  'BLANKET', 'BLESSING', 'BLIZZARD', 'BLOGGER', 'BLOODSTREAM', 'BLOODY', 'BLOOMING', 'BLOSSOM', 'BLUEBERRY', 'BLUEBIRD',
  'BOBCAT', 'BOILED', 'BOILING', 'BOMBARD', 'BOMBER', 'BOMBING', 'BONUS', 'BOOKCASE', 'BOOKING', 'BOOKISH',
  'BOOKLET', 'BOOKMARK', 'BOOKSHELF', 'BOOKSHOP', 'BOOKSTORE', 'BORDER', 'BORED', 'BOREDOM', 'BORING', 'BOSSY',
  'BOTANY', 'BOTHER', 'BOTHERED', 'BOTHERSOME', 'BOTTLE', 'BOTTOM', 'BOULDER', 'BOURBON', 'BOWLING', 'BOXER',
  'BOXING', 'BOYFRIEND', 'BRACELET', 'BRACKET', 'BRAINSTORM', 'BRAVERY', 'BREAKABLE', 'BREAKDOWN', 'BREAKFAST', 'BREAKTHROUGH',
  'BREAKUP', 'BREATHLESS', 'BREEDING', 'BREEZY', 'BREWERY', 'BRILLIANT', 'BROADBAND', 'BROADCAST', 'BROADEN', 'BROCCOLI',
  'BROCHURE', 'BROKEN', 'BROTHER', 'BROWSER', 'BUBBLE', 'BUCKET', 'BUDDY', 'BUDGET', 'BUILDER', 'BUILDING',
  'BULIMIA', 'BULLET', 'BULLETIN', 'BULLY', 'BUMPER', 'BURDEN', 'BURDENSOME', 'BUREAU', 'BURGER', 'BURGLAR',
  'BURGLARY', 'BURGLE', 'BURIAL', 'BURNING', 'BURRITO', 'BUSTLE', 'BUSTLING', 'BUTCHER', 'BUTTER', 'BUTTERFLY',
  'BUTTON', 'CABBAGE', 'CABIN', 'CABINET', 'CABLE', 'CACTUS', 'CALCULATE', 'CALENDAR', 'CALLER', 'CAMEL',
  'CAMERA', 'CAMPAIGN', 'CAMPING', 'CAMPSITE', 'CAMPUS', 'CANAL', 'CANARY', 'CANCEL', 'CANCER', 'CANDIDATE',
  'CANDLE', 'CANDY', 'CANNED', 'CANNONBALL', 'CANON', 'CANTEEN', 'CANVAS', 'CANYON', 'CAPABLE', 'CAPITAL',
  'CAPSULE', 'CAPTAIN', 'CAPTION', 'CAPTIVE', 'CAPTURE', 'CARAMEL', 'CARAVAN', 'CARBON', 'CARDBOARD', 'CARDIGAN',
  'CAREER', 'CAREFREE', 'CAREFUL', 'CARELESS', 'CARING', 'CARNIVAL', 'CARPENTER', 'CARPET', 'CARPOOL', 'CARRIAGE',
  'CARROT', 'CARRY', 'CARTON', 'CARTOON', 'CASCADE', 'CASHEW', 'CASHIER', 'CASHPOINT', 'CASSETTE', 'CASTLE',
  'CASUAL', 'CATALYST', 'CATCHY', 'CATERING', 'CATHARSIS', 'CATHEDRAL', 'CATTLE', 'CAUTION', 'CAUTIOUS', 'CEILING',
  'CELEBRATE', 'CELERY', 'CELLAR', 'CELLIST', 'CELLO', 'CENTAUR', 'CENTIGRADE', 'CENTRAL', 'CENTURY', 'CEREAL',
  'CERTAIN', 'CERTAINTY', 'CERTIFY', 'CHAIRMAN', 'CHALLENGE', 'CHAMPAGNE', 'CHAMPION', 'CHANCE', 'CHANCELLOR', 'CHANNEL',
  'CHAOTIC', 'CHAPEL', 'CHAPTER', 'CHARACTER', 'CHARIOT', 'CHARMING', 'CHECKOUT', 'CHECKPOINT', 'CHEEKY', 'CHEERFUL',
  'CHEETAH', 'CHEMIST', 'CHEMISTRY', 'CHERISH', 'CHERISHED', 'CHERRY', 'CHICKEN', 'CHILDISH', 'CHIMNEY', 'CHIMPANZEE',
  'CHIPMUNK', 'CHISEL', 'CHOCOLATE', 'CHOPSTICKS', 'CHRISTIAN', 'CHUCKLE', 'CIGARETTE', 'CINEMA', 'CINNAMON', 'CIPHER',
  'CIRCLE', 'CIRCUIT', 'CIRCUITRY', 'CIRCULAR', 'CIRCUS', 'CITADEL', 'CITIZEN', 'CITY', 'CITYWIDE', 'CIVIL',
  'CLARIFY', 'CLASSIC', 'CLASSIFY', 'CLASSMATE', 'CLASSROOM', 'CLEANER', 'CLEVER', 'CLIMATE', 'CLIMBER', 'CLIMBING',
  'CLINIC', 'CLOSED', 'CLOSURE', 'CLOTHES', 'CLOTHING', 'CLOUDY', 'CLUMSY', 'COACHING', 'COASTAL', 'COASTER',
  'COASTLINE', 'COBRA', 'COCKTAIL', 'COCOA', 'COCONUT', 'COFFIN', 'COHERENT', 'COINCIDE', 'COLLAPSE', 'COLLAR',
  'COLLEAGUE', 'COLLECT', 'COLLECTOR', 'COLLEGE', 'COLON', 'COLONIAL', 'COLUMN', 'COLUMNIST', 'COMBINE', 'COMEDIAN',
  'COMEDY', 'COMET', 'COMFORT', 'COMIC', 'COMMA', 'COMMAND', 'COMMANDER', 'COMMENT', 'COMMERCE', 'COMMIT',
  'COMMITTEE', 'COMMON', 'COMMUTE', 'COMPANION', 'COMPANY', 'COMPARE', 'COMPASS', 'COMPENSATE', 'COMPETE', 'COMPETENT',
  'COMPILE', 'COMPLAIN', 'COMPLAINT', 'COMPLETE', 'COMPLEX', 'COMPLEXION', 'COMPLICATE', 'COMPONENT', 'COMPOSE', 'COMPOSER',
  'COMPOUND', 'COMPRESS', 'COMPROMISE', 'COMPUTE', 'COMPUTER', 'CONCEAL', 'CONCEDE', 'CONCEIT', 'CONCEIVE', 'CONCEPT',
  'CONCERN', 'CONCERNED', 'CONCERT', 'CONCLUDE', 'CONCRETE', 'CONDEMN', 'CONDUCT', 'CONDUCTOR', 'CONFESS', 'CONFIDENT',
  'CONFINE', 'CONFIRM', 'CONFLICT', 'CONFRONT', 'CONFUSE', 'CONFUSED', 'CONFUSING', 'CONNECT', 'CONQUER', 'CONQUEST',
  'CONSCIOUS', 'CONSENSUS', 'CONSENT', 'CONSIDER', 'CONSIST', 'CONSISTENT', 'CONSOLE', 'CONSONANT', 'CONSTANT', 'CONSTITUTE',
  'CONSTRUCT', 'CONSULT', 'CONSULTANT', 'CONSUME', 'CONSUMER', 'CONTACT', 'CONTAIN', 'CONTAINER', 'CONTEMPT', 'CONTENT',
  'CONTEST', 'CONTEXT', 'CONTINENT', 'CONTINUAL', 'CONTINUE', 'CONTINUOUS', 'CONTRACT', 'CONTRADICT', 'CONTRARY', 'CONTRAST',
  'CONTRIBUTE', 'CONTROL', 'CONVENIENT', 'CONVERSE', 'CONVERT', 'CONVEY', 'CONVINCE', 'CONVINCED', 'COOKER', 'COOKING',
  'COOLER', 'COOPERATE', 'COPPER', 'COPYRIGHT', 'CORAL', 'CORDUROY', 'CORNER', 'CORNET', 'CORONA', 'CORPORAL',
  'CORPORATE', 'CORRECT', 'CORRESPOND', 'CORRIDOR', 'CORRUPT', 'COSTLY', 'COSTUME', 'COTTAGE', 'COTTON', 'COUNCIL',
  'COUNTER', 'COUNTLESS', 'COUNTRY', 'COUNTRYMAN', 'COUNTY', 'COUPLE', 'COURAGE', 'COURAGEOUS', 'COURGETTE', 'COURIER',
  'COURTESY', 'COURTROOM', 'COUSIN', 'COVER', 'COWARD', 'COWARDLY', 'COWBOY', 'CRACKER', 'CRAFTSMAN', 'CRATER',
  'CRAZY', 'CREATIVE', 'CREATOR', 'CREATURE', 'CREDIT', 'CREEPY', 'CRICKET', 'CRIMINAL', 'CRIPPLE', 'CRISIS',
  'CRITIC', 'CROCODILE', 'CROISSANT', 'CROSSING', 'CROSSROADS', 'CROWBAR', 'CROWDED', 'CRUELTY', 'CUBISM', 'CUCUMBER',
  'CULTIVATE', 'CULTURAL', 'CULTURE', 'CUPBOARD', 'CURIOUS', 'CURLING', 'CURLY', 'CURRENCY', 'CURRENT', 'CURRY',
  'CURSOR', 'CURTAIN', 'CUSHION', 'CUSTARD', 'CUSTOM', 'CUSTOMER', 'CUSTOMS', 'CYBERCRIME', 'CYBERPET', 'CYBERSPACE',
  'CYBORG', 'CYCLE', 'CYCLING', 'CYCLIST', 'CYCLONE', 'DADDY', 'DAILY', 'DAISY', 'DAMAGE', 'DAMAGED',
  'DANCE', 'DANCER', 'DANCING', 'DANDELION', 'DANGER', 'DANGEROUS', 'DARLING', 'DATABASE', 'DATED', 'DATING',
  'DAUGHTER', 'DAYLIGHT', 'DAYTIME', 'DAZZLE', 'DEADLINE', 'DEADLY', 'DEALER', 'DEBATE', 'DEBIT', 'DEBRIS',
  'DECADE', 'DECAY', 'DECEIVE', 'DECEMBER', 'DECENT', 'DECEPTIVE', 'DECIDE', 'DECISIVE', 'DECLARE', 'DECLINE',
  'DECORATE', 'DECREASE', 'DEDICATE', 'DEDUCE', 'DEFEAT', 'DEFEND', 'DEFENDER', 'DEFICIT', 'DEFINE', 'DEFINITE',
  'DELAY', 'DELEGATE', 'DELETE', 'DELICATE', 'DELICIOUS', 'DELIGHT', 'DELIGHTED', 'DELIGHTFUL', 'DELIVER', 'DEMAND',
  'DEMANDING', 'DEMOLISH', 'DENIM', 'DENTAL', 'DENTIST', 'DEPART', 'DEPARTURE', 'DEPEND', 'DEPENDENT', 'DEPOSIT',
  'DEPRESSED', 'DEPRESSING', 'DEPRIVE', 'DEPUTY', 'DERIVE', 'DESCEND', 'DESCRIBE', 'DESERT', 'DESERVE', 'DESIGN',
  'DESIGNER', 'DESIRE', 'DESKTOP', 'DESPAIR', 'DESPERATE', 'DESPISE', 'DESSERT', 'DESTINY', 'DESTROY', 'DETACH',
  'DETAIL', 'DETAILED', 'DETECT', 'DETECTIVE', 'DETERMINE', 'DEVASTATE', 'DEVELOP', 'DEVICE', 'DEVIL', 'DEVOTE',
  'DEVOTED', 'DIAGRAM', 'DIAMETER', 'DIAMOND', 'DIAPER', 'DIARY', 'DICTATOR', 'DIFFER', 'DIFFERENT', 'DIFFICULT',
  'DIGEST', 'DIGITAL', 'DIGNIFY', 'DILEMMA', 'DILIGENT', 'DINGO', 'DINNER', 'DINOSAUR', 'DIOXIDE', 'DIPHTHERIA',
  'DIPLOMA', 'DIPLOMAT', 'DIRECT', 'DIRECTOR', 'DIRTY', 'DISABLE', 'DISABLED', 'DISAGREE', 'DISAPPEAR', 'DISAPPOINT',
  'DISAPPROVE', 'DISASTER', 'DISASTROUS', 'DISCHARGE', 'DISCIPLE', 'DISCIPLINE', 'DISCO', 'DISCOMFORT', 'DISCONNECT', 'DISCORD',
  'DISCOUNT', 'DISCOURAGE', 'DISCOVER', 'DISCREDIT', 'DISCUSS', 'DISEASE', 'DISGRACE', 'DISGUISE', 'DISGUSTING', 'DISHONEST',
  'DISHWASHER', 'DISLIKE', 'DISMISS', 'DISORDER', 'DISPLACE', 'DISPLAY', 'DISPOSAL', 'DISPUTE', 'DISREGARD', 'DISRUPT',
  'DISSIDENT', 'DISSOLVE', 'DISTANT', 'DISTRACT', 'DISTRIBUTE', 'DISTRICT', 'DISTURB', 'DIVER', 'DIVERSE', 'DIVERT',
  'DIVIDE', 'DIVIDED', 'DIVINE', 'DIVING', 'DIVORCE', 'DIVORCED', 'DIZZY', 'DOCTOR', 'DOGMA', 'DOLLAR',
  'DOLPHIN', 'DOMESTIC', 'DOMINATE', 'DONATE', 'DONKEY', 'DONUT', 'DOORKEEPER', 'DOORWAY', 'DOUBLE', 'DOUBTFUL',
  'DOWNFALL', 'DOWNLOAD', 'DOWNSIZE', 'DOWNSTAIRS', 'DOWNWARD', 'DOWRY', 'DOZEN', 'DRAGON', 'DRAGONFLY', 'DRAMA',
  'DRAMATIC', 'DRAPERY', 'DRAWER', 'DRAWING', 'DREADFUL', 'DREAMY', 'DRESSED', 'DRINKABLE', 'DRIVER', 'DROPOUT',
  'DRUGSTORE', 'DUMPLING', 'DUNGEON', 'DUPLICATE', 'DUSTBIN', 'DUSTY', 'DUVET', 'DYNAMIC', 'DYNASTY', 'DYSTOPIA',
  'EAGER', 'EARACHE', 'EARLY', 'EARNEST', 'EARNINGS', 'EARRING', 'EARTHQUAKE', 'EASEL', 'EASTERN', 'ECLIPSE',
  'ECONOMY', 'ECSTASY', 'ECSTATIC', 'EDITOR', 'EDUCATE', 'EFFECT', 'EFFECTIVE', 'EFFORT', 'ELBOW', 'ELDERLY',
  'ELECT', 'ELECTIVE', 'ELECTRIC', 'ELECTRON', 'ELEGANT', 'ELEPHANT', 'ELITE', 'ELOQUENT', 'EMAIL', 'EMBARRASS',
  'EMBASSY', 'EMBRACE', 'EMERGE', 'EMPEROR', 'EMPHASIS', 'EMPIRE', 'EMPLOY', 'EMPLOYEE', 'EMPLOYER', 'EMPTY',
  'ENABLE', 'ENCLOSE', 'ENCOUNTER', 'ENCOURAGE', 'ENDANGER', 'ENDING', 'ENDLESS', 'ENDORSE', 'ENDURE', 'ENDURING',
  'ENEMY', 'ENERGY', 'ENFORCE', 'ENGAGE', 'ENGAGED', 'ENGINE', 'ENGINEER', 'ENGLISHMAN', 'ENGULF', 'ENHANCE',
  'ENJOY', 'ENJOYABLE', 'ENNUI', 'ENORMOUS', 'ENRICH', 'ENSURE', 'ENTERPRISE', 'ENTERTAIN', 'ENTHUSIASM', 'ENTHUSIAST',
  'ENTIRE', 'ENTITLE', 'ENTROPY', 'ENTRY', 'ENVELOPE', 'EPISODE', 'EQUAL', 'EQUIP', 'ERASER', 'ERECT',
  'ERROR', 'ERUPT', 'ESCAPE', 'ESPRESSO', 'ESSAY', 'ESSAYIST', 'ESSENCE', 'ESSENTIAL', 'ESTABLISH', 'ESTATE',
  'ESTIMATE', 'ETERNAL', 'ETHIC', 'ETHNIC', 'EVACUATE', 'EVALUATE', 'EVENING', 'EVENT', 'EVIDENT', 'EVOLVE',
  'EXACT', 'EXALT', 'EXAMINE', 'EXAMINEE', 'EXAMPLE', 'EXCEED', 'EXCEL', 'EXCELLENT', 'EXCESS', 'EXCESSIVE',
  'EXCHANGE', 'EXCITED', 'EXCITING', 'EXCLAIM', 'EXCLUDE', 'EXCLUSIVE', 'EXCUSE', 'EXECUTE', 'EXERCISE', 'EXHAUST',
  'EXHAUSTED', 'EXHAUSTING', 'EXHIBIT', 'EXILE', 'EXIST', 'EXISTING', 'EXOTIC', 'EXPAND', 'EXPECT', 'EXPECTED',
  'EXPENSE', 'EXPENSIVE', 'EXPERT', 'EXPLAIN', 'EXPLODE', 'EXPLOIT', 'EXPLORE', 'EXPLORER', 'EXPLOSIVE', 'EXPORT',
  'EXPOSE', 'EXPRESS', 'EXPRESSIVE', 'EXQUISITE', 'EXTEND', 'EXTENSIVE', 'EXTENT', 'EXTERNAL', 'EXTINCT', 'EXTRA',
  'EXTRACT', 'EXTREME', 'EXULTANT', 'EYEBROW', 'EYELASH', 'EYELID', 'EYESIGHT', 'FABRIC', 'FABULOUS', 'FACTOR',
  'FACTORY', 'FACULTY', 'FAILURE', 'FAIRY', 'FAITHFUL', 'FALAFEL', 'FALLEN', 'FALTER', 'FAMILIAR', 'FAMOUS',
  'FANCY', 'FANTASTIC', 'FANTASY', 'FARAWAY', 'FAREWELL', 'FARMER', 'FARMING', 'FARMLAND', 'FASCINATE', 'FASHION',
  'FASTEN', 'FATAL', 'FATHER', 'FAULTY', 'FEARSOME', 'FEATHER', 'FEATURE', 'FEBRUARY', 'FEDERAL', 'FEEDBACK',
  'FEELING', 'FELLOW', 'FEMALE', 'FENCE', 'FENCING', 'FERRET', 'FERRY', 'FERRYBOAT', 'FESTIVAL', 'FESTIVE',
  'FEVER', 'FICTION', 'FICTIONAL', 'FIGHTER', 'FIGHTING', 'FIGURE', 'FILIAL', 'FILLING', 'FILTER', 'FINAL',
  'FINANCE', 'FINDING', 'FINGER', 'FINGERNAIL', 'FINISH', 'FIREARM', 'FIREFLY', 'FIREPLACE', 'FIREWORK', 'FISCAL',
  'FISHERMAN', 'FISHING', 'FITNESS', 'FIXED', 'FLAMINGO', 'FLAWLESS', 'FLEXIBLE', 'FLOWER', 'FLUENCY', 'FLUTTER',
  'FOCUS', 'FOGGY', 'FOLDER', 'FOLLOW', 'FOLLOWER', 'FOLLOWING', 'FOLLY', 'FOOLISH', 'FOOTBALL', 'FOOTBALLER',
  'FOOTNOTE', 'FORBID', 'FORBIDDEN', 'FORECAST', 'FOREHEAD', 'FOREIGN', 'FOREIGNER', 'FOREMAN', 'FORESEE', 'FOREST',
  'FORESTRY', 'FORGET', 'FORGIVE', 'FORMAL', 'FORMAT', 'FORMER', 'FORMULA', 'FORTNIGHT', 'FORTRESS', 'FORTUNATE',
  'FORTUNE', 'FOUNTAIN', 'FREEDOM', 'FREEZER', 'FREEZING', 'FREQUENCY', 'FREQUENT', 'FRESHMAN', 'FRIDAY', 'FRIENDLY',
  'FRIGATE', 'FRIGHTEN', 'FRIGHTENED', 'FRONTIER', 'FROZEN', 'FRUGAL', 'FRUSTRATED', 'FUNCTIONAL', 'FUNDRAISER', 'FUNERAL',
  'FUNKY', 'FUNNEL', 'FUNNY', 'FURIOUS', 'FURNISH', 'FURNITURE', 'FURTHER', 'FUTURE', 'GAIETY', 'GALLERY',
  'GALLON', 'GAMBLING', 'GAMING', 'GANGSTER', 'GARAGE', 'GARBAGE', 'GARDENER', 'GARDENING', 'GARLIC', 'GARMENT',
  'GATEWAY', 'GATHER', 'GAUDY', 'GECKO', 'GENDER', 'GENERAL', 'GENERATE', 'GENEROUS', 'GENETIC', 'GENETICS',
  'GENIUS', 'GENTLE', 'GENTLEMAN', 'GENUINE', 'GEOGRAPHIC', 'GESTURE', 'GETAWAY', 'GEYSER', 'GIFTED', 'GIGGLE',
  'GINGER', 'GIRAFFE', 'GIRLFRIEND', 'GIVEAWAY', 'GIVEN', 'GLACIER', 'GLACIS', 'GLADIATOR', 'GLANCE', 'GLASSES',
  'GLOBAL', 'GLOCAL', 'GLOOMY', 'GLORIFY', 'GLORIOUS', 'GLORY', 'GOALKEEPER', 'GOBLIN', 'GODDESS', 'GODLY',
  'GOLDEN', 'GOLDFISH', 'GOLFER', 'GONDOLA', 'GOODWILL', 'GORGEOUS', 'GORILLA', 'GOSSIP', 'GOVERN', 'GOVERNOR',
  'GRACEFUL', 'GRADUAL', 'GRADUATE', 'GRAMMAR', 'GRANDCHILD', 'GRANDDAD', 'GRANDMA', 'GRANDPA', 'GRANDSON', 'GRANNY',
  'GRANOLA', 'GRAPHIC', 'GRAPHICS', 'GRATEFUL', 'GRATITUDE', 'GRAVESTONE', 'GRAVY', 'GREEDY', 'GREENHOUSE', 'GREETING',
  'GRIFFIN', 'GRILLED', 'GROUPING', 'GROWING', 'GUARANTEE', 'GUERRILLA', 'GUIDEBOOK', 'GUIDELINE', 'GUILTY', 'GUITAR',
  'GUITARIST', 'GUNSHOT', 'GYMNASTIC', 'GYMNASTICS', 'HABIT', 'HABITANT', 'HABITAT', 'HAIKU', 'HAIRCUT', 'HAIRDRYER',
  'HAIRY', 'HAMBURGER', 'HAMMER', 'HAMSTER', 'HANDBAG', 'HANDBALL', 'HANDICAP', 'HANDICRAFT', 'HANDLE', 'HANDOUT',
  'HANDRAIL', 'HANDSHAKE', 'HANDSOME', 'HANDY', 'HANGING', 'HAPPEN', 'HARBINGER', 'HARBOR', 'HARDWARE', 'HARMFUL',
  'HARMLESS', 'HARMONY', 'HARNESS', 'HARROW', 'HARVEST', 'HASTY', 'HATCHING', 'HATRED', 'HAUNTING', 'HAVEN',
  'HAZARD', 'HAZARDOUS', 'HEADACHE', 'HEADLINE', 'HEADPHONE', 'HEADPHONES', 'HEALING', 'HEALTHY', 'HEARING', 'HEARTED',
  'HEARTY', 'HEATER', 'HEATING', 'HEATWAVE', 'HEAVEN', 'HEAVENLY', 'HEAVY', 'HEDGEHOG', 'HELLO', 'HELMET',
  'HELPER', 'HELPFUL', 'HELPLESS', 'HERITAGE', 'HESITATE', 'HIDDEN', 'HIGHLIGHT', 'HIGHWAY', 'HIJACK', 'HIKING',
  'HILARIOUS', 'HIPPO', 'HISTORIAN', 'HISTORIC', 'HISTORY', 'HOBBY', 'HOCKEY', 'HOLDER', 'HOLIDAY', 'HOLLOW',
  'HOMAGE', 'HOMELESS', 'HOMETOWN', 'HOMEWARD', 'HOMEWORK', 'HONEST', 'HONESTY', 'HONEY', 'HONEYMOON', 'HOOD',
  'HOPEFUL', 'HOPELESS', 'HORIZON', 'HORRIBLE', 'HORRIFY', 'HORROR', 'HOSPICE', 'HOSPITAL', 'HOSTEL', 'HOTEL',
  'HOURLY', 'HOUSEHOLD', 'HOUSEWIFE', 'HOUSEWORK', 'HOVER', 'HUBRIS', 'HUMAN', 'HUMANE', 'HUMANIST', 'HUMBLE',
  'HUMBUG', 'HUMID', 'HUMILIATE', 'HUMMUS', 'HUMOROUS', 'HUNGER', 'HUNGRY', 'HUNTER', 'HUNTING', 'HURRICANE',
  'HURRY', 'HUSBAND', 'HYBRID', 'HYGIENE', 'HYPERBOLE', 'HYPHEN', 'ICEBERG', 'ICEMAN', 'IDEAL', 'IDIOM',
  'IDIOT', 'IGLOO', 'IGNORANT', 'IGNORE', 'ILLEGAL', 'ILLNESS', 'ILLUSTRATE', 'IMAGE', 'IMAGERY', 'IMAGINE',
  'IMITATE', 'IMMEDIATE', 'IMMERSE', 'IMMIGRANT', 'IMMIGRATE', 'IMMORAL', 'IMMORTAL', 'IMPACT', 'IMPAIR', 'IMPARTIAL',
  'IMPATIENT', 'IMPLY', 'IMPOLITE', 'IMPORT', 'IMPORTANT', 'IMPOSE', 'IMPRESS', 'IMPRESSED', 'IMPRESSIVE', 'IMPRISON',
  'IMPROPER', 'IMPROVE', 'IMPROVED', 'IMPULSE', 'IMPULSIVE', 'INBORN', 'INCENSE', 'INCENTIVE', 'INCIDENT', 'INCLUDE',
  'INCOME', 'INCORRECT', 'INCREASE', 'INCUR', 'INDEBTED', 'INDENT', 'INDEX', 'INDICATE', 'INDIRECT', 'INDOOR',
  'INDULGE', 'INDULGENT', 'INDUSTRIAL', 'INDUSTRY', 'INERT', 'INFANT', 'INFECT', 'INFECTED', 'INFECTIOUS', 'INFER',
  'INFLATE', 'INFLUENZA', 'INFORM', 'INFORMAL', 'INFRINGE', 'INGREDIENT', 'INHABIT', 'INHALE', 'INHERIT', 'INITIAL',
  'INJECT', 'INJURED', 'INJURY', 'INNATE', 'INNER', 'INNERMOST', 'INNOCENT', 'INPUT', 'INSANE', 'INSCRIBE',
  'INSECT', 'INSIDE', 'INSIGHT', 'INSIST', 'INSPECT', 'INSPECTOR', 'INSPIRE', 'INSTANT', 'INSTINCT', 'INSTITUTE',
  'INSTRUCT', 'INSTRUCTOR', 'INSULT', 'INTEGRATE', 'INTEND', 'INTENSE', 'INTENSIVE', 'INTENT', 'INTERACT', 'INTEREST',
  'INTERFERE', 'INTERIOR', 'INTERNAL', 'INTERPRET', 'INTERRUPT', 'INTERVAL', 'INTERVIEW', 'INTIMATE', 'INTRODUCE', 'INTRUDE',
  'INTRUDER', 'INVADE', 'INVENT', 'INVENTOR', 'INVEST', 'INVESTOR', 'INVITE', 'INVOKE', 'INVOLVE', 'INVOLVED',
  'IRONING', 'IRONY', 'IRRITATE', 'ISLAND', 'ISLANDER', 'IVORY', 'JACKET', 'JAGUAR', 'JANUARY', 'JEALOUS',
  'JELLY', 'JELLYFISH', 'JESTER', 'JEWEL', 'JOGGING', 'JOURNAL', 'JOURNALIST', 'JOURNEY', 'JUICY', 'JUMPER',
  'JUNGLE', 'JUNIOR', 'JUROR', 'JUSTICE', 'JUSTIFY', 'KANGAROO', 'KARAOKE', 'KARMA', 'KAYAKING', 'KAZOO',
  'KEBAB', 'KEEPER', 'KEROSENE', 'KETCHUP', 'KETTLE', 'KEYBOARD', 'KEYSTROKE', 'KILLER', 'KILLING', 'KINDLY',
  'KINGDOM', 'KITTEN', 'KNITTING', 'KNOWLEDGE', 'KOALA', 'KRAKEN', 'LABEL', 'LABYRINTH', 'LACROSSE', 'LADDER',
  'LADLE', 'LADYBUG', 'LANCE', 'LANDING', 'LANDLADY', 'LANDLORD', 'LANDSCAPE', 'LANDSLIDE', 'LANGUAGE', 'LANTERN',
  'LAPTOP', 'LASER', 'LASTING', 'LATER', 'LATEST', 'LATTER', 'LAUGHTER', 'LAUNDRY', 'LAWFUL', 'LAWMAKER',
  'LAWSUIT', 'LAWYER', 'LAYABOUT', 'LEADER', 'LEADING', 'LEAFLET', 'LEARNER', 'LEARNING', 'LEATHER', 'LECTURE',
  'LECTURER', 'LEGAL', 'LEGEND', 'LEGISLATE', 'LEISURE', 'LEMON', 'LEMONADE', 'LEMUR', 'LENGTHEN', 'LENGTHY',
  'LEOPARD', 'LESSEN', 'LESSON', 'LETTER', 'LETTUCE', 'LEVEL', 'LIBERAL', 'LIBERATE', 'LIBERTY', 'LIBRARIAN',
  'LIBRARY', 'LIFEGUARD', 'LIFELESS', 'LIFELONG', 'LIFESTYLE', 'LIFETIME', 'LIGHTEN', 'LIGHTER', 'LIGHTHOUSE', 'LIGHTING',
  'LIGHTNING', 'LIKELY', 'LIMBO', 'LIMIT', 'LIMITED', 'LINEN', 'LINER', 'LINGER', 'LIQUID', 'LISTEN',
  'LISTENER', 'LITERAL', 'LITTER', 'LITTLE', 'LIVELY', 'LIVER', 'LIVING', 'LLAMA', 'LOBBY', 'LOBSTER',
  'LOCAL', 'LOCATE', 'LOCKSMITH', 'LOGIC', 'LOLLIPOP', 'LONELY', 'LORRY', 'LOTTERY', 'LOUSY', 'LOVELY',
  'LOVER', 'LOWER', 'LOWLAND', 'LOYALTY', 'LUCKY', 'LUCRATIVE', 'LUGGAGE', 'LUNCHBOX', 'LUNCHTIME', 'LUXURIOUS',
  'LUXURY', 'LYRIC', 'LYRICS', 'MACHINE', 'MADAM', 'MADAME', 'MADNESS', 'MAESTRO', 'MAGAZINE', 'MAGIC',
  'MAGICIAN', 'MAGNIFY', 'MAILBOX', 'MAINTAIN', 'MAJOR', 'MAKER', 'MALADY', 'MALARIA', 'MALLET', 'MANAGE',
  'MANAGER', 'MANGO', 'MANKIND', 'MANNER', 'MANSION', 'MANUAL', 'MAPLE', 'MARATHON', 'MARBLE', 'MARGIN',
  'MARINE', 'MARKED', 'MARKET', 'MARKETING', 'MARRIAGE', 'MARRIED', 'MARRY', 'MASSAGE', 'MASSEUR', 'MASSIVE',
  'MASTER', 'MASTERY', 'MATERIAL', 'MATTER', 'MATURE', 'MAXIMUM', 'MEADOW', 'MEANING', 'MEANINGFUL', 'MEASURE',
  'MECHANIC', 'MEDAL', 'MEDIA', 'MEDICINE', 'MEDIOCRE', 'MEDITATE', 'MEDIUM', 'MEETING', 'MELODY', 'MELON',
  'MEMBER', 'MEMORIAL', 'MEMORY', 'MENTAL', 'MENTION', 'MENTOR', 'MERCHANT', 'MERCY', 'MERGER', 'MERMAID',
  'MESSAGE', 'MESSENGER', 'MESSY', 'METAL', 'METAPHOR', 'METHOD', 'METRIC', 'MICRO', 'MICROBE', 'MICROPHONE',
  'MICROSCOPE', 'MICROWAVE', 'MIDDAY', 'MIDDLE', 'MIDNIGHT', 'MIGHTY', 'MILKSHAKE', 'MIMIC', 'MINERAL', 'MINIATURE',
  'MINIMUM', 'MINISTER', 'MINOR', 'MINUTE', 'MIRACLE', 'MIRAGE', 'MIRROR', 'MISCHIEF', 'MISERY', 'MISFORTUNE',
  'MISLEAD', 'MISLEADING', 'MISSILE', 'MISSING', 'MISSION', 'MISTAKE', 'MISTREAT', 'MISTY', 'MIXTURE', 'MOBILE',
  'MODEL', 'MODEM', 'MODERATE', 'MODERN', 'MODEST', 'MODIFY', 'MOGUL', 'MOISTURE', 'MOLECULE', 'MOMENT',
  'MOMENTUM', 'MONDAY', 'MONITOR', 'MONKEY', 'MONSOON', 'MONSTER', 'MONTHLY', 'MOODY', 'MOONLIGHT', 'MOONSCAPE',
  'MORAL', 'MORNING', 'MORTAL', 'MORTAR', 'MORTGAGE', 'MORTIFY', 'MOSQUITO', 'MOTHERLAND', 'MOTION', 'MOTIONLESS',
  'MOTIVATE', 'MOTIVE', 'MOTOR', 'MOTORBIKE', 'MOTORIST', 'MOTORWAY', 'MOTTO', 'MOURNFUL', 'MOVER', 'MOVING',
  'MUDDY', 'MUFFIN', 'MULTIPLE', 'MULTIPLY', 'MUMBLE', 'MURDER', 'MURDERER', 'MURMUR', 'MUSCLE', 'MUSEUM',
  'MUSHROOM', 'MUSICIAN', 'MUSTARD', 'MUTABLE', 'MUTTER', 'MUTTON', 'MUTUAL', 'MYSTERIOUS', 'MYSTERY', 'MYSTIFY',
  'NACHO', 'NAPKIN', 'NARRATE', 'NARRATIVE', 'NARRATOR', 'NARROW', 'NASTY', 'NATION', 'NATIONAL', 'NATIONWIDE',
  'NATIVE', 'NATURAL', 'NATURE', 'NAUGHTY', 'NAVAL', 'NAVIGATE', 'NEARBY', 'NECKLACE', 'NECTAR', 'NEEDLE',
  'NEEDLESS', 'NEEDY', 'NEGATIVE', 'NEGLECT', 'NEGOTIATE', 'NEPHEW', 'NERVES', 'NERVOUS', 'NESS', 'NETWORK',
  'NEUROSIS', 'NEUTRAL', 'NEWBORN', 'NEWCOMER', 'NEWSCASTER', 'NEWSPAPER', 'NEWSWORTHY', 'NEXUS', 'NICKNAME', 'NIGHTCLUB',
  'NIGHTLIFE', 'NIGHTMARE', 'NINJA', 'NOBLE', 'NOBLEMAN', 'NOISY', 'NOMAD', 'NOMINEE', 'NONSENSE', 'NOODLE',
  'NORMAL', 'NORTHEAST', 'NORTHERN', 'NORTHWEST', 'NOSTRIL', 'NOTEBOOK', 'NOTICE', 'NOTION', 'NOTORIOUS', 'NOURISH',
  'NOVEL', 'NOVELIST', 'NOVELTY', 'NOVEMBER', 'NUANCE', 'NUCLEAR', 'NUCLEUS', 'NUMBER', 'NUMEROUS', 'NURSERY',
  'NUTRIENT', 'NUTRITIOUS', 'NUTSHELL', 'OBEDIENT', 'OBJECT', 'OBJECTIVE', 'OBLIVION', 'OBSERVE', 'OBSERVER', 'OBSESS',
  'OBSESSIVE', 'OBSTACLE', 'OBTAIN', 'OBVIOUS', 'OCCUPY', 'OCCUR', 'OCEAN', 'OCTOBER', 'OCTOPUS', 'OFFEND',
  'OFFENDER', 'OFFENSIVE', 'OFFER', 'OFFICE', 'OFFICER', 'OFFSHORE', 'OLIVE', 'OLYMPIA', 'OLYMPIAD', 'OLYMPIC',
  'OLYMPICS', 'ONION', 'ONLINE', 'ONSTAGE', 'OPENING', 'OPERA', 'OPERATE', 'OPINION', 'OPPONENT', 'OPPOSE',
  'OPPOSITE', 'OPPRESS', 'OPTIMIST', 'OPTION', 'OPTIONAL', 'ORACLE', 'ORANGE', 'ORATOR', 'ORBIT', 'ORCHESTRA',
  'ORCHESTRAL', 'ORCHID', 'ORDER', 'ORDERLY', 'ORGAN', 'ORGANIC', 'ORIGIN', 'ORPHAN', 'OTTER', 'OUTBACK',
  'OUTBREAK', 'OUTCOME', 'OUTDO', 'OUTDOOR', 'OUTER', 'OUTFIT', 'OUTGROW', 'OUTING', 'OUTLAW', 'OUTLET',
  'OUTLINE', 'OUTLIVE', 'OUTLOOK', 'OUTPATIENT', 'OUTPUT', 'OUTRAGE', 'OUTRAGEOUS', 'OUTSHINE', 'OUTSIDE', 'OUTSIDER',
  'OUTSKIRTS', 'OUTWARD', 'OUTWEIGH', 'OVERALL', 'OVERBOOK', 'OVERCOAT', 'OVERCOME', 'OVERHEAR', 'OVERJOYED', 'OVERLAP',
  'OVERLOOK', 'OVERNIGHT', 'OVERSEAS', 'OVERSIZE', 'OVERSTEP', 'OVERTAKE', 'OVERTHROW', 'OVERTIME', 'OVERTURN', 'OVERWEIGHT',
  'OVERWHELM', 'OVERWORK', 'OWING', 'OWNER', 'OXYGEN', 'OZONE', 'PACIFIC', 'PACKAGE', 'PACKED', 'PACKET',
  'PACKING', 'PADDLE', 'PAINFUL', 'PAINTBRUSH', 'PAINTER', 'PAINTING', 'PALACE', 'PALETTE', 'PALLET', 'PANCAKE',
  'PANDA', 'PANDEMIC', 'PANEL', 'PANIC', 'PANTHER', 'PAPAYA', 'PAPERLESS', 'PAPERWORK', 'PARACHUTE', 'PARADE',
  'PARADISE', 'PARADOX', 'PARAGRAPH', 'PARAKEET', 'PARCEL', 'PARDON', 'PARENT', 'PARENTAL', 'PARKING', 'PARODY',
  'PARROT', 'PARTIAL', 'PARTICLE', 'PARTISAN', 'PARTNER', 'PASSAGE', 'PASSENGER', 'PASSION', 'PASSIONATE', 'PASSIVE',
  'PASSPORT', 'PASSWORD', 'PASTA', 'PASTOR', 'PASTORAL', 'PATIENT', 'PATRIOT', 'PATRIOTIC', 'PATROL', 'PATRON',
  'PATTERN', 'PAWNBROKER', 'PAWNSHOP', 'PAYMENT', 'PEACEFUL', 'PEACOCK', 'PEANUT', 'PEBBLE', 'PECULIAR', 'PEDAL',
  'PEDANTIC', 'PEDESTRIAN', 'PELICAN', 'PENALTY', 'PENCE', 'PENCIL', 'PENETRATE', 'PENGUIN', 'PENNILESS', 'PENNY',
  'PENSION', 'PENTAGON', 'PEOPLE', 'PEPPER', 'PERCEIVE', 'PERCENTAGE', 'PERFECT', 'PERFORM', 'PERFORMER', 'PERFUME',
  'PERIOD', 'PERMANENT', 'PERMEATE', 'PERMIT', 'PERSIST', 'PERSISTENT', 'PERSON', 'PERSONAL', 'PERSONNEL', 'PERSUADE',
  'PERSUASIVE', 'PESSIMIST', 'PESTLE', 'PETAL', 'PETRIFIED', 'PETROL', 'PETTY', 'PHANTOM', 'PHARAOH', 'PHARMACIST',
  'PHARMACY', 'PHOENIX', 'PHOTO', 'PHOTOGRAPH', 'PHYSICIAN', 'PHYSICS', 'PIANO', 'PICKLE', 'PICKY', 'PICNIC',
  'PICTURE', 'PIETY', 'PIGEON', 'PILGRIM', 'PILLOW', 'PILLOWCASE', 'PILOT', 'PINBALL', 'PINEAPPLE', 'PINNACLE',
  'PIRACY', 'PIRATE', 'PISTACHIO', 'PITY', 'PLACEBO', 'PLANET', 'PLANNING', 'PLASTIC', 'PLATFORM', 'PLAYFUL',
  'PLAYGROUND', 'PLAYMATE', 'PLAYWRIGHT', 'PLEASANT', 'PLEASED', 'PLEASING', 'PLEASURE', 'PLENTY', 'PLUMBER', 'PLURAL',
  'PNEUMONIA', 'POCKET', 'POETRY', 'POINTLESS', 'POISON', 'POISONOUS', 'POLICE', 'POLICY', 'POLIO', 'POLISH',
  'POLITICS', 'POLLUTANT', 'POLLUTE', 'PONDER', 'POPCORN', 'POPULAR', 'PORCUPINE', 'PORTION', 'PORTRAIT', 'POSITIVE',
  'POSSESS', 'POSSESSED', 'POSSESSIVE', 'POSSIBLE', 'POSTAL', 'POSTCARD', 'POSTER', 'POSTMAN', 'POSTPONE', 'POTATO',
  'POTENT', 'POTENTIAL', 'POTTERY', 'POVERTY', 'POWDER', 'POWER', 'POWERFUL', 'PRACTICE', 'PRANCE', 'PRECEDE',
  'PRECIOUS', 'PRECISE', 'PREDICATE', 'PREDICT', 'PREDICTIVE', 'PREDICTOR', 'PREFECT', 'PREFER', 'PREFIX', 'PREGNANT',
  'PREHUMAN', 'PREJUDGE', 'PREJUDICE', 'PREMIERE', 'PREOCCUPY', 'PREPARE', 'PREPARED', 'PRESCHOOL', 'PRESCRIBE', 'PRESENT',
  'PRESENTER', 'PRESERVE', 'PRESIDENT', 'PRESSURE', 'PRESTIGE', 'PRETEND', 'PRETTY', 'PRETZEL', 'PREVAIL', 'PREVENT',
  'PREVENTIVE', 'PREVIOUS', 'PRICELESS', 'PRIMARY', 'PRIMITIVE', 'PRINCESS', 'PRINCIPAL', 'PRINCIPLE', 'PRINTER', 'PRISON',
  'PRISONER', 'PRIVACY', 'PRIVATE', 'PRIVILEGE', 'PROBABLE', 'PROBLEM', 'PROCEDURE', 'PROCEED', 'PROCESS', 'PROCLAIM',
  'PRODUCE', 'PRODUCER', 'PRODUCT', 'PRODUCTIVE', 'PROFESSOR', 'PROFILE', 'PROFIT', 'PROGRAMMER', 'PROGRESS', 'PROHIBIT',
  'PROJECT', 'PROMINENT', 'PROMISE', 'PROMOTE', 'PRONOUN', 'PRONOUNCE', 'PROPER', 'PROPERTY', 'PROPHECY', 'PROPONENT',
  'PROPOSAL', 'PROPOSE', 'PROPOSED', 'PROSECUTE', 'PROSPECT', 'PROSPER', 'PROSPEROUS', 'PROTECT', 'PROTECTIVE', 'PROTEST',
  'PROVEN', 'PROVERB', 'PROVIDE', 'PROVINCE', 'PUBLIC', 'PUBLISH', 'PUBLISHER', 'PUDDING', 'PUDDLE', 'PULLOVER',
  'PUMPKIN', 'PUNCTUAL', 'PUNISH', 'PUPIL', 'PUPPY', 'PURCHASE', 'PURIFY', 'PURPLE', 'PURPOSE', 'PURSUIT',
  'PUZZLE', 'PUZZLED', 'PYTHON', 'QUALIFIED', 'QUALIFY', 'QUANTIFY', 'QUARANTINE', 'QUARREL', 'QUARTER', 'QUERY',
  'QUOTABLE', 'RABBIT', 'RACCOON', 'RACKET', 'RADAR', 'RADIATE', 'RADIO', 'RADIUM', 'RAFTER', 'RAILROAD',
  'RAILWAY', 'RAINBOW', 'RAINCOAT', 'RAINFALL', 'RAINFOREST', 'RAINSTORM', 'RAINY', 'RAISIN', 'RALLY', 'RAMEN',
  'RANGER', 'RAPID', 'RASPBERRY', 'RATING', 'RATION', 'RATIONAL', 'RATTLE', 'RAVAGE', 'RAVEN', 'RAZOR',
  'READER', 'READING', 'READY', 'REALISTIC', 'REARRANGE', 'REASON', 'REBEL', 'REBELLION', 'REBELLIOUS', 'REBUILD',
  'RECALL', 'RECEIPT', 'RECEIVE', 'RECENT', 'RECIPE', 'RECITAL', 'RECITE', 'RECKON', 'RECLAIM', 'RECOLLECT',
  'RECOMMEND', 'RECORD', 'RECORDING', 'RECOVER', 'RECRUIT', 'RECYCLE', 'RECYCLED', 'RECYCLING', 'REDUCE', 'REDUNDANT',
  'REFER', 'REFEREE', 'REFERENT', 'REFLECT', 'REFLECTIVE', 'REFORM', 'REFRAIN', 'REFRESH', 'REFUGE', 'REFUGEE',
  'REFUND', 'REFUSAL', 'REFUSE', 'REFUTE', 'REGAIN', 'REGARD', 'REGIME', 'REGION', 'REGIONAL', 'REGISTER',
  'REGRET', 'REGULAR', 'REGULATE', 'REHEARSAL', 'REINFORCE', 'REJECT', 'REJOIN', 'RELATE', 'RELATED', 'RELATIVE',
  'RELAX', 'RELAXED', 'RELAXING', 'RELAY', 'RELEASE', 'RELEVANT', 'RELIABLE', 'RELIC', 'RELIEF', 'RELIEVE',
  'RELIEVED', 'RELIGION', 'RELIGIOUS', 'RELUCTANT', 'REMAIN', 'REMAINDER', 'REMAINING', 'REMAINS', 'REMARK', 'REMEDY',
  'REMEMBER', 'REMIND', 'REMINDER', 'REMNANT', 'REMOTE', 'REMOVE', 'RENEW', 'RENTAL', 'REPAINT', 'REPAIR',
  'REPAY', 'REPEAT', 'REPERTOIRE', 'REPLACE', 'REPLICA', 'REPLY', 'REPORT', 'REPORTER', 'REPRESENT', 'REPRESS',
  'REPRINT', 'REPRODUCE', 'REPROVE', 'REPUBLIC', 'REQUEST', 'REQUIRE', 'RESEARCH', 'RESEARCHER', 'RESEMBLE', 'RESERVE',
  'RESIDENT', 'RESIGN', 'RESIST', 'RESOLVE', 'RESONANT', 'RESORT', 'RESOURCE', 'RESPECT', 'RESPECTED', 'RESPOND',
  'RESPONSE', 'RESTAURANT', 'RESTORE', 'RESTRICT', 'RESULT', 'RESUME', 'RETAIL', 'RETAILER', 'RETAIN', 'RETELL',
  'RETINA', 'RETIRE', 'RETIRED', 'RETREAT', 'RETRIEVE', 'RETROSPECT', 'RETURN', 'REUNIFY', 'REUNION', 'REVEAL',
  'REVENGE', 'REVENUE', 'REVERSE', 'REVIEW', 'REVISE', 'REVIVAL', 'REVIVE', 'REVOLVE', 'REWARD', 'REWRITE',
  'RHYTHMIC', 'RIBBON', 'RICKSHAW', 'RIDDLE', 'RIDER', 'RISKY', 'RITUAL', 'RIVAL', 'RIVER', 'ROADSIDE',
  'ROBBERY', 'ROBIN', 'ROBOT', 'ROCKET', 'ROCKY', 'ROLLING', 'ROMANCE', 'ROMANTIC', 'ROOFTOP', 'ROOMMATE',
  'ROOSTER', 'ROTTEN', 'ROUNDABOUT', 'ROUTINE', 'ROWBOAT', 'ROWING', 'ROYALTY', 'RUBBER', 'RUBBISH', 'RUBBLE',
  'RUGBY', 'RUINOUS', 'RULER', 'RUNAWAY', 'RUNNER', 'RUNNING', 'RUNWAY', 'RURAL', 'RUSTY', 'SACRED',
  'SADNESS', 'SAFARI', 'SAFEGUARD', 'SAFETY', 'SAILING', 'SAILOR', 'SALAD', 'SALARY', 'SALESMAN', 'SALMON',
  'SALON', 'SALSA', 'SALTY', 'SAMPLE', 'SAMURAI', 'SANCTUARY', 'SANDAL', 'SANDSTONE', 'SANDSTORM', 'SANDWICH',
  'SANDY', 'SARCASM', 'SARDINE', 'SATELLITE', 'SATIRE', 'SATISFIED', 'SATISFY', 'SATURDAY', 'SAUCEPAN', 'SAUCER',
  'SAUSAGE', 'SCANDAL', 'SCARED', 'SCARLET', 'SCARY', 'SCATTER', 'SCENERY', 'SCENIC', 'SCHEDULE', 'SCHEDULED',
  'SCHOLAR', 'SCHOOLCHILD', 'SCHOOLGIRL', 'SCHOOLMATE', 'SCHOOLWORK', 'SCIENCE', 'SCIENTIFIC', 'SCIENTIST', 'SCISSORS', 'SCOOTER',
  'SCRAMBLE', 'SCRIBBLE', 'SCUBA', 'SCULPTURE', 'SEAFOOD', 'SEAHORSE', 'SEASIDE', 'SEASON', 'SEASONAL', 'SEAWATER',
  'SEAWEED', 'SECOND', 'SECRET', 'SECTION', 'SECTOR', 'SECURE', 'SEESAW', 'SEGMENT', 'SELECT', 'SELFISH',
  'SELFLESS', 'SELLER', 'SEMESTER', 'SEMINAR', 'SENATOR', 'SENIOR', 'SENSIBLE', 'SENSITIVE', 'SEPARATE', 'SEPTEMBER',
  'SERENE', 'SERIAL', 'SERIES', 'SERIOUS', 'SERVANT', 'SERVER', 'SERVICE', 'SESSION', 'SETBACK', 'SETTING',
  'SETTLE', 'SETTLER', 'SEVERE', 'SHABBY', 'SHADOW', 'SHADOWY', 'SHAKEN', 'SHAKY', 'SHALLOW', 'SHAMEFUL',
  'SHAMPOO', 'SHATTER', 'SHELTER', 'SHERIFF', 'SHINY', 'SHIP', 'SHIPPING', 'SHIPWRECK', 'SHIVER', 'SHOCKED',
  'SHOCKING', 'SHOOTING', 'SHOPKEEPER', 'SHOPLIFT', 'SHOPLIFTER', 'SHOPPER', 'SHOPPING', 'SHORTAGE', 'SHOULDER', 'SHOVEL',
  'SHOWBIZ', 'SHOWCASE', 'SHOWER', 'SIDEWALK', 'SIGHTSEEING', 'SIGNAL', 'SIGNATURE', 'SIGNIFY', 'SIGNPOST', 'SILENCE',
  'SILENT', 'SILLY', 'SILVER', 'SILVERWARE', 'SIMILAR', 'SIMPLE', 'SIMPLIFY', 'SINCERE', 'SINGER', 'SINGING',
  'SINGLE', 'SINGULAR', 'SISTER', 'SKATEBOARD', 'SKATING', 'SKELETON', 'SKILLED', 'SKYLARK', 'SKYSCRAPER', 'SLAUGHTER',
  'SLEEPLESS', 'SLEEPOVER', 'SLEEPY', 'SLIVER', 'SLOGAN', 'SLOPPY', 'SMOKER', 'SMOKESTACK', 'SMOKING', 'SMOOTHIE',
  'SNOWBALL', 'SNOWBOARD', 'SNOWSTORM', 'SNOWY', 'SOAKED', 'SOAKING', 'SOCCER', 'SOCIABLE', 'SOCIETY', 'SOFTWARE',
  'SOLAR', 'SOLDIER', 'SOLID', 'SOLITUDE', 'SOLVENT', 'SONNET', 'SOPHOMORE', 'SORCERER', 'SORROW', 'SORRY',
  'SOUNDTRACK', 'SOUTHEAST', 'SOUTHERN', 'SOUTHWEST', 'SOUVENIR', 'SOVIET', 'SOYBEAN', 'SPAGHETTI', 'SPARERIB', 'SPARKLE',
  'SPARKLING', 'SPARROW', 'SPATULA', 'SPEAKER', 'SPECIALIST', 'SPECIALTY', 'SPECIES', 'SPECIFIC', 'SPECIFY', 'SPECTACLE',
  'SPECTATOR', 'SPECTER', 'SPECTRUM', 'SPEEDER', 'SPELLBOUND', 'SPELLING', 'SPICY', 'SPIDER', 'SPINACH', 'SPIRAL',
  'SPIRIT', 'SPIRITUAL', 'SPLATTER', 'SPOKESMAN', 'SPONSOR', 'SPREADSHEET', 'SQUIRREL', 'STABLE', 'STADIUM', 'STAGGER',
  'STAMMER', 'STANDARD', 'STANDBY', 'STANDSTILL', 'STANZA', 'STAPLER', 'STARTLE', 'STARVING', 'STATESMAN', 'STATION',
  'STATISTICS', 'STATUS', 'STEADY', 'STEELY', 'STEPFATHER', 'STEPMOTHER', 'STEREOTYPE', 'STICKER', 'STICKY', 'STIMULANT',
  'STIMULATE', 'STINGY', 'STOCKPILE', 'STOMACH', 'STONEWORK', 'STOPOVER', 'STOPWATCH', 'STORAGE', 'STORMY', 'STORY',
  'STRAIGHT', 'STRAIGHTEN', 'STRANGER', 'STRANGLE', 'STRATEGIC', 'STRATEGY', 'STRAWBERRY', 'STRENGTH', 'STRENGTHEN', 'STRESSED',
  'STRESSFUL', 'STRICKEN', 'STRIKING', 'STRUCTURE', 'STRUGGLE', 'STUBBORN', 'STUDENT', 'STUDIO', 'STUDY', 'STUFFED',
  'STUMBLE', 'STUNNING', 'STUPID', 'STYLISH', 'STYLIST', 'SUBCULTURE', 'SUBJECT', 'SUBMARINE', 'SUBMIT', 'SUBPLOT',
  'SUBSIDE', 'SUBSTITUTE', 'SUBTEXT', 'SUBTITLE', 'SUBTLE', 'SUBTRACT', 'SUBURB', 'SUBWAY', 'SUCCEED', 'SUCCESS',
  'SUCCESSFUL', 'SUCCESSIVE', 'SUDDEN', 'SUFFER', 'SUFFERING', 'SUFFIX', 'SUGAR', 'SUGGEST', 'SUICIDE', 'SUITABLE',
  'SUITCASE', 'SUMMARY', 'SUMMER', 'SUMMIT', 'SUNBATHE', 'SUNBEAM', 'SUNDAY', 'SUNDIAL', 'SUNFLOWER', 'SUNGLASSES',
  'SUNLIGHT', 'SUNNY', 'SUNRISE', 'SUNSET', 'SUNSHINE', 'SUPER', 'SUPERB', 'SUPERIOR', 'SUPERSTAR', 'SUPERVISE',
  'SUPPER', 'SUPPLIER', 'SUPPLY', 'SUPPORT', 'SUPPORTER', 'SUPPORTIVE', 'SUPPOSE', 'SUPPRESS', 'SURFACE', 'SURFING',
  'SURGEON', 'SURGERY', 'SURNAME', 'SURPRISE', 'SURPRISED', 'SURPRISING', 'SURRENDER', 'SURROUND', 'SURVEY', 'SURVIVAL',
  'SURVIVE', 'SURVIVOR', 'SUSHI', 'SUSPECT', 'SUSPEND', 'SUSPENSE', 'SUSPICION', 'SUSPICIOUS', 'SUSTAIN', 'SWALLOW',
  'SWEATER', 'SWEATSHIRT', 'SWEETHEART', 'SWIMMER', 'SWIMMING', 'SWIMSUIT', 'SWOLLEN', 'SYLLABLE', 'SYMBOL', 'SYMBOLIC',
  'SYMPATHY', 'SYMPHONY', 'SYMPTOM', 'SYNAGOGUE', 'SYNDROME', 'SYNONYM', 'SYRUP', 'SYSTEM', 'TABLECLOTH', 'TABLESPOON',
  'TABLET', 'TABLOID', 'TACKLE', 'TACTILE', 'TAKEAWAY', 'TALENT', 'TALENTED', 'TALKATIVE', 'TAMBOURINE', 'TANNED',
  'TARGET', 'TASTELESS', 'TASTY', 'TATTER', 'TATTOO', 'TAVERN', 'TEACHER', 'TEACHING', 'TEAMMATE', 'TEAMWORK',
  'TEASPOON', 'TECHNIQUE', 'TEENAGE', 'TEENAGER', 'TELEGRAM', 'TELEPHONE', 'TELESCOPE', 'TELLER', 'TEMPER', 'TEMPERATE',
  'TEMPLE', 'TENDENCY', 'TENDER', 'TENNIS', 'TENSION', 'TERMINAL', 'TERRACE', 'TERRIBLE', 'TERRIFIC', 'TERRIFIED',
  'TERRIFY', 'TERRIFYING', 'TERROR', 'TERRORIST', 'TESTIFY', 'TEXTBOOK', 'THANKFUL', 'THEATER', 'THEORIST', 'THEORY',
  'THERAPIST', 'THERAPY', 'THERMOS', 'THESIS', 'THINKER', 'THIRSTY', 'THOROUGH', 'THOUGHTFUL', 'THOUGHTLESS', 'THREATEN',
  'THRESHOLD', 'THRILLED', 'THRILLER', 'THRILLING', 'THUNDER', 'THUNDEROUS', 'THURSDAY', 'TICKET', 'TICKLE', 'TIGER',
  'TIGHTEN', 'TIGHTROPE', 'TIMELESS', 'TIMELY', 'TIMING', 'TIRED', 'TIRESOME', 'TIRING', 'TITLE', 'TOASTER',
  'TOBACCO', 'TODAY', 'TOENAIL', 'TOILET', 'TOLERANT', 'TOLERATE', 'TOMATO', 'TOMORROW', 'TONIGHT', 'TOOTHACHE',
  'TOOTHBRUSH', 'TOOTHPASTE', 'TOPIC', 'TORNADO', 'TOTAL', 'TOUCAN', 'TOURISM', 'TOURIST', 'TOWEL', 'TOWER',
  'TOXIC', 'TRACKSUIT', 'TRACTOR', 'TRADER', 'TRAFFIC', 'TRAGEDY', 'TRAGIC', 'TRAILER', 'TRAINER', 'TRAINING',
  'TRAITOR', 'TRAMPLE', 'TRANSCRIPT', 'TRANSFER', 'TRANSFORM', 'TRANSISTOR', 'TRANSITIVE', 'TRANSLATE', 'TRANSLATOR', 'TRANSMIT',
  'TRANSPORT', 'TRAVEL', 'TRAVERSE', 'TREASURE', 'TREATY', 'TREMBLE', 'TREMENDOUS', 'TREMOR', 'TRIANGLE', 'TRICKY',
  'TRIGGER', 'TRIVIAL', 'TROLLEY', 'TROPHY', 'TROPIC', 'TROUBLE', 'TROUSERS', 'TRUMPET', 'TRUSTY', 'TRUTHFUL',
  'TSUNAMI', 'TUESDAY', 'TUITION', 'TULIP', 'TUMBLE', 'TUNNEL', 'TURBULENT', 'TURKEY', 'TURNING', 'TURTLE',
  'TUTOR', 'TWINKLE', 'TWISTED', 'TYPHOID', 'TYRANNY', 'TYRANT', 'UKULELE', 'ULTIMATE', 'UMBRELLA', 'UNABLE',
  'UNAFRAID', 'UNAWARE', 'UNCERTAIN', 'UNCHANGED', 'UNCLE', 'UNCLEAR', 'UNCOMMON', 'UNCOVER', 'UNDERAGE', 'UNDERGO',
  'UNDERLINE', 'UNDERPANTS', 'UNDERSEA', 'UNDERSTAND', 'UNDERTAKE', 'UNDERWEAR', 'UNDREAMED', 'UNDRESS', 'UNDRESSED', 'UNEASE',
  'UNEASY', 'UNEMPLOYED', 'UNEVEN', 'UNFAIR', 'UNFIT', 'UNFOLD', 'UNFRIENDLY', 'UNGODLY', 'UNHAPPY', 'UNHEALTHY',
  'UNHEARD', 'UNHELPFUL', 'UNICORN', 'UNIFORM', 'UNIFY', 'UNION', 'UNIQUE', 'UNITE', 'UNITED', 'UNIVERSE',
  'UNKIND', 'UNKNOWN', 'UNLIKE', 'UNLOAD', 'UNLOCK', 'UNLUCKY', 'UNPACK', 'UNPLEASANT', 'UNREST', 'UNSAFE',
  'UNSELFISH', 'UNSURE', 'UNTIDY', 'UNTREATED', 'UNTRIMMED', 'UNUSUAL', 'UNWANTED', 'UNWELL', 'UNWILLING', 'UNWISE',
  'UNWORLDLY', 'UPBRINGING', 'UPDATE', 'UPGRADE', 'UPLIFTED', 'UPLOAD', 'UPPER', 'UPRIGHT', 'UPSET', 'UPSTAIRS',
  'UPWARD', 'URBAN', 'URGENT', 'USAGE', 'USEFUL', 'USELESS', 'USHER', 'USUAL', 'UTOPIA', 'UTTER',
  'VACANCY', 'VACANT', 'VACCINE', 'VALENTINE', 'VALID', 'VALLEY', 'VALUABLE', 'VAMPIRE', 'VANILLA', 'VANISH',
  'VARIED', 'VARIETY', 'VARIOUS', 'VEHICLE', 'VENTURE', 'VERBAL', 'VERSION', 'VERTIGO', 'VESSEL', 'VESTIGE',
  'VETERAN', 'VIBRATE', 'VICTIM', 'VICTORY', 'VIDEO', 'VIEWER', 'VIEWPOINT', 'VIGOROUS', 'VILLA', 'VILLAGE',
  'VILLAGER', 'VILLAIN', 'VINEGAR', 'VIOLATE', 'VIOLENT', 'VIOLIN', 'VIPER', 'VIRTUAL', 'VIRUS', 'VISIBLE',
  'VISION', 'VISIT', 'VISITOR', 'VISUAL', 'VITAL', 'VITAMIN', 'VIVID', 'VOCALIST', 'VOLCANO', 'VOLLEYBALL',
  'VOLUME', 'VOLUNTEER', 'VOMIT', 'VORTEX', 'VOTER', 'VOWEL', 'WAFER', 'WAFFLE', 'WAGON', 'WAISTCOAT',
  'WAITER', 'WAITRESS', 'WALKABOUT', 'WALKER', 'WALKING', 'WALLBOARD', 'WALLET', 'WALNUT', 'WALRUS', 'WANDER',
  'WANDERLUST', 'WARDROBE', 'WAREHOUSE', 'WARNING', 'WARRANTY', 'WARRIOR', 'WARSHIP', 'WARTIME', 'WASHBOWL', 'WASTEFUL',
  'WATERFALL', 'WATERPROOF', 'WAVELENGTH', 'WEAKEN', 'WEALTHY', 'WEAPON', 'WEARISOME', 'WEARY', 'WEASEL', 'WEATHER',
  'WEBCAM', 'WEBSITE', 'WEDDING', 'WEDNESDAY', 'WEEKDAY', 'WEEKEND', 'WEEKLY', 'WELCOME', 'WELFARE', 'WEREWOLF',
  'WESTERN', 'WETLAND', 'WHEELCHAIR', 'WHIMSY', 'WHISPER', 'WHISTLE', 'WIDEN', 'WIDESPREAD', 'WIDOW', 'WILDFIRE',
  'WILDLIFE', 'WILLING', 'WINDING', 'WINDMILL', 'WINDOW', 'WINDSCREEN', 'WINDSHIELD', 'WINDY', 'WINNER', 'WINTER',
  'WISDOM', 'WITHDRAW', 'WITHDRAWAL', 'WITHER', 'WITNESS', 'WITTY', 'WIZARD', 'WONDER', 'WONDERFUL', 'WONDROUS',
  'WOODEN', 'WOODPECKER', 'WORKBENCH', 'WORKER', 'WORKING', 'WORKMAN', 'WORKOUT', 'WORKPLACE', 'WORKSHOP', 'WORKTABLE',
  'WORLDLY', 'WORLDVIEW', 'WORLDWIDE', 'WORRIED', 'WORRY', 'WORRYING', 'WORSEN', 'WORSHIP', 'WORTHLESS', 'WORTHWHILE',
  'WORTHY', 'WRAPPING', 'WRESTLING', 'WRISTWATCH', 'WRITER', 'WRITING', 'WRITTEN', 'XYLOPHONE', 'YELLOW', 'YOGURT',
  'YOUTHFUL', 'YUMMY', 'ZEBRA', 'ZEITGEIST', 'ZENITH', 'ZIPPER',
]

export const redWords: string[] = [
  'ABANDONED', 'ABILITY', 'ABORIGINAL', 'ABORIGINE', 'ABSURDITY', 'ABUNDANCE', 'ACADEMIC', 'ACCEPTABLE', 'ACCEPTANCE', 'ACCESSIBILITY',
  'ACCESSIBLE', 'ACCESSORY', 'ACCIDENTAL', 'ACCOMMODATION', 'ACCOMPANY', 'ACCUMULATE', 'ACCURACY', 'ACCUSATION', 'ACHIEVABLE', 'ACHIEVEMENT',
  'ACKNOWLEDGE', 'ACQUAINTANCE', 'ACQUISITION', 'ACTIVITY', 'ADAPTABLE', 'ADDICTION', 'ADDITION', 'ADDITIONAL', 'ADJUSTMENT', 'ADMINISTRATION',
  'ADMINISTRATIVE', 'ADMIRABLE', 'ADMIRATION', 'ADMISSION', 'ADOPTION', 'ADORABLE', 'ADVANCEMENT', 'ADVENTUROUS', 'ADVERSITY', 'ADVERTISEMENT',
  'ADVERTISING', 'AFFECTION', 'AFFECTIONATE', 'AFFORDABLE', 'AGREEMENT', 'AGRICULTURAL', 'AGRICULTURE', 'ALCOHOLIC', 'ALCOHOLISM', 'ALLEGATION',
  'ALLEGORY', 'ALLIANCE', 'ALLOWANCE', 'ALPHABETICAL', 'ALTERNATIVE', 'AMAZEMENT', 'AMBASSADOR', 'AMBIGUITY', 'AMBITION', 'AMBULANCE',
  'AMUSEMENT', 'ANALYSIS', 'ANCHORPERSON', 'ANCIENT', 'ANIMATED', 'ANIMATION', 'ANNIVERSARY', 'ANNOUNCEMENT', 'ANNOYANCE', 'ANONYMOUS',
  'ANTIAIRCRAFT', 'ANTIBACTERIAL', 'ANTICANCER', 'ANTICIPATE', 'ANTICIPATION', 'ANTIPOLLUTION', 'ANTISTATIC', 'ANTIVIRUS', 'APARTMENT', 'APOLOGY',
  'APPEARANCE', 'APPLICATION', 'APPOINTMENT', 'APPRECIATION', 'APPRECIATIVE', 'APPROPRIATE', 'APPROXIMATE', 'ARCHAEOLOGIST', 'ARCHITECTURE', 'ARGUMENT',
  'ARISTOCRACY', 'ARITHMETIC', 'ARMADILLO', 'ARRANGEMENT', 'ARTICULATE', 'ARTIFICIAL', 'ASPIRATION', 'ASSESSMENT', 'ASSIGNMENT', 'ASSISTANCE',
  'ASSOCIATION', 'ASSUMPTION', 'ASSURANCE', 'ASTONISHED', 'ASTONISHING', 'ASTONISHMENT', 'ASTRONOMER', 'ASTRONOMY', 'ATTACHMENT', 'ATTAINABLE',
  'ATTAINMENT', 'ATTENDANCE', 'ATTENTION', 'ATTRACTION', 'ATTRACTIVENESS', 'ATYPICAL', 'AUDIENCE', 'AUDITION', 'AUTHORITATIVE', 'AUTHORITY',
  'AUTOMATIC', 'AUXILIARY', 'AVAILABILITY', 'AVAILABLE', 'AWARENESS', 'BABYSITTER', 'BACKPACKING', 'BAROMETER', 'BASEMENT', 'BATTLEFIELD',
  'BENEFICIAL', 'BENEVOLENCE', 'BENEVOLENT', 'BEWILDERMENT', 'BIOCHEMISTRY', 'BIOGRAPHY', 'BIOLOGICAL', 'BIOLOGY', 'BIOTECHNOLOGY', 'BLINDNESS',
  'BRAINSTORMING', 'BREATHTAKING', 'BROADCASTER', 'BROTHERHOOD', 'BUREAUCRACY', 'BUSINESS', 'BUSINESSMAN', 'BUSINESSWOMAN', 'CAFETERIA', 'CALCULATION',
  'CALCULATOR', 'CALMNESS', 'CAPABILITY', 'CAPACITY', 'CAPPUCCINO', 'CARELESSNESS', 'CARICATURE', 'CATASTROPHE', 'CATASTROPHIC', 'CATEGORY',
  'CATERPILLAR', 'CAULIFLOWER', 'CELEBRATION', 'CELEBRITY', 'CEMETERY', 'CEREMONY', 'CERTIFICATE', 'CERTIFICATION', 'CHALLENGING', 'CHAMPIONSHIP',
  'CHARACTERISTIC', 'CHARITY', 'CHEERFULNESS', 'CHEERLEADING', 'CHEMICAL', 'CHEMOTHERAPY', 'CHILDHOOD', 'CHRONOLOGICAL', 'CIRCUMSTANCE', 'CITIZENSHIP',
  'CLASSICAL', 'CLASSIFICATION', 'CLEARNESS', 'CLERICAL', 'COALITION', 'COHERENCE', 'COINCIDENCE', 'COLLECTION', 'COLLISION', 'COLLOCATION',
  'COMBINATION', 'COMFORTABLE', 'COMMEMORATE', 'COMMERCIAL', 'COMMISSION', 'COMMITMENT', 'COMMONWEALTH', 'COMMUNICATE', 'COMMUNICATION', 'COMMUNICATIVE',
  'COMMUNITY', 'COMPARATIVE', 'COMPARISON', 'COMPASSION', 'COMPASSIONATE', 'COMPATIBLE', 'COMPENSATION', 'COMPETENCE', 'COMPETITION', 'COMPETITIVE',
  'COMPETITOR', 'COMPLEMENT', 'COMPLETION', 'COMPLEXITY', 'COMPLICATED', 'COMPLIMENT', 'COMPOSITION', 'COMPREHENSION', 'COMPREHENSIVE', 'COMPRESSION',
  'COMPULSORY', 'CONCEIVABLE', 'CONCENTRATE', 'CONCENTRATION', 'CONCEPTION', 'CONCESSION', 'CONCLUSION', 'CONDITION', 'CONFERENCE', 'CONFERENCING',
  'CONFESSION', 'CONFIDENCE', 'CONFIRMATION', 'CONFUSION', 'CONGRATULATE', 'CONJUNCTION', 'CONSCIENCE', 'CONSCIOUSNESS', 'CONSEQUENCE', 'CONSERVATION',
  'CONSERVATIVE', 'CONSIDERABLE', 'CONSIDERATION', 'CONSOLATION', 'CONSPIRACY', 'CONSTITUTION', 'CONSTRUCTION', 'CONSUMPTION', 'CONTAMINATE', 'CONTEMPORARY',
  'CONTRADICTION', 'CONTRIBUTION', 'CONTROVERSIAL', 'CONTROVERSY', 'CONVENIENCE', 'CONVENTION', 'CONVENTIONAL', 'CONVERSATION', 'CONVERSION', 'COOPERATION',
  'COOPERATIVE', 'CORNERSTONE', 'CORPORATION', 'CORRECTION', 'CORRECTNESS', 'CORRESPONDENCE', 'CORRESPONDENT', 'CORRESPONDING', 'CORRUPTION', 'COUNTRYSIDE',
  'COUNTRYWIDE', 'CREATION', 'CREATIVITY', 'CRITICAL', 'CRITICISM', 'CRUCIAL', 'CULMINATION', 'CURIOSITY', 'CURRICULUM', 'CYBERADDICT',
  'CYBERSCHOOL', 'DARKNESS', 'DECADENCE', 'DECEPTION', 'DECISION', 'DECLARATION', 'DECOMPOSITION', 'DECORATION', 'DECORATIVE', 'DEDICATION',
  'DEDUCTION', 'DEFIANCE', 'DEFICIENCY', 'DEFINITION', 'DEFORESTATION', 'DELIBERATE', 'DELICACY', 'DELIVERY', 'DEMOCRACY', 'DEMOCRATIC',
  'DEMONSTRATE', 'DEMONSTRATION', 'DEPARTMENT', 'DEPENDABLE', 'DEPRESSION', 'DESCRIPTION', 'DESCRIPTIVE', 'DESIRABLE', 'DESOLATION', 'DESPERATION',
  'DESTINATION', 'DESTRUCTION', 'DESTRUCTIVE', 'DETACHMENT', 'DETERMINATION', 'DETERMINED', 'DETERMINER', 'DEVASTATING', 'DEVELOPED', 'DEVELOPING',
  'DEVELOPMENT', 'DEVOTION', 'DICTIONARY', 'DIFFERENCE', 'DIFFICULTY', 'DIGNITY', 'DILIGENCE', 'DIMENSION', 'DIRECTION', 'DISABILITY',
  'DISADVANTAGE', 'DISAGREEMENT', 'DISAPPEARANCE', 'DISAPPOINTED', 'DISAPPOINTING', 'DISAPPOINTMENT', 'DISAPPROVAL', 'DISCOVERY', 'DISCRIMINATE', 'DISCRIMINATION',
  'DISCUSSION', 'DISHONESTY', 'DISILLUSION', 'DISORDERLY', 'DISPENSABLE', 'DISPLEASURE', 'DISPOSITION', 'DISQUALIFY', 'DISSATISFACTION', 'DISSATISFIED',
  'DISTANCE', 'DISTINCTION', 'DISTINGUISH', 'DISTINGUISHED', 'DISTORTION', 'DISTRACTION', 'DISTRESSING', 'DISTRIBUTION', 'DISTRIBUTOR', 'DISTURBANCE',
  'DIVERSION', 'DIVISION', 'DOCUMENT', 'DOCUMENTARY', 'DONATION', 'DORMITORY', 'DUPLICATION', 'EAGERNESS', 'ECOLOGICAL', 'ECOLOGIST',
  'ECOLOGY', 'ECONOMIC', 'ECONOMICAL', 'ECONOMICS', 'ECONOMIST', 'ECOSYSTEM', 'EDITION', 'EDITORIAL', 'EDUCATED', 'EDUCATION',
  'EDUCATIONAL', 'EDUCATOR', 'EFFECTIVENESS', 'EFFICIENCY', 'EFFICIENT', 'ELECTION', 'ELECTRICAL', 'ELECTRICIAN', 'ELECTRICITY', 'ELECTRONIC',
  'ELECTRONICS', 'ELEGANCE', 'ELEMENT', 'ELEMENTAL', 'ELEMENTARY', 'ELEVATOR', 'ELIGIBLE', 'ELIMINATE', 'ELOQUENCE', 'EMBARRASSED',
  'EMBARRASSING', 'EMBARRASSMENT', 'EMERGENCE', 'EMERGENCY', 'EMOTION', 'EMOTIONAL', 'EMPLOYMENT', 'ENCOURAGEMENT', 'ENCOURAGING', 'ENDANGERED',
  'ENDURANCE', 'ENERGETIC', 'ENGAGEMENT', 'ENGINEERING', 'ENJOYMENT', 'ENTERTAINER', 'ENTERTAINING', 'ENTERTAINMENT', 'ENTHUSIASTIC', 'ENTRANCE',
  'ENTREPRENEUR', 'ENVIRONMENT', 'ENVIRONMENTAL', 'ENVIRONMENTALIST', 'EPIPHANY', 'EQUALITY', 'EQUATION', 'EQUIPMENT', 'EQUITY', 'ERUPTION',
  'ESCALATOR', 'ESTABLISHMENT', 'ESTIMATED', 'ETERNITY', 'EVACUATION', 'EVALUATION', 'EVERLASTING', 'EVERYDAY', 'EVIDENCE', 'EVOLUTION',
  'EXACTNESS', 'EXAGGERATE', 'EXAGGERATION', 'EXAMINATION', 'EXAMINER', 'EXCELLENCE', 'EXCEPTION', 'EXCEPTIONAL', 'EXCITEMENT', 'EXCLUSION',
  'EXCURSION', 'EXECUTION', 'EXECUTIVE', 'EXHAUSTION', 'EXHIBITION', 'EXISTENCE', 'EXPANSION', 'EXPECTATION', 'EXPEDITION', 'EXPERIENCE',
  'EXPERIENCED', 'EXPERIMENT', 'EXPLANATION', 'EXPLORATION', 'EXPLOSION', 'EXPRESSION', 'EXTENSION', 'EXTINCTION', 'EXTRAORDINARY', 'FACILITATE',
  'FACILITIES', 'FACILITY', 'FASCINATED', 'FASCINATING', 'FASCINATION', 'FASHIONABLE', 'FIGURATIVE', 'FINANCIAL', 'FIREFIGHTER', 'FIRMNESS',
  'FLEXIBILITY', 'FONDNESS', 'FORMATION', 'FORMIDABLE', 'FORTHCOMING', 'FOUNDATION', 'FRAGMENT', 'FRAGRANCE', 'FRICTION', 'FRIENDLINESS',
  'FRIENDSHIP', 'FRIGHTENING', 'FRUSTRATION', 'FUNCTION', 'FUNCTIONALITY', 'FUNDAMENTAL', 'GENERATION', 'GENEROSITY', 'GEOGRAPHICAL', 'GEOGRAPHY',
  'GEOLOGY', 'GERRYMANDER', 'GOVERNMENT', 'GOVERNMENTAL', 'GRACEFULNESS', 'GRADUATION', 'GRANDDAUGHTER', 'GRANDFATHER', 'GRANDMOTHER', 'GRANDPARENT',
  'GRAVITATION', 'GRAVITY', 'GREATNESS', 'GUIDANCE', 'HAIRDRESSER', 'HANDICAPPED', 'HANDKERCHIEF', 'HANDWRITING', 'HAPPINESS', 'HARDSHIP',
  'HARMONICA', 'HEADQUARTERS', 'HEADTEACHER', 'HEARTBREAKING', 'HEGEMONY', 'HELICOPTER', 'HESITATION', 'HISTORICAL', 'HOSPITABLE', 'HOSPITALITY',
  'HOUSEKEEPER', 'HOUSEMASTER', 'HUMANITY', 'HUMILIATING', 'HUMILIATION', 'HUMMINGBIRD', 'IDENTICAL', 'IDENTIFICATION', 'IDENTIFY', 'IDENTITY',
  'IDEOLOGY', 'IGNORANCE', 'ILLUMINATE', 'ILLUSION', 'ILLUSTRATION', 'IMAGINARY', 'IMAGINATION', 'IMITATION', 'IMMIGRATION', 'IMMORTALITY',
  'IMPERATIVE', 'IMPERMANENT', 'IMPLEMENT', 'IMPLICATION', 'IMPORTANCE', 'IMPOSSIBILITY', 'IMPOSSIBLE', 'IMPRACTICAL', 'IMPRESSION', 'IMPRESSIONISM',
  'IMPRESSIONIST', 'IMPRISONMENT', 'IMPROBABLE', 'IMPROVEMENT', 'INACCURATE', 'INADEQUATE', 'INANIMATE', 'INCONVENIENT', 'INCREDIBLE', 'INCURABLE',
  'INDEPENDENCE', 'INDEPENDENT', 'INDESCRIBABLE', 'INDIFFERENT', 'INDIGNITY', 'INDISPENSABLE', 'INDIVIDUAL', 'INEFFECTIVE', 'INEVITABLE', 'INEXPENSIVE',
  'INEXPERIENCED', 'INFECTION', 'INFERENCE', 'INFINITIVE', 'INFLAMMATION', 'INFLAMMATORY', 'INFLATION', 'INFLUENCE', 'INFLUENTIAL', 'INFORMATION',
  'INFORMATIVE', 'INFRINGEMENT', 'INHABITANT', 'INITIATIVE', 'INJECTION', 'INNOVATION', 'INNOVATIVE', 'INNOVATOR', 'INSCRIPTION', 'INSEPARABLE',
  'INSPECTION', 'INSPIRATION', 'INSPIRATIONAL', 'INSTANCE', 'INSTITUTION', 'INSTRUCTION', 'INSTRUMENT', 'INSUFFICIENT', 'INSURANCE', 'INTELLECTUAL',
  'INTELLIGENCE', 'INTELLIGENT', 'INTENTION', 'INTERACTION', 'INTERACTIVE', 'INTERESTED', 'INTERESTING', 'INTERMEDIATE', 'INTERMISSION', 'INTERNATIONAL',
  'INTERPERSONAL', 'INTERPRETATION', 'INTERPRETER', 'INTERRUPTION', 'INTERSECTION', 'INTERVIEWEE', 'INTERVIEWER', 'INTRANSITIVE', 'INTRAVENOUS', 'INTRODUCTION',
  'INTRUSION', 'INVARIABLE', 'INVASION', 'INVENTION', 'INVESTIGATE', 'INVESTIGATION', 'INVESTIGATOR', 'INVESTMENT', 'INVISIBLE', 'INVITATION',
  'INVOLVEMENT', 'IRRATIONAL', 'IRREGULAR', 'IRRESISTIBLE', 'IRRESPONSIBLE', 'IRRITATED', 'IRRITATING', 'IRRITATION', 'ISOLATION', 'JOURNALISM',
  'KINDNESS', 'LABORATORY', 'LATECOMER', 'LAZINESS', 'LEADERSHIP', 'LEGENDARY', 'LEGISLATION', 'LEGISLATIVE', 'LEGISLATOR', 'LEGISLATURE',
  'LEGITIMATE', 'LIBERATION', 'LIKENESS', 'LIMITATION', 'LITERARY', 'LITERATURE', 'LOCATION', 'LOGICAL', 'LONELINESS', 'LOUDSPEAKER',
  'MAGICAL', 'MAGNETISM', 'MAGNIFICENT', 'MAINTENANCE', 'MAJORITY', 'MANAGEMENT', 'MANIFESTO', 'MANIPULATE', 'MANUFACTURE', 'MANUFACTURER',
  'MANUFACTURING', 'MASTERPIECE', 'MATHEMATICAL', 'MATHEMATICIAN', 'MATHEMATICS', 'MEASUREMENT', 'MECHANICAL', 'MEDICAL', 'MEDICATION', 'MEDITATION',
  'MEDITERRANEAN', 'MELANCHOLY', 'MEMBERSHIP', 'MEMORABLE', 'MERCHANDISE', 'METAMORPHOSIS', 'MICROCOMPUTER', 'MICROORGANISM', 'MICROSCOPIC', 'MICROSCOPY',
  'MIGRATION', 'MILITARY', 'MILLIONAIRE', 'MINORITY', 'MISCONCEPTION', 'MISERABLE', 'MISTRUSTFUL', 'MISUNDERSTAND', 'MISUNDERSTANDING', 'MOBILITY',
  'MODIFICATION', 'MOMENTARY', 'MONASTERY', 'MONUMENT', 'MORALITY', 'MOTIVATED', 'MOTIVATION', 'MOTORCYCLE', 'MOUNTAINTOP', 'MOVEMENT',
  'MUSICAL', 'MUTABILITY', 'NARCISSISTIC', 'NATIONALIST', 'NATIONALITY', 'NAVIGATION', 'NECESSARY', 'NECESSITY', 'NEGOTIATION', 'NERVOUSNESS',
  'NOBILITY', 'NOMINATION', 'NONPROFESSIONAL', 'NORTHEASTERN', 'NORTHWESTERN', 'NOTICEABLE', 'NOTICEBOARD', 'NOURISHMENT', 'NUISANCE', 'NUMERICAL',
  'NUTRITION', 'OBEDIENCE', 'OBITUARY', 'OBJECTION', 'OBLIGATION', 'OBSERVATION', 'OBSERVATORY', 'OBSESSION', 'OCCASION', 'OCCASIONAL',
  'OCCUPATION', 'OFFICIAL', 'OINTMENT', 'OPERATION', 'OPERATOR', 'OPPORTUNITY', 'OPPOSITION', 'OPPRESSION', 'OPTIMISM', 'OPTIMISTIC',
  'ORDINARY', 'ORGANISM', 'ORIGINAL', 'ORIGINALITY', 'ORIGINATE', 'ORNAMENT', 'OUTDISTANCE', 'OUTSTANDING', 'OVERESTIMATE', 'OVERSHADOW',
  'OVERWHELMING', 'PARALYSIS', 'PARAMEDIC', 'PARATROOPER', 'PARLIAMENT', 'PARTICIPANT', 'PARTICIPATE', 'PARTICIPATION', 'PARTICIPLE', 'PARTICULAR',
  'PARTNERSHIP', 'PATIENCE', 'PATRIOTISM', 'PAVEMENT', 'PENICILLIN', 'PERCEPTION', 'PERFORMANCE', 'PERMANENCE', 'PERMISSION', 'PERSEVERANCE',
  'PERSISTENCE', 'PERSONALITY', 'PERSONIFICATION', 'PERSONIFY', 'PERSPECTIVE', 'PERSPIRATION', 'PERSUASION', 'PESSIMISTIC', 'PHENOMENON', 'PHILOSOPHER',
  'PHILOSOPHICAL', 'PHILOSOPHY', 'PHOTOCOPY', 'PHOTOGRAPHER', 'PHOTOGRAPHY', 'PHYSICAL', 'PICTURESQUE', 'POLARITY', 'POLICEMAN', 'POLICEWOMAN',
  'POLITENESS', 'POLITICAL', 'POLITICIAN', 'POLITY', 'POLLUTION', 'POPULARITY', 'POPULATION', 'POSITION', 'POSSESSION', 'POSSIBILITY',
  'PRACTICAL', 'PRACTICALITY', 'PREDICAMENT', 'PREDICATIVE', 'PREDICTABLE', 'PREDICTION', 'PREFERABLE', 'PREFERENCE', 'PREHISTORIC', 'PREINDUSTRIAL',
  'PRELIMINARY', 'PREPARATION', 'PREPOSITION', 'PRESCRIPTION', 'PRESENCE', 'PRESENTATION', 'PRESERVATION', 'PRESIDENCY', 'PRESIDENTIAL', 'PRESTIGIOUS',
  'PREVENTION', 'PRIORITY', 'PROBABILITY', 'PROCRASTINATION', 'PRODUCTION', 'PROFESSION', 'PROFESSIONAL', 'PROFITABLE', 'PROGRAMMING', 'PROGRESSIVE',
  'PROHIBITION', 'PROJECTION', 'PROMINENCE', 'PROMOTION', 'PRONUNCIATION', 'PROPAGANDA', 'PROPORTION', 'PROSPERITY', 'PROTECTION', 'PROVISION',
  'PROXIMITY', 'PSYCHOLOGICAL', 'PSYCHOLOGIST', 'PSYCHOLOGY', 'PUBLICATION', 'PUBLICITY', 'PUNCTUALITY', 'PUNCTUATION', 'PUNISHMENT', 'PURPOSEFUL',
  'QUALIFICATION', 'QUALITY', 'QUANTITY', 'QUARRELSOME', 'QUESTION', 'QUESTIONNAIRE', 'QUOTATION', 'RACIAL', 'RADIATION', 'RADICAL',
  'REACTION', 'REALITY', 'REASONABLE', 'RECEPTION', 'RECEPTIONIST', 'RECESSION', 'RECOGNITION', 'RECOLLECTION', 'RECOMMENDABLE', 'RECOMMENDATION',
  'RECONSIDER', 'RECOVERY', 'RECREATION', 'RECTANGULAR', 'REDEMPTION', 'REDUCTION', 'REFERENCE', 'REFINERY', 'REFLECTION', 'REFRESHMENTS',
  'REFRIGERATOR', 'REGISTRATION', 'REGULATION', 'REINFORCEMENT', 'REJECTION', 'RELATION', 'RELATIONSHIP', 'RELATIVITY', 'RELAXATION', 'REMARKABLE',
  'REMEMBRANCE', 'REPETITION', 'REPLACEMENT', 'REPRESENTATIVE', 'REPRESSION', 'REPUTATION', 'REQUIREMENT', 'RESERVATION', 'RESIDENCE', 'RESIDENTIAL',
  'RESIGNATION', 'RESISTANCE', 'RESOLUTION', 'RESONANCE', 'RESPECTABLE', 'RESPIRATION', 'RESPIRATORY', 'RESPONSIBILITY', 'RESPONSIBLE', 'RESTRICTION',
  'RETIREMENT', 'REUNIFICATION', 'REVELATION', 'REVERENCE', 'REVISION', 'REVOLUTION', 'REVOLUTIONARY', 'RHINOCEROS', 'RIDICULOUS', 'RIGHTEOUSNESS',
  'SALESMANSHIP', 'SALESPERSON', 'SALESWOMAN', 'SANITARY', 'SANITATION', 'SATISFACTION', 'SATISFACTORY', 'SCHADENFREUDE', 'SCHOLARSHIP', 'SCHOLASTICISM',
  'SCHOOLTEACHER', 'SCREWDRIVER', 'SECONDARY', 'SECRETARY', 'SECURITY', 'SELECTION', 'SEMICOLON', 'SENSATION', 'SENTENCE', 'SEPARATION',
  'SEQUENCE', 'SERENDIPITY', 'SERENITY', 'SETTLEMENT', 'SHAKESPEAREAN', 'SHOPLIFTING', 'SHORTNESS', 'SICKNESS', 'SIGNIFICANCE', 'SIGNIFICANT',
  'SIMILARITY', 'SIMPLIFICATION', 'SIMULTANEOUS', 'SINCERITY', 'SITUATION', 'SKATEBOARDER', 'SKATEBOARDING', 'SNOWBOARDING', 'SOCIAL', 'SOFTNESS',
  'SOLIDITY', 'SOLILOQUY', 'SOLUTION', 'SOPHISTICATED', 'SOVEREIGNTY', 'SPACESHIP', 'SPECIAL', 'SPECTACULAR', 'SPOKESWOMAN', 'SPORTSMANSHIP',
  'STABILITY', 'STAGNATION', 'STARVATION', 'STATEMENT', 'STIMULATION', 'STOICISM', 'STOMACHACHE', 'STORYTELLER', 'STRAIGHTFORWARD', 'SUBCONSCIOUS',
  'SUBCONTINENT', 'SUBDIVISION', 'SUBJUNCTIVE', 'SUBSTANCE', 'SUBSTANTIAL', 'SUFFICIENT', 'SUGGESTION', 'SUPERHERO', 'SUPERINTENDENT', 'SUPERLATIVE',
  'SUPERMARKET', 'SUPERSTITION', 'SUPERVISION', 'SUPERVISOR', 'SUPPLEMENT', 'SURROUNDING', 'SURROUNDINGS', 'SURVEILLANCE', 'SYMPATHETIC', 'SYSTEMATIC',
  'TECHNICAL', 'TECHNOLOGICAL', 'TECHNOLOGY', 'TELECOMMUNICATIONS', 'TELEVISION', 'TEMPERATURE', 'TEMPORARY', 'TEMPTATION', 'TENDERNESS', 'TERRITORY',
  'TERRORISM', 'TESTIMONY', 'THERMOMETER', 'THICKNESS', 'THREATENING', 'THUNDERSTORM', 'TIMELINESS', 'TIMETABLE', 'TIREDNESS', 'TORTOISESHELL',
  'TOURNAMENT', 'TRADITION', 'TRADITIONAL', 'TRAJECTORY', 'TRANSCENDENCE', 'TRANSFORMATION', 'TRANSFUSION', 'TRANSITION', 'TRANSITIONAL', 'TRANSLATION',
  'TRANSMISSION', 'TRANSPARENT', 'TRANSPORTATION', 'TREATMENT', 'TROPICAL', 'TROUBLESOME', 'TRUSTWORTHY', 'TRUTHFULNESS', 'TUBERCULOSIS', 'TURBULENCE',
  'TYPICAL', 'UNACCEPTABLE', 'UNATTRACTIVE', 'UNAVAILABLE', 'UNBEARABLE', 'UNBEATABLE', 'UNBELIEVABLE', 'UNCERTAINTY', 'UNCHARACTERISTIC', 'UNCOMFORTABLE',
  'UNCONCERNED', 'UNCONSCIOUS', 'UNCONTROLLABLE', 'UNDERESTIMATE', 'UNDERGRADUATE', 'UNDERGROUND', 'UNDERSTANDABLE', 'UNDERSTANDING', 'UNDERTAKER', 'UNDERWATER',
  'UNEMPLOYMENT', 'UNENTHUSIASTIC', 'UNEXPECTED', 'UNFAMILIAR', 'UNFASHIONABLE', 'UNFORESEEN', 'UNFORGETTABLE', 'UNFORTUNATE', 'UNHAPPINESS', 'UNIMAGINABLE',
  'UNIMPORTANT', 'UNINTERESTED', 'UNINTERESTING', 'UNIVERSAL', 'UNIVERSITY', 'UNLIKELY', 'UNLIMITED', 'UNMISTAKABLE', 'UNNATURAL', 'UNNECESSARY',
  'UNOFFICIAL', 'UNPOPULAR', 'UNPREDICTABLE', 'UNREALISTIC', 'UNREASONABLE', 'UNRELATED', 'UNRELIABLE', 'UNSATISFACTORY', 'UNSUCCESSFUL', 'UNSUITABLE',
  'UNTALENTED', 'UNUSUALNESS', 'UTILITY', 'VACATION', 'VANITY', 'VARIATION', 'VEGETABLE', 'VEGETARIAN', 'VELOCITY', 'VIBRATION',
  'VIOLENCE', 'VOCABULARY', 'WATERMELON', 'WEAKNESS', 'WILDERNESS', 'WILLINGNESS', 'WINDSURFING', 'WOODCARVING', 'WORKAHOLIC',
]

// Money round pool — distinct high-energy phrases for the final screen.
export const moneyWords: string[] = [
  'AIR GUITAR', 'ALIEN ABDUCTION', 'AWARD SHOW', 'BACKSTAGE PASS', 'BACKYARD BBQ', 'BALLOON DROP', 'BATTLE OF THE BANDS', 'BEACH BONFIRE', 'BIGFOOT SIGHTING', 'BIRTHDAY CAKE',
  'BLACK LIGHT', 'BLANKET FORT', 'BLOCK PARTY', 'BLOW UP POOL', 'BOARD GAME NIGHT', 'BOBA TEA', 'BOTTLE ROCKET', 'BRAIN FREEZE', 'BRUNCH BUFFET', 'BUBBLE MACHINE',
  'CAMPUS LEGEND', 'CAR CHASE', 'CARD TRICK', 'CEREAL MASCOT', 'CHAMPAGNE TOWER', 'CHEESE FOUNTAIN', 'CLASS GROUP CHAT', 'CLOWN CAR', 'COFFEE RUN', 'CONFETTI CANNON',
  'COSTUME PARTY', 'COUNTDOWN CLOCK', 'CRASH PAD', 'DANCE BATTLE', 'DANCE FLOOR', 'DESSERT TABLE', 'DORM ROOM', 'DOUBLE DATE', 'DRAMA QUEEN', 'ENERGY DRINK',
  'ESCAPE ROOM', 'FAKE ID', 'FANTASY DRAFT', 'FASHION SHOW', 'FAST FOOD DRIVE THRU', 'FILM PREMIERE', 'FINAL EXAM', 'FIRE DRILL', 'FOAM FINGER', 'FOOD COMA',
  'FOOD TRUCK', 'FRAT HOUSE', 'FREE SAMPLE', 'FREE THROW', 'FRIEND ZONE', 'GAME CONTROLLER', 'GAME DAY', 'GHOST STORY', 'GLITTER BOMB', 'GROUP PROJECT',
  'HALL PASS', 'HAUNTED HOUSE', 'HIDDEN TALENT', 'HIGH FIVE', 'HOMECOMING DANCE', 'HOT SAUCE', 'HOUSE PARTY', 'ICE BREAKER', 'ICE CREAM TRUCK', 'INSIDE JOKE',
  'INSTANT RAMEN', 'JELLO SHOT', 'JUKEBOX HERO', 'JUMP SCARE', 'KARAOKE NIGHT', 'KITCHEN SINK', 'LASER TAG', 'LAST CALL', 'LAUNDRY DAY', 'LIGHT SABER',
  'LIP SYNC', 'LIVE STREAM', 'LOCKER ROOM', 'LOST AND FOUND', 'MAGIC SHOW', 'MARCHING BAND', 'MASCOT SUIT', 'MIC DROP', 'MIDNIGHT SNACK', 'MOVIE TRAILER',
  'MUSIC FESTIVAL', 'NERF WAR', 'NERVOUS LAUGH', 'OPEN MIC', 'PARTY BUS', 'PARTY HAT', 'PEP RALLY', 'PHONE CHARGER', 'PHOTO BOOTH', 'PILLOW FIGHT',
  'PIZZA DELIVERY', 'PODCAST HOST', 'POOL FLOAT', 'POP QUIZ', 'POWER NAP', 'PRANK CALL', 'PROM PHOTO', 'QUARTERBACK SNEAK', 'RAFFLE TICKET', 'RAIN CHECK',
  'RED CARPET', 'ROAD TRIP', 'ROLLER RINK', 'ROOFTOP PARTY', 'ROOMMATE CODE', 'SCAVENGER HUNT', 'SCHOOL SPIRIT', 'SECRET MENU', 'SELFIE STICK', 'SHOPPING CART',
  'SILENT DISCO', 'SLEEPOVER STORY', 'SNACK TABLE', 'SNOW DAY', 'SOAP OPERA', 'SODA FOUNTAIN', 'SPACE CAMP', 'SPIRIT WEEK', 'SPORTS BAR', 'SPRING BREAK',
  'STAGE DIVE', 'STUDENT SECTION', 'STUDY BREAK', 'SUMMER CAMP', 'SURPRISE PARTY', 'TACO TRUCK', 'TAILGATE PARTY', 'TALENT SHOW', 'TEAM PHOTO', 'TEXT MESSAGE',
  'TEXT THREAD', 'THEME SONG', 'THRIFT STORE', 'TIKTOK DANCE', 'TOGA PARTY', 'TRIVIA NIGHT', 'UGLY SWEATER', 'VENDING MACHINE', 'VICTORY SONG', 'VIDEO GAME BOSS',
  'VIP SECTION', 'VOICE MEMO', 'WATER BALLOON', 'WATER PARK', 'WEEKEND PLANS', 'WIFI PASSWORD', 'YEARBOOK PHOTO', 'YOGA POSE', 'ZIP LINE', 'ZOOM CALL',
]

const WORD_POOLS: WordPools = {
  bidding: Array.from(new Set([...greenWords, ...yellowWords])),
  green: greenWords,
  yellow: yellowWords,
  red: redWords,
  money: moneyWords,
}

export function getWordPools(): WordPools {
  return {
    bidding: [...WORD_POOLS.bidding],
    green: [...WORD_POOLS.green],
    yellow: [...WORD_POOLS.yellow],
    red: [...WORD_POOLS.red],
    money: [...WORD_POOLS.money],
  }
}

export function getWordsForDeck(deckId: WordDeckId, count: number, usedWords: string[] = []): string[] {
  return pickWords(WORD_POOLS[deckId], count, usedWords)
}

export function getBiddingWords(usedWords: string[] = []): string[] {
  return getWordsForDeck('bidding', 5, usedWords)
}

export function getColorWords(difficulty: Difficulty, usedWords: string[] = []): string[] {
  return getWordsForDeck(difficulty, 5, usedWords)
}

export function getMoneyWords(usedWords: string[] = []): string[] {
  return getWordsForDeck('money', 10, usedWords)
}

const BLOCKED_WORDS = new Set([
  'GOOK',
  'RAPE',
  'RETARD',
  'SLAVE',
  'SLAVERY',
  'HOLOCAUST',
  'MASSACRE',
  'TORTURE',
])

const VALID_WORD_DECK_IDS = new Set<WordDeckId>(['bidding', 'green', 'yellow', 'red', 'money'])
const VALID_DIFFICULTIES = new Set<WordDeck['difficulty']>(['green', 'yellow', 'red', 'money'])
const WORD_ENTRY_PATTERN = /^[A-Z0-9][A-Z0-9 ]*$/
const SOURCE_ID_PATTERN = /^[a-z0-9][a-z0-9-]*$/

function canonicalWordEntry(word: string): string {
  return word.trim().replace(/\s+/g, ' ')
}

function spacingInsensitiveKey(word: string): string {
  return canonicalWordEntry(word).replace(/\s/g, '')
}

function isIsoDateOnly(value: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false
  const date = new Date(`${value}T00:00:00.000Z`)
  if (Number.isNaN(date.getTime())) return false
  return date.toISOString().slice(0, 10) === value
}

export function getWordDecks(): WordDeck[] {
  return [
    {
      id: 'green',
      difficulty: 'green',
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: greenWords,
    },
    {
      id: 'yellow',
      difficulty: 'yellow',
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: yellowWords,
    },
    {
      id: 'red',
      difficulty: 'red',
      sourceIds: ['cefr-j-olp'],
      words: redWords,
    },
    {
      id: 'bidding',
      difficulty: 'yellow',
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: WORD_POOLS.bidding,
    },
    {
      id: 'money',
      difficulty: 'money',
      sourceIds: ['curated-party'],
      words: moneyWords,
    },
  ]
}

export function getWordBankSummary(
  decks: WordDeck[] = getWordDecks(),
  sources: WordSource[] = WORD_BANK_SOURCES
): WordBankSummary {
  const deckCounts: Record<WordDeckId, number> = {
    bidding: 0,
    green: 0,
    yellow: 0,
    red: 0,
    money: 0,
  }
  const deckSummaries = decks.map(deck => {
    deckCounts[deck.id] = deck.words.length
    return {
      id: deck.id,
      difficulty: deck.difficulty,
      count: deck.words.length,
      sourceIds: [...deck.sourceIds],
    }
  })

  return {
    totalPlayableWords: deckSummaries
      .filter(deck => deck.id !== 'bidding')
      .reduce((total, deck) => total + deck.count, 0),
    deckCounts,
    sourceCount: sources.length,
    decks: deckSummaries,
  }
}

export function validateWordBank(
  decks: WordDeck[] = getWordDecks(),
  sources: WordSource[] = WORD_BANK_SOURCES
): string[] {
  const errors: string[] = []
  const sourceIds = new Set(sources.map(source => source.id))
  const seenSourceIds = new Set<string>()
  const seenDeckIds = new Set<string>()
  const playableWordOwners = new Map<string, string>()
  const playableNearDuplicateOwners = new Map<string, { deckId: string; word: string }>()

  if (!sources.length) errors.push('word bank must include at least one source')
  sources.forEach(source => {
    const sourceId = source.id || '(missing id)'
    if (!source.id || !source.name || !source.url || !source.licenseNote || !source.importedAt || !source.transform) {
      errors.push(`source ${sourceId} is missing attribution metadata`)
    }
    if (source.id) {
      if (seenSourceIds.has(source.id)) errors.push(`source ${source.id} is duplicated`)
      seenSourceIds.add(source.id)
      if (!SOURCE_ID_PATTERN.test(source.id)) errors.push(`source ${source.id} has invalid id`)
    }
    if (source.importedAt && !isIsoDateOnly(source.importedAt)) {
      errors.push(`source ${sourceId} has invalid import date ${source.importedAt}`)
    }
    if (source.url && !/^(https?:\/\/|local:)/.test(source.url)) {
      errors.push(`source ${sourceId} has invalid url ${source.url}`)
    }
  })

  decks.forEach(deck => {
    const deckId = typeof deck.id === 'string' && deck.id ? deck.id : '(missing id)'
    if (seenDeckIds.has(deckId)) errors.push(`${deckId} deck id is duplicated`)
    seenDeckIds.add(deckId)
    if (!VALID_WORD_DECK_IDS.has(deck.id)) errors.push(`${deckId} deck has invalid id`)
    if (!VALID_DIFFICULTIES.has(deck.difficulty)) errors.push(`${deckId} deck has invalid difficulty ${deck.difficulty}`)
    if (!Array.isArray(deck.sourceIds) || deck.sourceIds.length === 0) errors.push(`${deckId} deck must include source attribution`)
    if (!Array.isArray(deck.words) || !deck.words.length) errors.push(`${deckId} deck is empty`)

    const deckSourceIds = new Set<string>()
    ;(Array.isArray(deck.sourceIds) ? deck.sourceIds : []).forEach(sourceId => {
      if (deckSourceIds.has(sourceId)) errors.push(`${deck.id} deck repeats source ${sourceId}`)
      deckSourceIds.add(sourceId)
      if (!sourceIds.has(sourceId)) errors.push(`${deck.id} deck references unknown source ${sourceId}`)
    })

    const seen = new Set<string>()
    const nearSeen = new Map<string, string>()
    ;(Array.isArray(deck.words) ? deck.words : []).forEach((word, index) => {
      const label = `${deckId}[${index}]`
      if (typeof word !== 'string' || !word.trim()) {
        errors.push(`${label} is empty`)
        return
      }
      const canonical = canonicalWordEntry(word)
      if (word !== canonical) errors.push(`${label} must use normalized spacing: ${word}`)
      if (canonical.length > 32) errors.push(`${label} is too long: ${canonical}`)
      if (canonical !== canonical.toUpperCase()) errors.push(`${label} must be uppercase: ${canonical}`)
      if (!WORD_ENTRY_PATTERN.test(canonical)) errors.push(`${label} has invalid characters: ${canonical}`)
      if (BLOCKED_WORDS.has(canonical)) errors.push(`${label} is blocked by safety filter: ${canonical}`)
      if (seen.has(canonical)) errors.push(`${deckId} contains duplicate word: ${canonical}`)
      seen.add(canonical)

      const nearKey = spacingInsensitiveKey(canonical)
      const previousNearWord = nearSeen.get(nearKey)
      if (previousNearWord && previousNearWord !== canonical) {
        errors.push(`${deckId} contains near-duplicate word: ${canonical} matches ${previousNearWord}`)
      } else {
        nearSeen.set(nearKey, canonical)
      }

      if (deck.id !== 'bidding') {
        const previousDeck = playableWordOwners.get(canonical)
        if (previousDeck && previousDeck !== deckId) {
          errors.push(`${deckId} duplicates ${canonical} from ${previousDeck}`)
        } else {
          playableWordOwners.set(canonical, deckId)
        }

        const previousNearOwner = playableNearDuplicateOwners.get(nearKey)
        if (previousNearOwner && previousNearOwner.word !== canonical) {
          errors.push(`${deckId} near-duplicates ${canonical} from ${previousNearOwner.deckId} (${previousNearOwner.word})`)
        } else {
          playableNearDuplicateOwners.set(nearKey, { deckId, word: canonical })
        }
      }
    })
  })

  return errors
}
