import type { WordDeckId } from './gameMode'
import { pickWords, type WordPools } from './wordSelection'

export { pickWords } from './wordSelection'

export type Difficulty = 'green' | 'yellow' | 'red'
export type WordTag =
  | 'campus'
  | 'party'
  | 'sports'
  | 'movies'
  | 'music'
  | 'internet'
  | 'food'
  | 'relationships'
  | 'travel'
  | 'jobs'
  | 'slang'
  | 'history'
  | 'science'
  | 'games'
  | 'brands'
  | 'places'
  | 'phrases'

export interface WordSource {
  id: string
  name: string
  url: string
  licenseNote: string
  importedAt: string
  transform: string
}

export interface WordDeck {
  id: WordDeckId
  difficulty: Difficulty | 'money'
  tags: WordTag[]
  sourceIds: string[]
  words: string[]
}

export interface WordDeckSummary {
  id: WordDeckId
  difficulty: Difficulty | 'money'
  count: number
  tags: WordTag[]
  sourceIds: string[]
}

export interface WordBankSummary {
  totalPlayableWords: number
  deckCounts: Record<WordDeckId, number>
  sourceCount: number
  decks: WordDeckSummary[]
}

// Green = A1/A2 CEFR + curated easy words — everyday concrete nouns, common actions
// Yellow = B1 CEFR + curated medium words — events, places, activities, characters
// Red = B2 CEFR + curated hard words — abstract concepts, less common vocabulary
// Words sourced from CEFRJ vocabulary profile (CC-BY) + hand-curated additions

export const WORD_BANK_SOURCES: WordSource[] = [
  {
    id: 'cefr-j-olp',
    name: 'Open Language Profiles English datasets from CEFR-J',
    url: 'https://github.com/openlanguageprofiles/olp-en-cefrj',
    licenseNote: 'CEFR-J vocabulary profile is permitted for research and commercial use with citation per repository terms.',
    importedAt: '2026-05-19',
    transform: 'Uppercased, deduped, grouped A1/A2 as green, B1 as yellow, B2 as red, then manually filtered for party play.',
  },
  {
    id: 'curated-party',
    name: 'Curated party-game additions',
    url: 'local:lib/words.ts',
    licenseNote: 'Original short list of common party-game words and phrases authored for this repo.',
    importedAt: '2026-05-19',
    transform: 'Uppercased, deduped, manually tiered by college-party playability.',
  },
]

export const greenWords: string[] = [
  'ABILITY', 'ACCEPT', 'ACCEPTABLE', 'ACCIDENT', 'ACCORDION', 'ACCOUNT', 'ACHIEVE', 'ACORN', 'ACTION', 'ACTIVITY',
  'ACTOR', 'ADDITION', 'ADDITIONAL', 'ADDRESS', 'ADJECTIVE', 'ADJUST', 'ADMIRE', 'ADMIT', 'ADULT', 'ADVANCED',
  'ADVANTAGE', 'ADVENTURE', 'ADVERTISEMENT', 'ADVERTISING', 'ADVICE', 'ADVISE', 'AFFAIR', 'AFRAID', 'AFTERNOON', 'AGED',
  'AGENCY', 'AGENT', 'AGREE', 'AIRPORT', 'AISLE', 'ALARM', 'ALBUM', 'ALIVE', 'ALLOW', 'ALMOND',
  'ALONE', 'ALRIGHT', 'AMBITION', 'AMBULANCE', 'AMUSED', 'AMUSEMENT', 'ANCESTOR', 'ANCHOR', 'ANCHOVY', 'ANCIENT',
  'ANGEL', 'ANGRY', 'ANIMAL', 'ANKLE', 'ANNIVERSARY', 'ANNOY', 'ANSWER', 'ANT', 'ANXIOUS', 'APARTMENT',
  'APPEAR', 'APPEARANCE', 'APPLE', 'APPOINTMENT', 'APPRECIATE', 'APPROPRIATE', 'APRIL', 'APRON', 'ARCHITECTURE', 'AREA',
  'ARGUE', 'ARGUMENT', 'ARM', 'ARMADILLO', 'ARMCHAIR', 'ARMED', 'ARRIVE', 'ARTICLE', 'ARTIFICIAL', 'ASLEEP',
  'ASSISTANT', 'ASSOCIATION', 'ASTRONAUT', 'ATHLETE', 'ATOM', 'ATTACK', 'ATTEMPT', 'ATTENTION', 'ATTITUDE', 'ATTRACTIVE',
  'AUDIENCE', 'AUDIO', 'AUGUST', 'AUNT', 'AUTHOR', 'AUTOMATIC', 'AUTUMN', 'AVERAGE', 'AVOCADO', 'AVOID',
  'AWAKE', 'AWARD', 'AWFUL', 'AXE', 'BABOON', 'BABY', 'BACK', 'BACKGROUND', 'BACKPACK', 'BACON',
  'BADMINTON', 'BAG', 'BAGEL', 'BAKE', 'BALCONY', 'BALL', 'BALLOON', 'BAMBOO', 'BANANA', 'BAND',
  'BANJO', 'BANK', 'BANKING', 'BARBECUE', 'BARBER', 'BARGAIN', 'BARN', 'BASE', 'BASEBALL', 'BASIC',
  'BASKET', 'BASKETBALL', 'BATCH', 'BATH', 'BATHROOM', 'BATTERY', 'BAY', 'BEACH', 'BEAN', 'BEANS',
  'BEAR', 'BEAUTIFUL', 'BEAUTY', 'BEAVER', 'BECOME', 'BEDROOM', 'BEE', 'BEEF', 'BEER', 'BEG',
  'BEGIN', 'BEGINNER', 'BEGINNING', 'BEING', 'BELIEVE', 'BELL', 'BELLY', 'BELONG', 'BELT', 'BENCH',
  'BEND', 'BETTER', 'BICYCLE', 'BIKE', 'BILL', 'BIRD', 'BIRTH', 'BIRTHDAY', 'BISCUIT', 'BISON',
  'BITE', 'BLACK', 'BLACKBOARD', 'BLAME', 'BLANK', 'BLANKET', 'BLIMP', 'BLOCK', 'BLONDE', 'BLOOD',
  'BLOOM', 'BLOW', 'BLUE', 'BLUEBERRY', 'BLUEBIRD', 'BOARD', 'BOAT', 'BOBCAT', 'BODY', 'BOIL',
  'BOILED', 'BONE', 'BONUS', 'BOOK', 'BOOKCASE', 'BOOKSHELF', 'BOOKSHOP', 'BOOKSTORE', 'BORED', 'BORING',
  'BOSS', 'BOTHER', 'BOTTLE', 'BOTTOM', 'BOULDER', 'BOWL', 'BOX', 'BOYFRIEND', 'BRA', 'BRAIN',
  'BRAINSTORM', 'BRAKE', 'BRANCH', 'BRAND', 'BRAVE', 'BREAD', 'BREAK', 'BREAKFAST', 'BREATHE', 'BREEZE',
  'BRIDE', 'BRIDGE', 'BRIGHT', 'BRILLIANT', 'BRING', 'BROCCOLI', 'BROKEN', 'BROOK', 'BROOM', 'BROTHER',
  'BROWN', 'BROWNIE', 'BRUSH', 'BUCKET', 'BUDGET', 'BUILD', 'BUILDING', 'BULB', 'BURGER', 'BURN',
  'BURRITO', 'BURY', 'BUS', 'BUSH', 'BUSINESS', 'BUSINESSMAN', 'BUSINESSWOMAN', 'BUTTER', 'BUTTERFLY', 'BUTTON',
  'BYE', 'CABINET', 'CACTUS', 'CAFETERIA', 'CAKE', 'CALENDAR', 'CALL', 'CAMEL', 'CAMERA', 'CAMP',
  'CAMPING', 'CAMPUS', 'CANARY', 'CANDLE', 'CANDY', 'CANOE', 'CANTEEN', 'CANVAS', 'CANYON', 'CAPITAL',
  'CAPPUCCINO', 'CAPTAIN', 'CAR', 'CARAMEL', 'CARD', 'CARE', 'CAREFUL', 'CARROT', 'CARRY', 'CARTOON',
  'CASE', 'CASH', 'CASHEW', 'CASSETTE', 'CASTLE', 'CAT', 'CATCH', 'CATERPILLAR', 'CAULIFLOWER', 'CAUSE',
  'CAVE', 'CELEBRATE', 'CELEBRATION', 'CELERY', 'CELLO', 'CENT', 'CENTURY', 'CEREAL', 'CERTAIN', 'CHAIN',
  'CHAIR', 'CHAIRMAN', 'CHALLENGE', 'CHAMPAGNE', 'CHAMPIONSHIP', 'CHANCE', 'CHANGE', 'CHAPTER', 'CHARACTER', 'CHAT',
  'CHEAP', 'CHECK', 'CHEEK', 'CHEER', 'CHEESE', 'CHEETAH', 'CHEF', 'CHEMICAL', 'CHEQUE', 'CHERRY',
  'CHESS', 'CHEST', 'CHICKEN', 'CHILD', 'CHILDHOOD', 'CHIMPANZEE', 'CHIN', 'CHIPMUNK', 'CHIRP', 'CHISEL',
  'CHOCOLATE', 'CHOICE', 'CHOOSE', 'CHOPSTICKS', 'CHURCH', 'CIGARETTE', 'CINEMA', 'CINNAMON', 'CIRCLE', 'CITIZEN',
  'CITY', 'CLAIM', 'CLAM', 'CLASS', 'CLASSIC', 'CLASSMATE', 'CLASSROOM', 'CLEAN', 'CLEANER', 'CLEAR',
  'CLERK', 'CLEVER', 'CLICK', 'CLIFF', 'CLIMB', 'CLIMBING', 'CLOCK', 'CLONE', 'CLOSE', 'CLOSED',
  'CLOTH', 'CLOTHES', 'CLOUD', 'CLOUDY', 'CLOWN', 'CLUB', 'CLUE', 'COACH', 'COAST', 'COASTER',
  'COAT', 'COBRA', 'COCONUT', 'CODE', 'COFFEE', 'COIN', 'COKE', 'COLA', 'COLLECT', 'COLLECTION',
  'COLLEGE', 'COLUMN', 'COMB', 'COME', 'COMFORTABLE', 'COMIC', 'COMMITMENT', 'COMMITTEE', 'COMMON', 'COMMUNICATE',
  'COMMUNICATION', 'COMPANY', 'COMPARATIVE', 'COMPARE', 'COMPASS', 'COMPETITION', 'COMPLAIN', 'COMPLAINT', 'COMPLETE', 'COMPOSER',
  'COMPUTER', 'CONCENTRATE', 'CONCERN', 'CONCERT', 'CONDITION', 'CONFIDENT', 'CONFUSE', 'CONFUSED', 'CONSEQUENCE', 'CONSIDER',
  'CONSIST', 'CONTACT', 'CONTAINER', 'CONTEST', 'CONTEXT', 'CONTINENT', 'CONTINUE', 'CONTRAST', 'CONTROL', 'CONVENIENCE',
  'CONVENIENT', 'CONVERSATION', 'COOK', 'COOKER', 'COOKIE', 'COOKING', 'COOLER', 'COP', 'COPY', 'CORAL',
  'CORN', 'CORNER', 'CORRECT', 'COST', 'COUCH', 'COUNT', 'COUNTRY', 'COUNTRYSIDE', 'COUPLE', 'COURSE',
  'COURT', 'COUSIN', 'COVER', 'COW', 'COWBOY', 'CRAB', 'CRACKER', 'CRATER', 'CRAYON', 'CRAZY',
  'CREAM', 'CREATE', 'CREATIVE', 'CREATIVITY', 'CREATURE', 'CREDIT', 'CRICKET', 'CRIME', 'CRISP', 'CROCODILE',
  'CROISSANT', 'CROSS', 'CROW', 'CROWBAR', 'CROWD', 'CROWDED', 'CROWN', 'CRUISE', 'CUCUMBER', 'CULTURE',
  'CUP', 'CUPBOARD', 'CURRY', 'CURSE', 'CURTAIN', 'CUSHION', 'CUSTARD', 'CUSTOM', 'CUSTOMER', 'CUTE',
  'CYCLING', 'DAD', 'DADDY', 'DAILY', 'DAISY', 'DANCE', 'DANCER', 'DANCING', 'DANGER', 'DANGEROUS',
  'DATE', 'DAUGHTER', 'DAYLIGHT', 'DEAL', 'DEATH', 'DEBATE', 'DECEMBER', 'DECIDE', 'DEER', 'DELAY',
  'DELICIOUS', 'DENTIST', 'DEPEND', 'DESCRIBE', 'DESCRIPTION', 'DESERT', 'DESIGN', 'DESK', 'DESSERT', 'DESTROY',
  'DETAIL', 'DEVELOP', 'DEVELOPED', 'DIAMOND', 'DIARY', 'DICTIONARY', 'DIET', 'DIFFERENCE', 'DIFFERENT', 'DIFFICULT',
  'DIFFICULTY', 'DINGO', 'DINNER', 'DINOSAUR', 'DIRECT', 'DIRECTION', 'DIRECTOR', 'DIRTY', 'DISADVANTAGE', 'DISAGREE',
  'DISAPPEAR', 'DISAPPOINTED', 'DISAPPOINTING', 'DISCO', 'DISCOVER', 'DISCUSS', 'DISCUSSION', 'DISH', 'DISHONEST', 'DISLIKE',
  'DISPLAY', 'DIVIDE', 'DIZZY', 'DOG', 'DOLL', 'DOLLAR', 'DOLPHIN', 'DONKEY', 'DONUT', 'DOOR',
  'DOUBLE', 'DOUBT', 'DOWNLOAD', 'DRAGONFLY', 'DRAMA', 'DRAW', 'DRAWER', 'DRAWING', 'DREAM', 'DRESS',
  'DRESSED', 'DRILL', 'DRINK', 'DRIVE', 'DRIVER', 'DROP', 'DRUG', 'DRUGSTORE', 'DRUM', 'DUCK',
  'DUE', 'DUMPLING', 'DUNE', 'DUST', 'DVD', 'EAGLE', 'EAR', 'EARLY', 'EARN', 'EARRING',
  'EARTH', 'EARTHQUAKE', 'EASEL', 'EAST', 'EASY', 'EDITOR', 'EDUCATION', 'EDUCATIONAL', 'EFFECT', 'EFFORT',
  'EGG', 'ELDERLY', 'ELECTRIC', 'ELEMENTARY', 'ELEPHANT', 'ELEVATOR', 'EMAIL', 'EMBARRASSING', 'EMERGENCY', 'EMPTY',
  'ENCOURAGE', 'ENDANGERED', 'ENDING', 'ENERGETIC', 'ENGINEER', 'ENJOY', 'ENORMOUS', 'ENTERTAINMENT', 'ENTRANCE', 'ENVELOPE',
  'ENVY', 'EPISODE', 'ERASER', 'ERROR', 'ESCALATOR', 'ESCAPE', 'ESPRESSO', 'ESSAY', 'ESTABLISH', 'EURO',
  'EVENING', 'EVENT', 'EVERYDAY', 'EVIDENCE', 'EXAM', 'EXAMPLE', 'EXCELLENT', 'EXCHANGE', 'EXCITED', 'EXCITING',
  'EXCUSE', 'EXERCISE', 'EXHIBITION', 'EXIST', 'EXPECT', 'EXPENSIVE', 'EXPERIENCE', 'EXPERT', 'EXPLAIN', 'EXPLANATION',
  'EXPLORE', 'EXPRESS', 'EXPRESSION', 'EXTRA', 'EYE', 'FACE', 'FACT', 'FACTORY', 'FAIL', 'FAIRY',
  'FALAFEL', 'FALL', 'FALSE', 'FAMILIAR', 'FAMILY', 'FAMOUS', 'FANCY', 'FANTASTIC', 'FARE', 'FARM',
  'FARMER', 'FASCINATING', 'FASHION', 'FAT', 'FATHER', 'FAULT', 'FEAR', 'FEATHER', 'FEATURE', 'FEBRUARY',
  'FEE', 'FEED', 'FEEL', 'FEELING', 'FEMALE', 'FENCE', 'FERN', 'FERRET', 'FERRY', 'FESTIVAL',
  'FEVER', 'FICTION', 'FIELD', 'FIGHT', 'FIGHTER', 'FIGURE', 'FILE', 'FILL', 'FILM', 'FINAL',
  'FIND', 'FINISH', 'FIRE', 'FIREFLY', 'FIRST', 'FISH', 'FISHERMAN', 'FISHING', 'FLAG', 'FLAMINGO',
  'FLEA', 'FLIGHT', 'FLOAT', 'FLOOD', 'FLOOR', 'FLOUR', 'FLOWER', 'FLUTE', 'FOCUS', 'FOG',
  'FOGGY', 'FOLDER', 'FOLLOW', 'FOLLOWING', 'FOOD', 'FOOL', 'FOOTBALL', 'FOOTBALLER', 'FORBID', 'FORCE',
  'FOREIGN', 'FOREIGNER', 'FOREST', 'FORGET', 'FORK', 'FORM', 'FORTUNE', 'FOX', 'FRAME', 'FRANK',
  'FREEDOM', 'FREEZE', 'FRESH', 'FRIDAY', 'FRIDGE', 'FRIED', 'FRIEND', 'FRIENDSHIP', 'FRIGHTEN', 'FRIGHTENED',
  'FRIGHTENING', 'FROG', 'FRONT', 'FRUIT', 'FRY', 'FUDGE', 'FUN', 'FUNCTION', 'FUNNEL', 'FUNNY',
  'FURNITURE', 'FURTHER', 'FUTURE', 'GALLERY', 'GAME', 'GARAGE', 'GARBAGE', 'GARDEN', 'GARLIC', 'GAS',
  'GATE', 'GATHER', 'GECKO', 'GENDER', 'GENERATION', 'GENTLE', 'GEYSER', 'GHOST', 'GIFT', 'GINGER',
  'GIRAFFE', 'GIRL', 'GIRLFRIEND', 'GIVE', 'GIVEN', 'GLACIER', 'GLAD', 'GLASS', 'GLASSES', 'GLOBE',
  'GLOVE', 'GOAL', 'GOAT', 'GOLD', 'GOLDEN', 'GOLDFISH', 'GOLF', 'GONDOLA', 'GORILLA', 'GOVERNMENT',
  'GRACE', 'GRADE', 'GRADUATE', 'GRAMMAR', 'GRANDCHILD', 'GRANDDAD', 'GRANDDAUGHTER', 'GRANDFATHER', 'GRANDMA', 'GRANDMOTHER',
  'GRANDPA', 'GRANDPARENT', 'GRANDSON', 'GRANNY', 'GRANOLA', 'GRAPE', 'GRASS', 'GRATEFUL', 'GREAT', 'GREEDY',
  'GREEN', 'GREET', 'GRILLED', 'GROUND', 'GROUP', 'GROW', 'GUARD', 'GUESS', 'GUEST', 'GUIDEBOOK',
  'GUITAR', 'GUN', 'GUY', 'HABIT', 'HAIR', 'HAIRCUT', 'HALF', 'HALL', 'HAM', 'HAMBURGER',
  'HAMMER', 'HAMSTER', 'HAND', 'HANDBAG', 'HANDICAPPED', 'HANDLE', 'HANDSOME', 'HAPPEN', 'HAPPINESS', 'HAPPY',
  'HARM', 'HARMFUL', 'HARMONICA', 'HARMONY', 'HARP', 'HARVEST', 'HAT', 'HATE', 'HAWK', 'HEAD',
  'HEADACHE', 'HEADPHONE', 'HEADPHONES', 'HEADTEACHER', 'HEALTH', 'HEALTHY', 'HEAR', 'HEART', 'HEAT', 'HEATING',
  'HEAVY', 'HEDGEHOG', 'HELICOPTER', 'HELLO', 'HELP', 'HELPFUL', 'HERO', 'HIDE', 'HIGHWAY', 'HIKE',
  'HIKING', 'HILL', 'HIPPO', 'HISTORY', 'HOBBY', 'HOCKEY', 'HOLD', 'HOLE', 'HOLIDAY', 'HOME',
  'HOMETOWN', 'HOMEWORK', 'HONEY', 'HOPE', 'HORROR', 'HORSE', 'HOSPITAL', 'HOST', 'HOT', 'HOTEL',
  'HOUR', 'HOUSE', 'HUG', 'HUMAN', 'HUMMINGBIRD', 'HUMMUS', 'HUNGRY', 'HUNTER', 'HURRY', 'HURT',
  'HUSBAND', 'ICE', 'ICEBERG', 'IDEA', 'IDEAL', 'ILL', 'ILLEGAL', 'IMAGE', 'IMAGINATION', 'IMAGINE',
  'IMPACT', 'IMPATIENT', 'IMPORTANCE', 'IMPORTANT', 'IMPOSSIBLE', 'IMPRESS', 'IMPROVE', 'INCH', 'INCLUDE', 'INCREASE',
  'INDEPENDENCE', 'INDICATE', 'INDOOR', 'INEXPENSIVE', 'INFLUENCE', 'INFORMATION', 'INNER', 'INSECT', 'INSPIRATION', 'INSTANT',
  'INSTRUMENT', 'INTELLIGENCE', 'INTELLIGENT', 'INTEREST', 'INTERESTED', 'INTERESTING', 'INTERNATIONAL', 'INTERVIEW', 'INTERVIEWER', 'INTRODUCE',
  'INVADE', 'INVENT', 'INVENTION', 'INVITE', 'ISLAND', 'ISSUE', 'ITEM', 'JACKET', 'JAGUAR', 'JAM',
  'JANUARY', 'JAR', 'JEANS', 'JELLY', 'JELLYFISH', 'JET', 'JOB', 'JOIN', 'JOKE', 'JOURNEY',
  'JOY', 'JUDGE', 'JUICE', 'JULY', 'JUMP', 'JUNE', 'JUNGLE', 'JUNIOR', 'JUNK', 'KANGAROO',
  'KAYAK', 'KAZOO', 'KEBAB', 'KEEP', 'KELP', 'KETCHUP', 'KETTLE', 'KEY', 'KEYBOARD', 'KICK',
  'KID', 'KILL', 'KILLER', 'KILO', 'KIND', 'KINDLY', 'KING', 'KINGDOM', 'KISS', 'KIT',
  'KITCHEN', 'KITE', 'KNEE', 'KNIFE', 'KNOCK', 'KNOW', 'KNOWLEDGE', 'KOALA', 'LACK', 'LADDER',
  'LADLE', 'LADY', 'LADYBUG', 'LAKE', 'LAMP', 'LAND', 'LANDSCAPE', 'LANE', 'LANGUAGE', 'LANTERN',
  'LARGE', 'LATEST', 'LATTE', 'LAUGH', 'LAW', 'LAWYER', 'LAZINESS', 'LAZY', 'LEAD', 'LEADER',
  'LEAF', 'LEARN', 'LEARNER', 'LEATHER', 'LEAVE', 'LEG', 'LEISURE', 'LEMON', 'LEMONADE', 'LEMUR',
  'LEND', 'LESSON', 'LETTER', 'LETTUCE', 'LEVEL', 'LIBERTY', 'LIBRARY', 'LIFE', 'LIFESTYLE', 'LIGHTNING',
  'LIKELY', 'LILY', 'LINE', 'LION', 'LIP', 'LIST', 'LISTEN', 'LITTLE', 'LIVELY', 'LIVING',
  'LLAMA', 'LOAD', 'LOBSTER', 'LOCAL', 'LOCK', 'LOGICAL', 'LOLLIPOP', 'LONELY', 'LOOK', 'LOOSE',
  'LOSE', 'LOST', 'LOT', 'LOVE', 'LOVELY', 'LOVER', 'LOW', 'LUCK', 'LUCKY', 'LUNCH',
  'LUNCHBOX', 'LUNCHTIME', 'LYNX', 'LYRIC', 'MACHINE', 'MAD', 'MAGAZINE', 'MAGIC', 'MAIL', 'MAJOR',
  'MAKE', 'MAKER', 'MALE', 'MALL', 'MALLET', 'MAN', 'MANAGE', 'MANAGER', 'MANGO', 'MANNER',
  'MAP', 'MARCH', 'MARK', 'MARKET', 'MARRIED', 'MARRY', 'MARSH', 'MATCH', 'MATERIAL', 'MATTER',
  'MAX', 'MAY', 'MEADOW', 'MEAL', 'MEAN', 'MEANING', 'MEAT', 'MEDAL', 'MEDICAL', 'MEDICINE',
  'MEET', 'MEETING', 'MELON', 'MEMBER', 'MEMORY', 'MENTION', 'MENU', 'MESSAGE', 'METAL', 'METHOD',
  'MIDDAY', 'MIDDLE', 'MIDNIGHT', 'MILITARY', 'MILK', 'MILKSHAKE', 'MIND', 'MINT', 'MINUTE', 'MIRROR',
  'MISS', 'MISSING', 'MISTAKE', 'MOBILE', 'MODEL', 'MODERN', 'MOM', 'MOMENT', 'MONDAY', 'MONEY',
  'MONKEY', 'MONTH', 'MOOD', 'MOON', 'MOOSE', 'MORNING', 'MORTAR', 'MOSQUE', 'MOSS', 'MOTHER',
  'MOTORCYCLE', 'MOTORWAY', 'MOUNTAIN', 'MOUSE', 'MOUTH', 'MOVE', 'MOVIE', 'MUD', 'MUFFIN', 'MUG',
  'MULE', 'MUM', 'MURDER', 'MUSEUM', 'MUSHROOM', 'MUSIC', 'MUSICAL', 'MUSICIAN', 'MUSTARD', 'MYSTERIOUS',
  'MYSTERY', 'NAAN', 'NACHO', 'NAIL', 'NAME', 'NAPKIN', 'NATION', 'NATIONAL', 'NATIONALITY', 'NATIVE',
  'NATURAL', 'NATURE', 'NECESSARY', 'NECK', 'NEED', 'NEGATIVE', 'NERVOUS', 'NET', 'NEWS', 'NEWSPAPER',
  'NICE', 'NIGHT', 'NOISE', 'NOISY', 'NOODLE', 'NOON', 'NORMAL', 'NORTH', 'NOSE', 'NOTE',
  'NOTEBOOK', 'NOTICE', 'NOUN', 'NOVEL', 'NOVEMBER', 'NUMBER', 'NURSE', 'OAK', 'OCCUPATION', 'OCEAN',
  'OCTOBER', 'OCTOPUS', 'OFFER', 'OFFICE', 'OFFICER', 'OFFICIAL', 'OIL', 'OLIVE', 'OLYMPIC', 'OLYMPICS',
  'ONION', 'ONLINE', 'ONLY', 'OPERA', 'OPERATE', 'OPINION', 'OPPORTUNITY', 'OPPOSE', 'OPPOSITE', 'ORANGE',
  'ORDER', 'ORIGINAL', 'ORPHAN', 'OTTER', 'OVEN', 'OVERWEIGHT', 'OWL', 'OWNER', 'PACIFIC', 'PACK',
  'PADDLE', 'PAGE', 'PAINT', 'PAINTBRUSH', 'PAINTER', 'PAINTING', 'PAIR', 'PAL', 'PALACE', 'PALETTE',
  'PALM', 'PAN', 'PANCAKE', 'PANDA', 'PANIC', 'PANTHER', 'PANTS', 'PAPER', 'PARAGRAPH', 'PARAKEET',
  'PARDON', 'PARENT', 'PARK', 'PARROT', 'PART', 'PARTNER', 'PARTY', 'PASS', 'PASSAGE', 'PASSENGER',
  'PASTA', 'PATH', 'PATIENT', 'PEA', 'PEACE', 'PEACEFUL', 'PEACH', 'PEACOCK', 'PEANUT', 'PEAR',
  'PEAS', 'PEBBLE', 'PELICAN', 'PEN', 'PENCE', 'PENCIL', 'PENGUIN', 'PEOPLE', 'PEPPER', 'PERFECT',
  'PERFORM', 'PERFORMANCE', 'PERFUME', 'PERIOD', 'PERMISSION', 'PERSON', 'PERSONAL', 'PERSONALITY', 'PESTLE', 'PET',
  'PETAL', 'PETROL', 'PHONE', 'PHOTO', 'PHOTOGRAPH', 'PHOTOGRAPHER', 'PHOTOGRAPHY', 'PHYSICAL', 'PIANO', 'PICK',
  'PICKLE', 'PICNIC', 'PICTURE', 'PIE', 'PIECE', 'PIG', 'PIGEON', 'PILE', 'PILGRIM', 'PILL',
  'PILLOW', 'PILOT', 'PINE', 'PINEAPPLE', 'PINK', 'PISTACHIO', 'PITY', 'PIZZA', 'PLACE', 'PLAN',
  'PLANE', 'PLANET', 'PLANT', 'PLASTIC', 'PLATE', 'PLAY', 'PLAYER', 'PLAYFUL', 'PLAYGROUND', 'PLEASANT',
  'PLEASED', 'PLEASING', 'PLEASURE', 'PLENTY', 'PLIERS', 'PLUM', 'PLURAL', 'POCKET', 'POEM', 'POINT',
  'POLICE', 'POLICEMAN', 'POLICEWOMAN', 'POLITICAL', 'POLLUTE', 'POLLUTION', 'POND', 'POOL', 'POP', 'POPCORN',
  'POPULAR', 'POPULATION', 'PORCUPINE', 'PORTRAIT', 'POSITION', 'POSSIBLE', 'POST', 'POSTER', 'POT', 'POTATO',
  'POUR', 'POWER', 'POWERFUL', 'PRACTICE', 'PRAY', 'PRECISE', 'PREDICT', 'PREDICTION', 'PREFER', 'PREPARE',
  'PRESENT', 'PRESSURE', 'PRETEND', 'PRETTY', 'PRETZEL', 'PREVENT', 'PRICE', 'PRIDE', 'PRINCE', 'PRINCESS',
  'PRINCIPAL', 'PRINT', 'PRINTER', 'PRIVATE', 'PRO', 'PROBLEM', 'PRODUCE', 'PRODUCT', 'PRODUCTION', 'PROFESSIONAL',
  'PROGRESSIVE', 'PROMISE', 'PRONOUNCE', 'PRONUNCIATION', 'PROPER', 'PROVIDE', 'PSYCHOLOGIST', 'PUBLIC', 'PUBLISH', 'PUDDLE',
  'PULL', 'PUMPKIN', 'PUNCTUATION', 'PURPLE', 'PURPOSE', 'PURSUE', 'PUSH', 'PYTHON', 'QUALITY', 'QUARTER',
  'QUEEN', 'QUESTION', 'QUICK', 'QUIET', 'QUIT', 'QUIZ', 'RABBIT', 'RACCOON', 'RACKET', 'RADIO',
  'RAFT', 'RAIN', 'RAINBOW', 'RAINCOAT', 'RAINY', 'RAISE', 'RAISIN', 'RAM', 'RAMEN', 'RANGE',
  'RAP', 'RASPBERRY', 'RAT', 'RATE', 'RATING', 'RAVEN', 'RAW', 'RAY', 'REACH', 'READ',
  'READER', 'READING', 'READY', 'REASON', 'RECEIPT', 'RECEIVE', 'RECENT', 'RECEPTIONIST', 'RECORD', 'RECYCLE',
  'RED', 'REEF', 'REFER', 'REFLECT', 'REGRET', 'REGULAR', 'RELAX', 'RELAXED', 'RELEASE', 'REMAIN',
  'REMEMBER', 'REMIND', 'REMOTE', 'RENT', 'REPAIR', 'REPEAT', 'REPLACE', 'REPLY', 'REPORT', 'REPORTER',
  'REPRESENT', 'REQUEST', 'RESEARCH', 'RESPONSE', 'RESTAURANT', 'RESULT', 'RETIRE', 'RETIRED', 'RETURN', 'REUNION',
  'REVEAL', 'REVIEW', 'RHYTHM', 'RIBBON', 'RICE', 'RICKSHAW', 'RIDE', 'RING', 'RIVER', 'ROAD',
  'ROAST', 'ROB', 'ROBBERY', 'ROBIN', 'ROCK', 'ROCKET', 'ROLE', 'ROLL', 'ROMANCE', 'ROMANTIC',
  'ROOF', 'ROOM', 'ROOSTER', 'ROOT', 'ROPE', 'ROSE', 'ROUNDABOUT', 'ROW', 'ROWBOAT', 'ROYAL',
  'RUG', 'RUGBY', 'RUIN', 'RULE', 'RULER', 'RUNNER', 'RUNNING', 'RUSH', 'SAD', 'SAILING',
  'SAILOR', 'SAKE', 'SALAD', 'SALE', 'SALT', 'SAMPLE', 'SAND', 'SANDWICH', 'SANDY', 'SARDINE',
  'SATISFY', 'SATURDAY', 'SAUCE', 'SAUSAGE', 'SAVE', 'SAW', 'SCALE', 'SCARF', 'SCENE', 'SCENERY',
  'SCHEDULE', 'SCHOOL', 'SCHOOLCHILD', 'SCHOOLWORK', 'SCIENCE', 'SCIENTIFIC', 'SCIENTIST', 'SCISSORS', 'SCOOTER', 'SCREAM',
  'SCREEN', 'SCREW', 'SCREWDRIVER', 'SCRIPT', 'SEA', 'SEAFOOD', 'SEAHORSE', 'SEAL', 'SEARCH', 'SEASIDE',
  'SEAT', 'SEAWEED', 'SECOND', 'SECRET', 'SECTION', 'SEED', 'SEEK', 'SEEM', 'SELF', 'SELL',
  'SEMESTER', 'SEND', 'SENIOR', 'SENSE', 'SENTENCE', 'SEPARATE', 'SEPTEMBER', 'SERVE', 'SEW', 'SHADE',
  'SHADOW', 'SHAKE', 'SHAMPOO', 'SHAPE', 'SHARE', 'SHARK', 'SHEEP', 'SHELF', 'SHELL', 'SHINE',
  'SHIP', 'SHIRT', 'SHOE', 'SHOOT', 'SHOP', 'SHOPPING', 'SHORE', 'SHORT', 'SHOT', 'SHOULDER',
  'SHOUT', 'SHOVEL', 'SHOW', 'SHOWER', 'SHRIMP', 'SHUT', 'SHY', 'SICK', 'SIDE', 'SIEVE',
  'SIGHT', 'SIGHTSEEING', 'SIGN', 'SIGNIFICANT', 'SILENCE', 'SILLY', 'SILVER', 'SIMILAR', 'SIMPLE', 'SING',
  'SINGER', 'SINGING', 'SINGLE', 'SINGULAR', 'SINK', 'SIR', 'SISTER', 'SITE', 'SITUATION', 'SIZE',
  'SKATE', 'SKATEBOARD', 'SKATEBOARDING', 'SKATING', 'SKI', 'SKIING', 'SKILL', 'SKIRT', 'SKUNK', 'SKY',
  'SLED', 'SLEEP', 'SLEEPLESS', 'SLEEPY', 'SLICE', 'SLIDE', 'SLIM', 'SMALL', 'SMART',
  'SMELL', 'SMILE', 'SMITH', 'SMOKE', 'SMOKING', 'SMOOTH', 'SMOOTHIE', 'SNACK', 'SNAIL', 'SNAKE',
  'SNOW', 'SNOWBOARDING', 'SNOWY', 'SOAP', 'SOCCER', 'SOCIAL', 'SOCIETY', 'SOCK', 'SODA', 'SOFA',
  'SOFTWARE', 'SOLDIER', 'SOLUTION', 'SOLVE', 'SON', 'SONG', 'SORRY', 'SOUND', 'SOUP', 'SOURCE',
  'SOUTH', 'SPACE', 'SPACESHIP', 'SPAGHETTI', 'SPARROW', 'SPATULA', 'SPEAK', 'SPEAKER', 'SPECIAL', 'SPECIFIC',
  'SPEECH', 'SPEED', 'SPELL', 'SPEND', 'SPILL', 'SPINACH', 'SPLASH', 'SPLIT', 'SPOON', 'SPORT',
  'SPOT', 'SPREAD', 'SPRING', 'SPY', 'SQUARE', 'SQUIRREL', 'STADIUM', 'STAFF', 'STAGE', 'STAIR',
  'STAMP', 'STAND', 'STAPLER', 'STAR', 'START', 'STATE', 'STATEMENT', 'STATION', 'STATUE', 'STAY',
  'STEAK', 'STEAL', 'STEP', 'STILL', 'STOMACH', 'STOMACHACHE', 'STONE', 'STOP', 'STORE', 'STORM',
  'STORY', 'STOVE', 'STRAIGHT', 'STRANGE', 'STRANGER', 'STRATEGY', 'STRAW', 'STRAWBERRY', 'STREET', 'STRENGTH',
  'STRICT', 'STRIKE', 'STRING', 'STRONG', 'STRUCTURE', 'STUDENT', 'STUDY', 'STUFF', 'STYLE', 'SUBJECT',
  'SUBMARINE', 'SUBWAY', 'SUCCEED', 'SUCCESS', 'SUCCESSFUL', 'SUDDEN', 'SUGAR', 'SUGGEST', 'SUGGESTION', 'SUIT',
  'SUITABLE', 'SUITCASE', 'SUM', 'SUMMARY', 'SUMMER', 'SUN', 'SUNDAY', 'SUNFLOWER', 'SUNGLASSES', 'SUNLIGHT',
  'SUNNY', 'SUNSHINE', 'SUPER', 'SUPERLATIVE', 'SUPERMARKET', 'SUPERSTAR', 'SUPPER', 'SUPPORT', 'SURF', 'SURFING',
  'SURNAME', 'SURPRISE', 'SURPRISED', 'SURPRISING', 'SURVEY', 'SURVIVE', 'SUSHI', 'SWALLOW', 'SWAMP', 'SWAN',
  'SWEAT', 'SWEATER', 'SWEET', 'SWEETHEART', 'SWIM', 'SWIMMING', 'SWIMSUIT', 'SYMBOL', 'SYMPHONY', 'SYRUP',
  'SYSTEM', 'TABLE', 'TABLESPOON', 'TACO', 'TAKE', 'TALENT', 'TALK', 'TAMBOURINE', 'TAP', 'TAPE',
  'TARGET', 'TASK', 'TAXI', 'TEA', 'TEACH', 'TEACHER', 'TEAM', 'TEAR', 'TECHNOLOGY', 'TEENAGE',
  'TEENAGER', 'TELEPHONE', 'TELEVISION', 'TELL', 'TEMPERATURE', 'TEMPLE', 'TENNIS', 'TERRIBLE', 'TERRIFY', 'TERRORIST',
  'TEST', 'TEXT', 'TEXTBOOK', 'THANK', 'THANKS', 'THERMOS', 'THIEF', 'THING', 'THINK', 'THIRD',
  'THIRSTY', 'THORN', 'THOUGHT', 'THROW', 'THUNDER', 'THUNDERSTORM', 'THURSDAY', 'TICKET', 'TIDE', 'TIDY',
  'TIGER', 'TIGHT', 'TIGHTS', 'TIME', 'TIMETABLE', 'TIP', 'TIRED', 'TITLE', 'TOAST', 'TOASTER',
  'TODAY', 'TOE', 'TOFFEE', 'TOILET', 'TOMATO', 'TOMORROW', 'TONE', 'TONIGHT', 'TOOL', 'TOOTH',
  'TOOTHACHE', 'TOOTHBRUSH', 'TOPIC', 'TOUCAN', 'TOUCH', 'TOUR', 'TOURIST', 'TOWEL', 'TOWER', 'TOWN',
  'TOY', 'TRACK', 'TRACTOR', 'TRADE', 'TRADITION', 'TRADITIONAL', 'TRAFFIC', 'TRAIN', 'TRAINING', 'TRAM',
  'TRAP', 'TRAVEL', 'TRAY', 'TREASURE', 'TREE', 'TRICK', 'TRIP', 'TROPHY', 'TROUBLE', 'TROUSERS',
  'TRUCK', 'TRUMPET', 'TRUST', 'TRUTH', 'TUBE', 'TUESDAY', 'TULIP', 'TUNE', 'TURKEY', 'TURN',
  'TWIG', 'TYPE', 'UGLY', 'UKULELE', 'UMBRELLA', 'UNCERTAIN', 'UNCLE', 'UNCOMFORTABLE', 'UNDERLINE', 'UNDERSTAND',
  'UNDERWATER', 'UNEASY', 'UNFAIR', 'UNFORGETTABLE', 'UNHAPPY', 'UNHEALTHY', 'UNIFORM', 'UNIMPORTANT', 'UNIT', 'UNIVERSITY',
  'UNKNOWN', 'UNLIKE', 'UNNECESSARY', 'UNPLEASANT', 'UNUSUAL', 'UPSET', 'USEFUL', 'USUAL', 'VACATION', 'VALLEY',
  'VALUE', 'VANILLA', 'VASE', 'VEGETABLE', 'VERB', 'VIDEO', 'VIEW', 'VILLAGE', 'VINE', 'VIOLENT',
  'VIOLIN', 'VIPER', 'VISIT', 'VISITOR', 'VOCABULARY', 'VOICE', 'VOLCANO', 'VOLLEYBALL', 'VOTE', 'WAFER',
  'WAFFLE', 'WAIT', 'WAITER', 'WAITRESS', 'WAKE', 'WALK', 'WALKING', 'WALL', 'WALLET', 'WALNUT',
  'WALRUS', 'WANDER', 'WANT', 'WAR', 'WASH', 'WATCH', 'WATER', 'WATERFALL', 'WATERMELON', 'WAVE',
  'WEALTH', 'WEAR', 'WEASEL', 'WEATHER', 'WEB', 'WEBSITE', 'WEDDING', 'WEDNESDAY', 'WEEK', 'WEEKDAY',
  'WEEKEND', 'WEEKLY', 'WEEP', 'WEIGH', 'WEIGHT', 'WELCOME', 'WELL', 'WEST', 'WET', 'WHALE',
  'WHEEL', 'WHEELCHAIR', 'WHISK', 'WHITE', 'WHOLE', 'WIFE', 'WIND', 'WINDOW', 'WINDY', 'WINE',
  'WINNER', 'WINTER', 'WISDOM', 'WISH', 'WOLF', 'WOMAN', 'WONDER', 'WONDERFUL', 'WOOD', 'WOODEN',
  'WOODPECKER', 'WOOL', 'WORD', 'WORK', 'WORKER', 'WORLD', 'WORRIED', 'WORRY', 'WORSE', 'WORST',
  'WRENCH', 'WRITE', 'WRITER', 'WRITING', 'WRONG', 'XYLOPHONE', 'YARD', 'YEAR', 'YELLOW', 'YOGURT',
  'YOUNG', 'YOUTH', 'ZEBRA', 'ZONE', 'ZOO',
]

export const yellowWords: string[] = [
  'ABANDON', 'ABLE', 'ABNORMAL', 'ABORIGINE', 'ABOVE', 'ABSENCE', 'ABSENT', 'ABSOLUTE', 'ABSORB', 'ABSTRACT',
  'ABUNDANCE', 'ABUNDANT', 'ACADEMIC', 'ACADEMY', 'ACCENT', 'ACCEPTANCE', 'ACCESS', 'ACCESSIBLE', 'ACCESSORY', 'ACCIDENTAL',
  'ACCOMPANY', 'ACCOMPLISH', 'ACCOUNTANT', 'ACCURACY', 'ACCURATE', 'ACCUSE', 'ACCUSTOM', 'ACHE', 'ACHIEVEMENT', 'ACKNOWLEDGE',
  'ACQUAINTANCE', 'ACQUIRE', 'ACROBAT', 'ACTIVE', 'ACTRESS', 'ADAPT', 'ADDRESSEE', 'ADMINISTRATION', 'ADMIRATION', 'ADMISSION',
  'ADOPT', 'ADORABLE', 'ADVANCE', 'ADVERB', 'ADVERBIAL', 'ADVERT', 'ADVERTISE', 'AEROBICS', 'AFFECT', 'AFFECTION',
  'AFFORD', 'AGENDA', 'AGGRESSIVE', 'AGREEMENT', 'AGRICULTURAL', 'AGRICULTURE', 'AID', 'AIRLINE', 'ALCOHOL', 'ALCOHOLIC',
  'ALIEN', 'ALIKE', 'ALLERGIC', 'ALLEY', 'ALLOWANCE', 'ALPHABET', 'ALTERNATIVE', 'AMAZED', 'AMAZING', 'AMBITIOUS',
  'AMOUNT', 'AMUSING', 'ANALYSIS', 'ANGER', 'ANGLE', 'ANIMATED', 'ANIMATION', 'ANNOUNCE', 'ANNOUNCEMENT', 'ANNOYANCE',
  'ANNOYED', 'ANNUAL', 'ANTI', 'ANTIQUE', 'ANTONYM', 'ANXIETY', 'APE', 'APOLOGY', 'APPARENT', 'APPEAL',
  'APPETITE', 'APPLAUD', 'APPLAUSE', 'APPLICATION', 'APPOINT', 'APPRECIATION', 'APPROACH', 'APPROVAL', 'APPROVE', 'AQUARIUM',
  'ARCADE', 'ARCHAEOLOGIST', 'ARCHERY', 'ARCHITECT', 'ARENA', 'ARISE', 'ARITHMETIC', 'ARMY', 'ARRANGE', 'ARRANGEMENT',
  'ARREST', 'ARRIVAL', 'ARROW', 'ARTIST', 'ARTISTIC', 'ASHAMED', 'ASPECT', 'ASPIRIN', 'ASSIGN', 'ASSIGNMENT',
  'ASSIST', 'ASSISTANCE', 'ASSOCIATE', 'ASSUME', 'ASTEROID', 'ASTRONOMER', 'ATHLETIC', 'ATLANTIC', 'ATMOSPHERE', 'ATOMIC',
  'ATTACH', 'ATTACHMENT', 'ATTAIN', 'ATTEND', 'ATTIC', 'ATTRACT', 'ATTRACTION', 'AUCTION', 'AUCTIONEER', 'AUTHORITY',
  'AUXILIARY', 'AVAILABLE', 'AVALANCHE', 'AVENUE', 'AWARE', 'AWARENESS', 'AWESOME', 'AWKWARD', 'BABYSIT', 'BABYSITTER',
  'BACKACHE', 'BACKPACKER', 'BACKPACKING', 'BAGGAGE', 'BAKER', 'BAKERY', 'BAKING', 'BALANCE', 'BALD', 'BANDAGE',
  'BANDIT', 'BANG', 'BANQUET', 'BARBERSHOP', 'BARK', 'BARMAN', 'BARREL', 'BARTENDER', 'BASEMENT', 'BASIN',
  'BASIS', 'BATHE', 'BATTLE', 'BEARD', 'BEAST', 'BEAT', 'BEDSIDE', 'BEHALF', 'BEHAVE', 'BELIEF',
  'BELOVED', 'BENEFIT', 'BENT', 'BILINGUAL', 'BIN', 'BIOCHEMISTRY', 'BIOGRAPHY', 'BIOLOGY', 'BISHOP', 'BITTER',
  'BLACKSMITH', 'BLEED', 'BLEND', 'BLESS', 'BLESSING', 'BLIND', 'BLIZZARD', 'BLOG', 'BLOGGER', 'BLUSH',
  'BOAST', 'BOMB', 'BOND', 'BOOKING', 'BOOM', 'BOOT', 'BORDER', 'BORE', 'BOREDOM', 'BOUNCE',
  'BOUND', 'BOWLING', 'BOXING', 'BRACELET', 'BRAINSTORMING', 'BRASS', 'BREAKTHROUGH', 'BREAST', 'BREATH', 'BREATHLESS',
  'BREED', 'BREEDING', 'BRICK', 'BRIEF', 'BROAD', 'BROADCAST', 'BRONZE', 'BROTHERHOOD', 'BUBBLE', 'BUDDY',
  'BUILDER', 'BULL', 'BULLET', 'BULLETIN', 'BUMP', 'BUNCH', 'BURDEN', 'BUREAU', 'BURGLAR', 'BURNING',
  'BURST', 'BUST', 'BUTCHER', 'BUYER', 'CABBAGE', 'CABIN', 'CAGE', 'CALCULATE', 'CALCULATION', 'CALCULATOR',
  'CALF', 'CALLER', 'CALMNESS', 'CAMPSITE', 'CANAL', 'CANCEL', 'CANCER', 'CANNED', 'CAPABLE', 'CAPACITY',
  'CAPSULE', 'CAPTURE', 'CAREER', 'CARELESS', 'CARELESSNESS', 'CARNIVAL', 'CARPENTER', 'CARPET', 'CARRIAGE', 'CARTON',
  'CASHIER', 'CASHPOINT', 'CASUAL', 'CATEGORY', 'CATHEDRAL', 'CATTLE', 'CAUTION', 'CAUTIOUS', 'CELEBRITY', 'CELL',
  'CEMETERY', 'CENTAUR', 'CENTRAL', 'CEREMONY', 'CERTAINTY', 'CHALLENGING', 'CHAMPION', 'CHANNEL', 'CHAOS', 'CHAPEL',
  'CHARACTERISTIC', 'CHARGE', 'CHARIOT', 'CHARITY', 'CHARM', 'CHASE', 'CHECKOUT', 'CHEERFUL', 'CHEERLEADING', 'CHEMIST',
  'CHEMISTRY', 'CHERISH', 'CHIEF', 'CHOIR', 'CHOKE', 'CHRISTIAN', 'CHRONOLOGICAL', 'CHUCKLE', 'CIRCULAR', 'CIRCUS',
  'CITIZENSHIP', 'CIVIL', 'CLASSICAL', 'CLASSIFY', 'CLIMATE', 'CLIMBER', 'CLINIC', 'CLIP', 'COAL', 'COASTAL',
  'COD', 'COFFIN', 'COLLAPSE', 'COLLAR', 'COLUMNIST', 'COMBINATION', 'COMBINE', 'COMEDIAN', 'COMEDY', 'COMET',
  'COMFORT', 'COMMA', 'COMMAND', 'COMMENT', 'COMMERCIAL', 'COMMIT', 'COMPANION', 'COMPARISON', 'COMPETE', 'COMPETITIVE',
  'COMPETITOR', 'COMPLEMENT', 'COMPLEX', 'COMPLICATE', 'COMPLICATED', 'COMPLIMENT', 'COMPOSE', 'COMPOSITION', 'COMPOUND', 'COMPROMISE',
  'CONCENTRATION', 'CONCEPT', 'CONCERNED', 'CONCLUDE', 'CONCLUSION', 'CONDUCT', 'CONFERENCE', 'CONFIDENCE', 'CONFIRM', 'CONFIRMATION',
  'CONFLICT', 'CONFUSING', 'CONFUSION', 'CONGRATULATE', 'CONNECT', 'CONQUER', 'CONSCIOUS', 'CONSERVATION', 'CONSERVATIVE', 'CONSIDERABLE',
  'CONSIDERATION', 'CONSONANT', 'CONSTITUTE', 'CONSTITUTION', 'CONSTRUCT', 'CONSTRUCTION', 'CONSUME', 'CONSUMER', 'CONSUMPTION', 'CONTAIN',
  'CONTENT', 'CONTINUAL', 'CONTINUOUS', 'CONTRARY', 'CONTRIBUTE', 'CONTRIBUTION', 'CONTROVERSIAL', 'CONVEY', 'CONVINCE', 'COPYRIGHT',
  'CORRECTION', 'COTTAGE', 'COTTON', 'COUGH', 'COUNCIL', 'COUNTER', 'COUNTLESS', 'COUNTY', 'COURAGE', 'COURAGEOUS',
  'COURGETTE', 'COURIER', 'COURTROOM', 'CRAFT', 'CRASH', 'CREATOR', 'CRIMINAL', 'CRISIS', 'CRITIC', 'CRITICAL',
  'CROP', 'CROSSING', 'CROSSROADS', 'CRUEL', 'CRUSH', 'CULTIVATE', 'CULTURAL', 'CURE', 'CURIOSITY', 'CURIOUS',
  'CURLING', 'CURLY', 'CURRENCY', 'CURRENT', 'CURRICULUM', 'CURVE', 'CUSTOMS', 'CYBORG', 'CYCLE', 'CYCLONE',
  'DAMAGE', 'DAMAGED', 'DAMP', 'DARE', 'DARKNESS', 'DATING', 'DAZE', 'DAZZLE', 'DEADLINE', 'DEADLY',
  'DEAF', 'DEALER', 'DEBRIS', 'DEBT', 'DECISION', 'DECLARATION', 'DECLARE', 'DECLINE', 'DECREASE', 'DEDICATE',
  'DEED', 'DEFEAT', 'DEFEND', 'DEFENDER', 'DEFICIENCY', 'DEFINE', 'DEFINITE', 'DEFINITION', 'DELETE', 'DELICATE',
  'DELIGHT', 'DELIGHTED', 'DELIGHTFUL', 'DELIVER', 'DELIVERY', 'DEMAND', 'DEMOCRACY', 'DEMOCRATIC', 'DEMONSTRATE', 'DEMONSTRATION',
  'DENY', 'DEPART', 'DEPARTMENT', 'DEPARTURE', 'DEPENDENT', 'DEPOSIT', 'DEPRESSED', 'DEPRESSING', 'DEPRESSION', 'DEPRIVE',
  'DEPTH', 'DERIVE', 'DESERVE', 'DESIGNER', 'DESIRE', 'DESPAIR', 'DESPERATE', 'DESTINATION', 'DESTRUCTION', 'DESTRUCTIVE',
  'DETECTIVE', 'DETERMINATION', 'DETERMINE', 'DEVASTATE', 'DEVASTATING', 'DEVELOPMENT', 'DEVICE', 'DEVOTION', 'DIAGRAM', 'DIAL',
  'DIAMETER', 'DIAPER', 'DIFFER', 'DIGITAL', 'DILIGENCE', 'DILIGENT', 'DIOXIDE', 'DIRT', 'DISABILITY', 'DISABLE',
  'DISABLED', 'DISAGREEMENT', 'DISAPPOINT', 'DISAPPOINTMENT', 'DISASTER', 'DISASTROUS', 'DISCOMFORT', 'DISCOUNT', 'DISCOURAGE', 'DISCOVERY',
  'DISCRIMINATION', 'DISEASE', 'DISGUSTING', 'DISHWASHER', 'DISSOLVE', 'DISTANCE', 'DISTANT', 'DISTINCTION', 'DISTINGUISH', 'DISTRIBUTE',
  'DISTRIBUTION', 'DISTRICT', 'DISTURB', 'DISTURBANCE', 'DIVE', 'DIVER', 'DIVERSE', 'DIVINE', 'DIVING', 'DIVORCED',
  'DOC', 'DOCTOR', 'DOCUMENT', 'DOCUMENTARY', 'DOWNSTAIRS', 'DOWNWARD', 'DOZE', 'DOZEN', 'DRAG', 'DRAGON',
  'DRAMATIC', 'DROUGHT', 'DROWN', 'DUDE', 'DUMP', 'DUNGEON', 'DUSTBIN', 'DUSTY', 'DUTY',
  'DUVET', 'DYNASTY', 'EAGER', 'EAGERNESS', 'EARACHE', 'EARNEST', 'EASTERN', 'ECLIPSE', 'ECO', 'ECOLOGICAL',
  'ECOLOGY', 'ECONOMIC', 'ECONOMICS', 'ECONOMY', 'ECOSYSTEM', 'ECSTASY', 'EDGE', 'EDITION', 'EDUCATE', 'EFFECTIVE',
  'EFFICIENCY', 'EFFICIENT', 'ELBOW', 'ELECTION', 'ELECTRICAL', 'ELECTRICIAN', 'ELECTRICITY', 'ELECTRON', 'ELECTRONIC', 'ELEMENT',
  'ELIMINATE', 'EMBARRASS', 'EMBARRASSED', 'EMBARRASSMENT', 'EMERGE', 'EMOTION', 'EMOTIONAL', 'EMPEROR', 'EMPHASIS', 'EMPIRE',
  'EMPLOYMENT', 'ENABLE', 'ENCLOSE', 'ENCOUNTER', 'ENCOURAGEMENT', 'ENCOURAGING', 'ENDANGER', 'ENDLESS', 'ENDURE', 'ENEMY',
  'ENGAGE', 'ENGAGED', 'ENGINE', 'ENGINEERING', 'ENGLISHMAN', 'ENJOYABLE', 'ENJOYMENT', 'ENRICH', 'ENSURE', 'ENTERTAIN',
  'ENTERTAINER', 'ENTHUSIASM', 'ENTHUSIAST', 'ENTHUSIASTIC', 'ENTIRE', 'ENTRY', 'ENVIRONMENTAL', 'ENVIRONMENTALIST', 'EQUAL', 'EQUALITY',
  'EQUIPMENT', 'ERA', 'ESSENCE', 'ESSENTIAL', 'ESTABLISHMENT', 'ESTIMATE', 'ETERNAL', 'ETERNITY', 'EVEN', 'EVIDENT',
  'EXACT', 'EXAMINATION', 'EXAMINE', 'EXAMINER', 'EXCELLENCE', 'EXCESS', 'EXCITEMENT', 'EXCLUSIVE', 'EXHAUSTED', 'EXISTENCE',
  'EXIT', 'EXPAND', 'EXPEDITION', 'EXPENSE', 'EXPERIENCED', 'EXPERIMENT', 'EXPLORATION', 'EXPLORER', 'EXPLOSION', 'EXPOSE',
  'EXTEND', 'EXTENT', 'EXTINCT', 'EXTINCTION', 'EXTRAORDINARY', 'EXTREME', 'EYESIGHT', 'FACILITY', 'FADE', 'FAILURE',
  'FAINT', 'FAITHFUL', 'FAKE', 'FALLEN', 'FANTASY', 'FARAWAY', 'FAREWELL', 'FARMING', 'FARMLAND', 'FASCINATE',
  'FASHIONABLE', 'FASTEN', 'FEAST', 'FELLOW', 'FENCING', 'FESTIVE', 'FETCH', 'FIFTH', 'FILLING', 'FILTER',
  'FINANCE', 'FINANCIAL', 'FINDING', 'FINGER', 'FIREFIGHTER', 'FIREWORK', 'FIRM', 'FITNESS', 'FLASH', 'FLOCK',
  'FLOW', 'FLU', 'FLUENT', 'FLUNK', 'FOLD', 'FOLK', 'FOND', 'FONDNESS', 'FOOLISH', 'FOOT',
  'FORBIDDEN', 'FORECAST', 'FOREHEAD', 'FORGIVE', 'FORMAL', 'FORMAT', 'FORMER', 'FORMULA', 'FORTNIGHT', 'FORTRESS',
  'FORTUNATE', 'FOUNDATION', 'FOUNTAIN', 'FRAGMENT', 'FREEZER', 'FREEZING', 'FREQUENCY', 'FREQUENT', 'FRESHMAN', 'FRIENDLINESS',
  'FRIGHT', 'FROST', 'FROZEN', 'FRUSTRATED', 'FRUSTRATION', 'FUEL', 'FUND', 'FUNDRAISER', 'FUNERAL', 'FUR',
  'FURNISH', 'FUSS', 'GAIN', 'GALA', 'GALL', 'GALLON', 'GAMING', 'GAP', 'GARDENING', 'GARMENT',
  'GENE', 'GENERAL', 'GENERATE', 'GENEROUS', 'GENETIC', 'GENETICS', 'GENTLEMAN', 'GEOGRAPHICAL', 'GEOGRAPHY',
  'GEOLOGY', 'GESTURE', 'GIANT', 'GIFTED', 'GIGGLE', 'GLADIATOR', 'GLANCE', 'GLIDE', 'GLIMPSE', 'GLINT',
  'GLOBAL', 'GLORIOUS', 'GLORY', 'GOALKEEPER', 'GOBLIN', 'GODDESS', 'GOLFER', 'GOODS', 'GORGEOUS', 'GOSSIP',
  'GOVERN', 'GOVERNOR', 'GOWN', 'GRAB', 'GRACEFUL', 'GRADUATION', 'GRANT', 'GRAPH', 'GRAPHIC', 'GRAPHICS',
  'GRATITUDE', 'GRAVE', 'GRAVITY', 'GRAVY', 'GREENHOUSE', 'GREETING', 'GRIFFIN', 'GRILL', 'GROOM', 'GROUPING',
  'GROWTH', 'GUARANTEE', 'GUIDANCE', 'GUIDE', 'GUILT', 'GUILTY', 'GUITARIST', 'GYM', 'GYMNASTICS', 'HABITAT',
  'HAIL', 'HAIRDRESSER', 'HAIRDRYER', 'HANDBALL', 'HANDKERCHIEF', 'HANDSHAKE', 'HANDWRITING', 'HANDY', 'HANG', 'HANGING',
  'HARBOR', 'HARDSHIP', 'HARNESS', 'HASTY', 'HATCH', 'HATRED', 'HAUNT', 'HAVEN', 'HAZARD', 'HEADLINE',
  'HEAL', 'HEALING', 'HEARING', 'HEARTED', 'HEARTY', 'HEATER', 'HEATWAVE', 'HEAVEN', 'HEAVENLY', 'HEEL',
  'HEIGHT', 'HELMET', 'HELPLESS', 'HERD', 'HESITATE', 'HIDDEN', 'HIGHLIGHT', 'HIP', 'HIRE', 'HISTORIAN',
  'HISTORIC', 'HISTORICAL', 'HIV', 'HOLY', 'HOMELESS', 'HONEST', 'HONESTY', 'HONEYMOON', 'HOPEFUL', 'HOPELESS',
  'HORIZON', 'HORN', 'HORRIBLE', 'HORRIFY', 'HOSTEL', 'HOUSEHOLD', 'HOUSEWORK', 'HUMANITY', 'HUMID', 'HUMOROUS',
  'HUNGER', 'HUNT', 'HUNTING', 'HURRICANE', 'HUT', 'IDENTITY', 'IDIOM', 'IDOL', 'IGLOO', 'IGNORE',
  'ILLNESS', 'ILLUMINATE', 'IMAGINARY', 'IMITATE', 'IMMEDIATE', 'IMMIGRATE', 'IMMIGRATION', 'IMPAIR', 'IMPRESSION', 'IMPRESSIVE',
  'IMPROPER', 'IMPROVEMENT', 'INCIDENT', 'INCOME', 'INCONVENIENT', 'INCORRECT', 'INCREDIBLE', 'INDEPENDENT', 'INDIRECT', 'INDIVIDUAL',
  'INDUSTRIAL', 'INDUSTRY', 'INEVITABLE', 'INFANT', 'INFECTION', 'INFINITIVE', 'INFORM', 'INFORMATIVE', 'INGREDIENT', 'INHABITANT',
  'INHALE', 'INITIAL', 'INJECT', 'INJURY', 'INK', 'INNERMOST', 'INNOCENT', 'INNOVATOR', 'INSANE', 'INSCRIBE',
  'INSCRIPTION', 'INSIGHT', 'INSIST', 'INSPECTION', 'INSPIRE', 'INSTANCE', 'INSTITUTE', 'INSTRUCTION', 'INSTRUCTOR', 'INSURANCE',
  'INTEND', 'INTENSE', 'INTENSIVE', 'INTENTION', 'INTERACT', 'INTERACTION', 'INTERMEDIATE', 'INTERMISSION', 'INTERNAL', 'INTERRUPT',
  'INTERVAL', 'INTERVIEWEE', 'INTRODUCTION', 'INVASION', 'INVENTOR', 'INVEST', 'INVESTIGATION', 'INVITATION', 'INVOLVE', 'INVOLVED',
  'IRON', 'IRONING', 'IRREGULAR', 'IRRITATE', 'ISLE', 'ISOLATION', 'IVORY', 'JADE', 'JAZZ', 'JEALOUS',
  'JESTER', 'JEWEL', 'JOG', 'JOGGING', 'JOINT', 'JOURNAL', 'JOURNALIST', 'JUG', 'JUICY', 'JUMPER',
  'JUSTICE', 'KARMA', 'KAYAKING', 'KILLING', 'KINDNESS', 'KITTEN', 'KNIGHT', 'KNIT', 'KNITTING', 'KRAKEN',
  'LAB', 'LABORATORY', 'LACROSSE', 'LAMB', 'LANDLORD', 'LANDSLIDE', 'LASTING', 'LATECOMER', 'LAUGHTER', 'LAUNCH',
  'LAWFUL', 'LAYER', 'LEADERSHIP', 'LEADING', 'LEAGUE', 'LEAN', 'LEAP', 'LECTURE', 'LEGAL', 'LENGTH',
  'LESSEN', 'LIAR', 'LIBERATE', 'LIBERATION', 'LIBRARIAN', 'LIFEGUARD', 'LIFELONG', 'LIFT', 'LIGHTER', 'LIGHTHOUSE',
  'LIKENESS', 'LIMIT', 'LIMITATION', 'LIMITED', 'LIMP', 'LINK', 'LIQUID', 'LITERARY', 'LITERATURE', 'LIVER',
  'LOAF', 'LOCATE', 'LOCATION', 'LOCKSMITH', 'LODGE', 'LOG', 'LOGIC', 'LOGO', 'LORRY', 'LOSS',
  'LOTTERY', 'LOUDSPEAKER', 'LOYAL', 'LOYALTY', 'LUGGAGE', 'LUNG', 'LUXURY', 'MAGICAL', 'MAGICIAN', 'MAGNIFICENT',
  'MAILBOX', 'MAIN', 'MAINTAIN', 'MAINTENANCE', 'MAJORITY', 'MANAGEMENT', 'MANKIND', 'MANSION', 'MAPLE', 'MARATHON',
  'MARBLE', 'MARINE', 'MARKED', 'MARRIAGE', 'MASH', 'MASS', 'MASSIVE', 'MATHEMATICIAN', 'MATHEMATICS', 'MAXIMUM',
  'MAYOR', 'MEANINGFUL', 'MEASURE', 'MEASUREMENT', 'MECHANIC', 'MECHANICAL', 'MEDITATE', 'MEDITATION', 'MEDITERRANEAN', 'MEDIUM',
  'MELT', 'MEMBERSHIP', 'MEMORABLE', 'MEND', 'MENTAL', 'MERCHANT', 'MERE', 'MERMAID', 'MESS', 'MESSY',
  'MILE', 'MINERAL', 'MINIMUM', 'MINOR', 'MINORITY', 'MIRACLE', 'MISCHIEF', 'MISERABLE', 'MISERY', 'MISLEAD',
  'MISSION', 'MIST', 'MISTY', 'MISUNDERSTANDING', 'MODEM', 'MODERATE', 'MODIFY', 'MOISTURE', 'MOLECULE', 'MONITOR',
  'MONK', 'MONSOON', 'MONSTER', 'MONTHLY', 'MONUMENT', 'MORAL', 'MOSQUITO', 'MOTHERLAND', 'MOTIONLESS', 'MOTIVATE',
  'MOTIVATION', 'MOTIVE', 'MOTOR', 'MOTTO', 'MOUNT', 'MOUNTAINTOP', 'MOURN', 'MOVEMENT', 'MURDERER', 'MUSCLE',
  'MUTUAL', 'MYTH', 'NAP', 'NARRATE', 'NARRATIVE', 'NARROW', 'NASTY', 'NATIONALIST', 'NAUGHTY',
  'NEARBY', 'NECKLACE', 'NECTAR', 'NEEDLE', 'NEGOTIATE', 'NEGOTIATION', 'NEPHEW', 'NERVOUSNESS', 'NESS', 'NETWORK',
  'NEUTRAL', 'NEWBORN', 'NEWCOMER', 'NICKNAME', 'NIECE', 'NIGHTLIFE', 'NINJA', 'NOD', 'NONSENSE', 'NORTHEAST',
  'NORTHEASTERN', 'NORTHERN', 'NORTHWEST', 'NORTHWESTERN', 'NOTICEABLE', 'NOTICEBOARD', 'NOTION', 'NOTORIOUS', 'NOVELIST', 'NUCLEAR',
  'NUCLEUS', 'NUMEROUS', 'NUTRIENT', 'NUTRITION', 'NUTRITIOUS', 'OBJECT', 'OBJECTION', 'OBJECTIVE', 'OBSERVATION', 'OBSERVATORY',
  'OBSERVE', 'OBSTACLE', 'OBTAIN', 'OBVIOUS', 'OCCASION', 'OCCASIONAL', 'OCCUPY', 'OCCUR', 'OFFENSIVE', 'OILY',
  'ONSTAGE', 'OPENING', 'OPERATION', 'OPPOSITION', 'OPPRESS', 'OPPRESSION', 'OPTION', 'ORAL', 'ORBIT', 'ORCHESTRA',
  'ORDERLY', 'ORDINARY', 'ORGAN', 'ORGANIC', 'ORGANISM', 'ORIGIN', 'OUTDOOR', 'OUTER', 'OUTLAW', 'OUTLINE',
  'OUTSTANDING', 'OUTWARD', 'OUTWEIGH', 'OVERCOME', 'OVERJOYED', 'OVERNIGHT', 'OVERWHELM', 'OVERWHELMING', 'OVERWORK', 'OWE',
  'OWING', 'OXYGEN', 'PACE', 'PACKAGE', 'PACKING', 'PAID', 'PAIN', 'PAINFUL', 'PARACHUTE', 'PARADE',
  'PARADISE', 'PARCEL', 'PARENTAL', 'PARKING', 'PARTIAL', 'PARTICIPANT', 'PARTICIPATE', 'PARTICIPLE', 'PASSION', 'PASSIVE',
  'PASSPORT', 'PASSWORD', 'PATIENCE', 'PATROL', 'PATTERN', 'PAUSE', 'PECULIAR', 'PENNILESS', 'PENNY', 'PERFORMER',
  'PERMANENT', 'PERMIT', 'PERSUADE', 'PERSUASIVE', 'PHANTOM', 'PHARMACY', 'PHENOMENON', 'PHILOSOPHER', 'PHILOSOPHY', 'PHOENIX',
  'PHOTOCOPY', 'PHRASE', 'PHYSICS', 'PIER', 'PIETY', 'PIN', 'PINBALL', 'PIPE', 'PIRATE', 'PIT',
  'PLAIN', 'PLATFORM', 'PLEASE', 'PLUG', 'PLUMBER', 'POET', 'POETRY', 'POISON', 'POISONOUS', 'POLE',
  'POLICY', 'POLITICIAN', 'POLITICS', 'POLLUTANT', 'POLO', 'PORK', 'PORT', 'POSITIVE', 'POSSESS', 'POSSESSION',
  'POSSESSIVE', 'POSSIBILITY', 'POSTCARD', 'POSTMAN', 'POTENTIAL', 'POTTERY', 'POUND', 'POVERTY', 'POWDER', 'PRACTICAL',
  'PRAISE', 'PRAYER', 'PRECIOUS', 'PREFERENCE', 'PREFIX', 'PREGNANT', 'PREJUDICE', 'PREMIERE', 'PREPARATION', 'PREPARED',
  'PREPOSITION', 'PRESCHOOL', 'PRESCRIPTION', 'PRESENCE', 'PRESENTATION', 'PRESERVATION', 'PRESERVE', 'PRESIDENT', 'PRESS', 'PREVIOUS',
  'PRIEST', 'PRIMITIVE', 'PRINCIPLE', 'PRISON', 'PRISONER', 'PRIVACY', 'PRIZE', 'PROBABILITY', 'PROCEED', 'PROCESS',
  'PROCLAIM', 'PROCRASTINATION', 'PRODUCER', 'PRODUCTIVE', 'PROFESSION', 'PROFESSOR', 'PROGRESS', 'PROHIBITION', 'PROM', 'PROMINENT',
  'PROMOTE', 'PROMOTION', 'PRONOUN', 'PROOF', 'PROPERTY', 'PROPORTION', 'PROPOSAL', 'PROPOSE', 'PROSPERITY', 'PROSPEROUS',
  'PROTECT', 'PROTECTION', 'PROTECTIVE', 'PROTEST', 'PROUD', 'PROVE', 'PROVERB', 'PSYCHOLOGICAL', 'PUB', 'PUBLISHER',
  'PULLOVER', 'PUMP', 'PUNISH', 'PUNISHMENT', 'PUPIL', 'PUPPY', 'PURIFY', 'PURSE', 'PUZZLE', 'QUAKE',
  'QUALIFIED', 'QUALIFY', 'QUANTITY', 'QUESTIONNAIRE', 'QUEUE', 'RACE', 'RACIAL', 'RADIATION', 'RAGE', 'RAIL',
  'RAILROAD', 'RAILWAY', 'RAINFALL', 'RAINFOREST', 'RALLY', 'RANGER', 'RANK', 'RAPID', 'RARE', 'RATION',
  'RATIONAL', 'RAZOR', 'REACT', 'REALISTIC', 'REALITY', 'REARRANGE', 'REASONABLE', 'REBUILD', 'RECALL', 'RECEPTION',
  'RECITAL', 'RECITE', 'RECLAIM', 'RECOMMEND', 'RECORDING', 'RECOVER', 'RECOVERY', 'RECYCLED', 'RECYCLING', 'REDUCE',
  'REDUCTION', 'REFEREE', 'REFLECTION', 'REFRESHMENTS', 'REFRIGERATOR', 'REFUND', 'REFUSAL', 'REFUSE', 'REGAIN', 'REGARD',
  'REGION', 'REGIONAL', 'REGISTER', 'REGISTRATION', 'REGULATION', 'REHEARSAL', 'REJECT', 'RELATE', 'RELATION', 'RELATIONSHIP',
  'RELATIVE', 'RELAXING', 'RELIABLE', 'RELIGION', 'RELIGIOUS', 'RELY', 'REMAINDER', 'REMARK', 'REMARKABLE', 'REMEDY',
  'REMEMBRANCE', 'REMOVE', 'RENEW', 'REPAY', 'REPRESENTATIVE', 'REPRODUCE', 'REPUBLIC', 'REPUTATION', 'REQUIRE', 'REQUIREMENT',
  'RESCUE', 'RESEARCHER', 'RESEMBLE', 'RESERVATION', 'RESERVE', 'RESIDENT', 'RESIDENTIAL', 'RESIST', 'RESOLVE', 'RESORT',
  'RESOURCE', 'RESPECT', 'RESPECTABLE', 'RESPOND', 'RESPONSIBILITY', 'RESPONSIBLE', 'REST', 'RESTORE', 'RESTRICT', 'RETAIL',
  'RETAIN', 'RETELL', 'RETROSPECT', 'REUNIFICATION', 'REUNIFY', 'REVISE', 'REVISION', 'REWARD', 'REWRITE', 'RID',
  'RIDDLE', 'RIDICULOUS', 'RIPE', 'RISE', 'RISK', 'ROADSIDE', 'ROBOT', 'ROLLING', 'ROOFTOP', 'ROTTEN',
  'ROUGH', 'ROUND', 'ROUTINE', 'ROWING', 'RUBBER', 'RUBBISH', 'RUNAWAY', 'RUNWAY', 'SACRED', 'SADNESS',
  'SAFARI', 'SAFEGUARD', 'SAFETY', 'SALESMAN', 'SALMON', 'SALON', 'SAMURAI', 'SANDAL', 'SANDSTORM', 'SATELLITE',
  'SATISFACTION', 'SATISFIED', 'SAUCEPAN', 'SAUCER', 'SCAN', 'SCARE', 'SCARED', 'SCARY', 'SCATTER', 'SCENIC',
  'SCHOLAR', 'SCHOLARSHIP', 'SCHOOLMATE', 'SCHOOLTEACHER', 'SCOLD', 'SCOPE', 'SCORE', 'SCRATCH', 'SCULPTURE', 'SEASON',
  'SEAWATER', 'SECRETARY', 'SECURE', 'SECURITY', 'SEIZE', 'SELECT', 'SELECTION', 'SELFISH', 'SENSATION', 'SEPARATION',
  'SEQUENCE', 'SERIES', 'SERIOUS', 'SERVER', 'SERVICE', 'SESSION', 'SETTING', 'SETTLE', 'SETTLEMENT', 'SETTLER',
  'SEVERE', 'SEX', 'SHADOWY', 'SHALLOW', 'SHAME', 'SHAMEFUL', 'SHARP', 'SHAVE', 'SHEER', 'SHEET',
  'SHELTER', 'SHERIFF', 'SHIFT', 'SHINY', 'SHIVER', 'SHOCKED', 'SHOCKING', 'SHOPPER', 'SHORTAGE', 'SICKNESS',
  'SIDEWALK', 'SIGH', 'SIGNAL', 'SIGNATURE', 'SIGNIFICANCE', 'SIGNPOST', 'SILENT', 'SILK', 'SIMILARITY', 'SIMPLIFY',
  'SKELETON', 'SKIN', 'SKYSCRAPER', 'SLEEPOVER', 'SLEEVE', 'SLIGHT', 'SLIP', 'SLOGAN', 'SLOPE',
  'SLOT', 'SMOKER', 'SNEEZE', 'SNOWBOARD', 'SNOWSTORM', 'SOIL', 'SOLID', 'SOOTHE', 'SOPHOMORE', 'SORCERER',
  'SORE', 'SORROW', 'SORT', 'SOUL', 'SOUR', 'SOUTHEAST', 'SOUTHERN', 'SOUTHWEST', 'SOUVENIR', 'SPA',
  'SPARKLE', 'SPECIALIST', 'SPECTACULAR', 'SPECTATOR', 'SPELLING', 'SPHERE', 'SPHINX', 'SPICE', 'SPICY', 'SPIDER',
  'SPIRAL', 'SPIRIT', 'SPIRITUAL', 'SPOIL', 'SPONGE', 'SPONSOR', 'SPORTS', 'SPORTSMANSHIP', 'STABLE', 'STALL',
  'STANDARD', 'STARE', 'STATUS', 'STEADY', 'STEAM', 'STEEL', 'STEEP', 'STEM', 'STICK', 'STICKER',
  'STICKY', 'STIR', 'STORAGE', 'STORMY', 'STORYTELLER', 'STRAIN', 'STRATEGIC', 'STREAM', 'STRENGTHEN', 'STRESS',
  'STRESSED', 'STRESSFUL', 'STRETCH', 'STRICKEN', 'STRIP', 'STRIPE', 'STRUGGLE', 'STUBBORN', 'STUCK', 'STUDIO',
  'STUFFED', 'STUMBLE', 'STUN', 'STUNNING', 'STUPID', 'STYLISH', 'SUBCONSCIOUS', 'SUBSTANTIAL', 'SUBSTITUTE', 'SUFFER',
  'SUFFICIENT', 'SUFFIX', 'SUICIDE', 'SUMMIT', 'SUNBATHE', 'SUNDIAL', 'SUNRISE', 'SUNSET', 'SUPERHERO', 'SUPERIOR',
  'SUPERSTITION', 'SUPPLY', 'SUPPORTER', 'SUPPORTIVE', 'SUPPOSE', 'SURFACE', 'SURGEON', 'SURGERY', 'SURROUND', 'SURROUNDING',
  'SURVIVAL', 'SURVIVOR', 'SUSPECT', 'SUSPICION', 'SWARM', 'SWEAR', 'SWEATSHIRT', 'SWELL', 'SWIMMER', 'SWITCH',
  'SWOLLEN', 'SWORD', 'SYMPATHY', 'SYMPTOM', 'SYNAGOGUE', 'SYNDROME', 'SYSTEMATIC', 'TABLET', 'TAKEAWAY', 'TALE',
  'TALENTED', 'TALKATIVE', 'TANK', 'TASTE', 'TASTELESS', 'TASTY', 'TAVERN', 'TAX', 'TEACHING', 'TEAMMATE',
  'TEAMWORK', 'TEASE', 'TECHNIQUE', 'TECHNOLOGICAL', 'TEEN', 'TELECOMMUNICATIONS', 'TELEGRAM', 'TELLER', 'TEMPER', 'TEMPORARY',
  'TEMPT', 'TEND', 'TENDENCY', 'TENDER', 'TENSE', 'TENSION', 'TENT', 'TERM', 'TERMINAL', 'TERRIFIC',
  'TERRIFIED', 'TERROR', 'TERRORISM', 'THANKFUL', 'THEATER', 'THEFT', 'THEORY', 'THERAPIST', 'THIRST', 'THOROUGH',
  'THREAT', 'THREATENING', 'THRILLER', 'THUMB', 'THUMP', 'THUNDEROUS', 'TICK', 'TICKLE', 'TIGHTEN', 'TILE',
  'TIMELY', 'TIN', 'TIRE', 'TIRING', 'TISSUE', 'TOBACCO', 'TONGUE', 'TOOTHPASTE', 'TORNADO', 'TOSS',
  'TOTAL', 'TOURISM', 'TOURNAMENT', 'TRACE', 'TRACKSUIT', 'TRAGEDY', 'TRAGIC', 'TRAIL', 'TRANSFER', 'TRANSFORM',
  'TRANSFORMATION', 'TRANSITIONAL', 'TRANSLATE', 'TRANSPORT', 'TRANSPORTATION', 'TRASH', 'TREAT', 'TREATMENT', 'TREMBLE', 'TREMENDOUS',
  'TREND', 'TRIGGER', 'TRIM', 'TRIUMPH', 'TROLL', 'TROPICAL', 'TRUSTWORTHY', 'TSUNAMI', 'TUMBLE', 'TUNA',
  'TURBULENCE', 'TURNING', 'TURTLE', 'TWIN', 'TWIST', 'TYPICAL', 'UNABLE', 'UNAFRAID', 'UNBELIEVABLE', 'UNCERTAINTY',
  'UNCLEAR', 'UNCONTROLLABLE', 'UNCOVER', 'UNDERAGE', 'UNDERGO', 'UNDERPANTS', 'UNDERTAKER', 'UNDO', 'UNDRESS', 'UNEMPLOYED',
  'UNEMPLOYMENT', 'UNEXPECTED', 'UNFIT', 'UNFOLD', 'UNFORTUNATE', 'UNFRIENDLY', 'UNHEARD', 'UNICORN', 'UNIFY', 'UNINTERESTED',
  'UNINTERESTING', 'UNION', 'UNIQUE', 'UNITE', 'UNIVERSE', 'UNLIKELY', 'UNLUCKY', 'UNPACK', 'UNPREDICTABLE', 'UNRELATED',
  'UNTIDY', 'UNWANTED', 'UNWELL', 'UPDATE', 'UPLIFTED', 'UPLOAD', 'UPPER', 'UPSTAIRS', 'UPWARD', 'URGE',
  'URGENT', 'USAGE', 'USELESS', 'VACANCY', 'VAGUE', 'VAIN', 'VALUABLE', 'VAMPIRE', 'VAN', 'VARIETY',
  'VARIOUS', 'VARY', 'VAST', 'VEGETARIAN', 'VEHICLE', 'VEIN', 'VESSEL', 'VET', 'VICE', 'VICTIM',
  'VICTORY', 'VIEWPOINT', 'VILLAIN', 'VIOLENCE', 'VIRTUAL', 'VIRUS', 'VISA', 'VISIBLE', 'VISION', 'VISUAL',
  'VIVID', 'VOLUME', 'VOLUNTEER', 'VOWEL', 'VOYAGE', 'WAGON', 'WARD', 'WARDROBE', 'WAREHOUSE', 'WARMTH',
  'WARN', 'WARNING', 'WARRANTY', 'WARRIOR', 'WASHBOWL', 'WASTE', 'WASTEFUL', 'WAX', 'WEAKNESS', 'WEAPON',
  'WEBCAM', 'WEIRD', 'WEREWOLF', 'WETLAND', 'WHILE', 'WHISPER', 'WHISTLE', 'WIDESPREAD', 'WILDFIRE', 'WILDLIFE',
  'WILLINGNESS', 'WINDMILL', 'WINDSCREEN', 'WINDSURFING', 'WING', 'WIRE', 'WITCH', 'WITHER', 'WITNESS', 'WIZARD',
  'WORKING', 'WORKOUT', 'WORKPLACE', 'WORKSHOP', 'WORN', 'WORTH', 'WORTHWHILE', 'WORTHY', 'WOUND', 'WRAP',
  'WRAPPING', 'WRESTLING', 'WRIST', 'WRISTWATCH', 'WRITTEN', 'YELL', 'YOGA', 'ZIPPER', 'ZOMBIE',
]

export const redWords: string[] = [
  'ABANDONED', 'ABOLISH', 'ABORIGINAL', 'ABSENTEE', 'ABSURD', 'ABSURDITY', 'ABUSE', 'ABYSS', 'ACCESSIBILITY', 'ACCOMMODATION',
  'ACCUMULATE', 'ACCUSATION', 'ACHIEVABLE', 'ACID', 'ACQUISITION', 'ACTUAL', 'ACUTE', 'ADAPTABLE', 'ADDICT', 'ADDICTED',
  'ADDICTION', 'ADEQUATE', 'ADJUSTMENT', 'ADMINISTRATIVE', 'ADMIRABLE', 'ADOPTED', 'ADOPTION', 'ADORE', 'ADORN', 'ADVANCEMENT',
  'ADVENT', 'ADVENTUROUS', 'ADVERSE', 'ADVERSITY', 'AFFECTIONATE', 'AFFORDABLE', 'AGELESS', 'AGONY', 'AIRCRAFT', 'AIRCREW',
  'ALCHEMY', 'ALCOHOLISM', 'ALERT', 'ALLEGATION', 'ALLEGORY', 'ALLIANCE', 'ALLY', 'ALPHABETICAL', 'ALTAR', 'ALTER',
  'ALTERNATE', 'ALTITUDE', 'AMAZE', 'AMAZEMENT', 'AMBASSADOR', 'AMBIGUITY', 'AMBIGUOUS', 'AMMONIA', 'AMPLE', 'AMPLIFIER',
  'AMPLIFY', 'AMPLITUDE', 'AMUSE', 'ANALOGY', 'ANALYST', 'ANARCHY', 'ANCHORAGE', 'ANCHORMAN', 'ANCHORPERSON', 'ANGST',
  'ANGUISH', 'ANIMATE', 'ANOMALY', 'ANONYMOUS', 'ANTIAIRCRAFT', 'ANTIBACTERIAL', 'ANTICANCER', 'ANTICIPATE', 'ANTICIPATION', 'ANTIPOLLUTION',
  'ANTISTATIC', 'ANTIVIRUS', 'APOSTROPHE', 'APPLICANT', 'APPRECIATIVE', 'APPROXIMATE', 'ARCH', 'ARCTIC', 'ARISTOCRACY', 'ARMFUL',
  'AROUSE', 'ARROGANT', 'ARTERY', 'ARTICULATE', 'ARTISTRY', 'ASH', 'ASPIRATION', 'ASPIRE', 'ASSAULT', 'ASSEMBLE',
  'ASSEMBLY', 'ASSERT', 'ASSESS', 'ASSESSMENT', 'ASSUMPTION', 'ASSURANCE', 'ASSURE', 'ASTONISH', 'ASTONISHED', 'ASTONISHING',
  'ASTONISHMENT', 'ASTRONOMY', 'ATHLETICS', 'ATROPHY', 'ATTACHED', 'ATTAINABLE', 'ATTAINMENT', 'ATTENDANCE', 'ATTENTIVE', 'ATTRACTIVENESS',
  'ATTRIBUTE', 'ATYPICAL', 'AUBERGINE', 'AUDIT', 'AUDITION', 'AUTHORITATIVE', 'AVAILABILITY', 'AWAIT', 'AXIS', 'BACKUP',
  'BACKYARD', 'BADGE', 'BALANCED', 'BALKY', 'BALLAD', 'BALLET', 'BALLOT', 'BANKER', 'BANKRUPT', 'BANKRUPTCY',
  'BARLEY', 'BAROMETER', 'BARREN', 'BARRIER', 'BATHHOUSE', 'BATTLEFIELD', 'BEAGLE', 'BEAK', 'BEAM', 'BEARING',
  'BEAUTIFY', 'BELLOW', 'BELONGINGS', 'BENEFICIAL', 'BENEVOLENCE', 'BENEVOLENT', 'BERRY', 'BESTOW', 'BESTSELLER', 'BETRAY',
  'BEWILDER', 'BEWILDERMENT', 'BIDDING', 'BIKINI', 'BILLION', 'BIND', 'BIO', 'BIOLOGICAL', 'BIOTECHNOLOGY', 'BIRDCAGE',
  'BIRTHPLACE', 'BIZARRE', 'BLADE', 'BLAST', 'BLAZE', 'BLINDNESS', 'BLINK', 'BLISS', 'BLOODSTREAM', 'BLOODY',
  'BLOOMING', 'BLOSSOM', 'BLUR', 'BLURT', 'BOILING', 'BOLT', 'BOMBARD', 'BOMBER', 'BOMBING', 'BONY',
  'BOOKISH', 'BOOKLET', 'BOOKMARK', 'BOOST', 'BOOTH', 'BOSSY', 'BOTANY', 'BOTHERED', 'BOTHERSOME', 'BOURBON',
  'BOXER', 'BRACKET', 'BRAG', 'BRAVERY', 'BREAKABLE', 'BREAKDOWN', 'BREAKUP', 'BREATHTAKING', 'BREEZY', 'BREWERY',
  'BROADBAND', 'BROADCASTER', 'BROADEN', 'BROCHURE', 'BROWSE', 'BROWSER', 'BRUISE', 'BULIMIA', 'BULLY', 'BUM',
  'BUMPER', 'BURDENSOME', 'BUREAUCRACY', 'BURGLARY', 'BURGLE', 'BURIAL', 'BUSTLE', 'BUSTLING', 'BUZZ', 'CABLE',
  'CAMPAIGN', 'CANDIDATE', 'CANE', 'CANNONBALL', 'CANON', 'CAPABILITY', 'CAPTION', 'CAPTIVE', 'CARAVAN', 'CARBON',
  'CARDBOARD', 'CARDIGAN', 'CAREFREE', 'CARICATURE', 'CARING', 'CARPOOL', 'CARVE', 'CASCADE', 'CAST', 'CATALYST',
  'CATASTROPHE', 'CATASTROPHIC', 'CATCHY', 'CATERING', 'CATHARSIS', 'CEASE', 'CEILING', 'CELLAR', 'CELLIST', 'CENTIGRADE',
  'CERTIFICATE', 'CERTIFICATION', 'CERTIFY', 'CHANCELLOR', 'CHAOTIC', 'CHARMING', 'CHEAT', 'CHECKPOINT', 'CHEEKY', 'CHEERFULNESS',
  'CHEMOTHERAPY', 'CHERISHED', 'CHEW', 'CHILDISH', 'CHIMNEY', 'CHIP', 'CHOP', 'CHUNK', 'CIPHER', 'CIRCUIT',
  'CIRCUITRY', 'CIRCUMSTANCE', 'CITADEL', 'CITYWIDE', 'CLAP', 'CLARIFY', 'CLASSIFICATION', 'CLAUSE', 'CLEARNESS', 'CLERICAL',
  'CLIENT', 'CLOG', 'CLOSURE', 'CLOTHING', 'CLUMSY', 'COACHING', 'COALITION', 'COARSE', 'COASTLINE', 'COCKTAIL',
  'COCOA', 'COHERENCE', 'COHERENT', 'COINCIDE', 'COINCIDENCE', 'COLLEAGUE', 'COLLECTOR', 'COLLISION', 'COLLOCATION', 'COLON',
  'COLONIAL', 'COMA', 'COMMANDER', 'COMMEMORATE', 'COMMERCE', 'COMMISSION', 'COMMONWEALTH', 'COMMUNICATIVE', 'COMMUNITY', 'COMMUTE',
  'COMPASSION', 'COMPASSIONATE', 'COMPATIBLE', 'COMPENSATE', 'COMPENSATION', 'COMPETENCE', 'COMPETENT', 'COMPILE', 'COMPLETION', 'COMPLEXION',
  'COMPLEXITY', 'COMPONENT', 'COMPREHENSION', 'COMPREHENSIVE', 'COMPRESS', 'COMPRESSION', 'COMPULSORY', 'COMPUTE', 'CONCEAL', 'CONCEDE',
  'CONCEIT', 'CONCEIVABLE', 'CONCEIVE', 'CONCEPTION', 'CONCESSION', 'CONCRETE', 'CONDEMN', 'CONDUCTOR', 'CONE', 'CONFERENCING',
  'CONFESS', 'CONFESSION', 'CONFINE', 'CONFRONT', 'CONJUNCTION', 'CONQUEST', 'CONSCIENCE', 'CONSCIOUSNESS', 'CONSENSUS', 'CONSENT',
  'CONSISTENT', 'CONSOLATION', 'CONSOLE', 'CONSPIRACY', 'CONSTANT', 'CONSULT', 'CONSULTANT', 'CONTAMINATE', 'CONTEMPORARY', 'CONTEMPT',
  'CONTRACT', 'CONTRADICT', 'CONTRADICTION', 'CONTROVERSY', 'CONVENTION', 'CONVENTIONAL', 'CONVERSE', 'CONVERSION', 'CONVERT', 'CONVINCED',
  'COOPERATE', 'COOPERATION', 'COOPERATIVE', 'COPE', 'COPPER', 'CORDUROY', 'CORE', 'CORNERSTONE', 'CORNET', 'CORONA',
  'CORPORAL', 'CORPORATE', 'CORPORATION', 'CORRECTNESS', 'CORRESPOND', 'CORRESPONDENCE', 'CORRESPONDENT', 'CORRESPONDING', 'CORRIDOR', 'CORRUPT',
  'CORRUPTION', 'COSTLY', 'COSTUME', 'COUNTRYMAN', 'COUNTRYWIDE', 'COURTESY', 'COWARD', 'COWARDLY', 'CRACK', 'CRAFTSMAN',
  'CRAWL', 'CREASE', 'CREATION', 'CREEK', 'CREEPY', 'CREW', 'CRIPPLE', 'CRITICISM', 'CRUCIAL', 'CRUELTY',
  'CUBE', 'CUBISM', 'CUFF', 'CULMINATION', 'CURL', 'CURSOR', 'CYBERADDICT', 'CYBERCRIME', 'CYBERPET', 'CYBERSCHOOL',
  'CYBERSPACE', 'CYCLIST', 'DAFT', 'DANDELION', 'DARLING', 'DASH', 'DATA', 'DATABASE', 'DATED', 'DAWN',
  'DAYTIME', 'DEBIT', 'DECADE', 'DECADENCE', 'DECAY', 'DECEIVE', 'DECENT', 'DECEPTION', 'DECEPTIVE', 'DECISIVE',
  'DECK', 'DECOMPOSITION', 'DECORATE', 'DECORATION', 'DECORATIVE', 'DEDICATION', 'DEDUCE', 'DEDUCTION', 'DEEM', 'DEFIANCE',
  'DEFICIT', 'DEFORESTATION', 'DEFY', 'DELEGATE', 'DELIBERATE', 'DELICACY', 'DEMANDING', 'DEMOLISH', 'DENIM', 'DENSE',
  'DENTAL', 'DEPENDABLE', 'DEPUTY', 'DESCEND', 'DESCRIPTIVE', 'DESIRABLE', 'DESKTOP', 'DESOLATION', 'DESPERATION', 'DESPISE',
  'DESTINY', 'DETACH', 'DETACHMENT', 'DETAILED', 'DETECT', 'DETERMINED', 'DETERMINER', 'DEVELOPING', 'DEVIL', 'DEVOTE',
  'DEVOTED', 'DICTATOR', 'DIGEST', 'DIGNIFY', 'DIGNITY', 'DILEMMA', 'DIME', 'DIMENSION', 'DIPHTHERIA', 'DIPLOMA',
  'DIPLOMAT', 'DISAPPEARANCE', 'DISAPPROVAL', 'DISAPPROVE', 'DISCHARGE', 'DISCIPLE', 'DISCIPLINE', 'DISCONNECT', 'DISCORD', 'DISCREDIT',
  'DISCRIMINATE', 'DISGRACE', 'DISGUISE', 'DISHONESTY', 'DISILLUSION', 'DISMISS', 'DISORDER', 'DISORDERLY', 'DISPENSABLE', 'DISPLACE',
  'DISPLEASURE', 'DISPOSAL', 'DISPOSITION', 'DISPUTE', 'DISQUALIFY', 'DISREGARD', 'DISRUPT', 'DISSATISFACTION', 'DISSATISFIED', 'DISSIDENT',
  'DISTINGUISHED', 'DISTORTION', 'DISTRACT', 'DISTRACTION', 'DISTRESSING', 'DISTRIBUTOR', 'DIVERSION', 'DIVERT', 'DIVIDED', 'DIVISION',
  'DIVORCE', 'DNA', 'DOCK', 'DOGMA', 'DOMESTIC', 'DOMINATE', 'DONATE', 'DONATION', 'DOOM', 'DOORKEEPER',
  'DOORWAY', 'DORM', 'DORMITORY', 'DOSE', 'DOUBTFUL', 'DOVE', 'DOWN', 'DOWNFALL', 'DOWNSIZE', 'DOWRY',
  'DRAIN', 'DRAPERY', 'DREAD', 'DREADFUL', 'DREAMY', 'DRIFT', 'DRINKABLE', 'DROOP', 'DROPOUT', 'DUEL',
  'DUMB', 'DUPLICATE', 'DUPLICATION', 'DWARF', 'DYE', 'DYNAMIC', 'DYSTOPIA', 'EARNINGS', 'EASE', 'ECHO',
  'ECOLOGIST', 'ECONOMICAL', 'ECONOMIST', 'ECSTATIC', 'EDIT', 'EDITORIAL', 'EDUCATED', 'EDUCATOR', 'EFFECTIVENESS', 'ELECT',
  'ELECTIVE', 'ELECTRONICS', 'ELEGANCE', 'ELEGANT', 'ELEMENTAL', 'ELIGIBLE', 'ELITE', 'ELOQUENCE', 'ELOQUENT', 'EMBASSY',
  'EMBRACE', 'EMERGENCE', 'EMPLOY', 'EMPLOYEE', 'EMPLOYER', 'ENDORSE', 'ENDURANCE', 'ENDURING', 'ENERGY', 'ENFORCE',
  'ENGAGEMENT', 'ENGULF', 'ENHANCE', 'ENNUI', 'ENTERPRISE', 'ENTERTAINING', 'ENTITLE', 'ENTREPRENEUR', 'ENTROPY', 'ENVIRONMENT',
  'EPIPHANY', 'EQUATION', 'EQUIP', 'EQUITY', 'ERECT', 'ERUPT', 'ERUPTION', 'ESSAYIST', 'ESTATE', 'ESTIMATED',
  'ETHIC', 'ETHNIC', 'EVACUATE', 'EVACUATION', 'EVALUATE', 'EVALUATION', 'EVERLASTING', 'EVIL', 'EVOLUTION', 'EVOLVE',
  'EXACTNESS', 'EXAGGERATE', 'EXAGGERATION', 'EXALT', 'EXAMINEE', 'EXCEED', 'EXCEL', 'EXCEPTION', 'EXCEPTIONAL', 'EXCESSIVE',
  'EXCLAIM', 'EXCLUDE', 'EXCLUSION', 'EXCURSION', 'EXECUTE', 'EXECUTION', 'EXECUTIVE', 'EXHAUST', 'EXHAUSTING', 'EXHAUSTION',
  'EXHIBIT', 'EXILE', 'EXISTING', 'EXOTIC', 'EXPANSION', 'EXPECTATION', 'EXPECTED', 'EXPLODE', 'EXPLOIT', 'EXPLOSIVE',
  'EXPORT', 'EXPRESSIVE', 'EXQUISITE', 'EXTENSION', 'EXTENSIVE', 'EXTERNAL', 'EXTRACT', 'EXULTANT', 'EYEBROW', 'EYELASH',
  'EYELID', 'FABRIC', 'FABULOUS', 'FACILITATE', 'FACILITIES', 'FACTOR', 'FACULTY', 'FAITH', 'FALTER', 'FAME',
  'FAR', 'FASCINATED', 'FASCINATION', 'FATAL', 'FATE', 'FAULTY', 'FEARSOME', 'FEAT', 'FEDERAL', 'FEEDBACK',
  'FERRYBOAT', 'FICTIONAL', 'FIERCE', 'FIGHTING', 'FIGURATIVE', 'FILIAL', 'FINGERNAIL', 'FIREARM', 'FIREPLACE', 'FIRMNESS',
  'FISCAL', 'FIXED', 'FLAME', 'FLAP', 'FLAW', 'FLAWLESS', 'FLAX', 'FLEE', 'FLEET', 'FLESH',
  'FLEXIBILITY', 'FLEXIBLE', 'FLIP', 'FLUENCY', 'FLUID', 'FLUTTER', 'FOLLOWER', 'FOLLY', 'FOOTNOTE', 'FOREMAN',
  'FORESEE', 'FORESTRY', 'FORMATION', 'FORMIDABLE', 'FORTHCOMING', 'FOUL', 'FOUND', 'FRAGRANCE', 'FRAUD', 'FREAK',
  'FRICTION', 'FRIENDLY', 'FRIGATE', 'FRONTIER', 'FRUGAL', 'FUME', 'FUNCTIONAL', 'FUNCTIONALITY', 'FUNDAMENTAL', 'FUNK',
  'FUNKY', 'FURIOUS', 'GAIETY', 'GAMBLING', 'GANG', 'GANGSTER', 'GARDENER', 'GASP', 'GATEWAY', 'GAUDY',
  'GAZE', 'GEAR', 'GENEROSITY', 'GENIUS', 'GENRE', 'GENUINE', 'GEOGRAPHIC', 'GERM', 'GERRYMANDER', 'GETAWAY',
  'GIVEAWAY', 'GLACIS', 'GLARE', 'GLEAM', 'GLEE', 'GLOCAL', 'GLOOMY', 'GLORIFY', 'GLOW',
  'GOD', 'GODLY', 'GOODWILL', 'GORGE', 'GOVERNMENTAL', 'GRACEFULNESS', 'GRADUAL', 'GRAIN', 'GRAND',
  'GRASP', 'GRAVESTONE', 'GRAVITATION', 'GREATNESS', 'GRIEF', 'GRIEVE', 'GRIM', 'GRIN', 'GRIP', 'GROSS',
  'GROWING', 'GUERRILLA', 'GUIDELINE', 'GULP', 'GUM', 'GUNSHOT', 'GUTS', 'GYMNASTIC', 'HABITANT', 'HAIKU',
  'HAIRY', 'HANDICAP', 'HANDICRAFT', 'HANDOUT', 'HANDRAIL', 'HARBINGER', 'HARDWARE', 'HARMLESS', 'HARROW', 'HASTE',
  'HATCHING', 'HAUNTING', 'HAY', 'HAZARDOUS', 'HEADQUARTERS', 'HEAP', 'HEARTBREAKING', 'HEDGE', 'HEGEMONY', 'HELPER',
  'HEMP', 'HERB', 'HERITAGE', 'HESITATION', 'HIJACK', 'HILARIOUS', 'HINT', 'HOLDER', 'HOLLOW',
  'HOMAGE', 'HOMEWARD', 'HONE', 'HOOD', 'HOOK', 'HOSPICE', 'HOSPITABLE', 'HOSPITALITY', 'HOURLY', 'HOUSEKEEPER',
  'HOUSEMASTER', 'HOUSEWIFE', 'HOVER', 'HUBRIS', 'HUMANE', 'HUMANIST', 'HUMBLE', 'HUMBUG', 'HUMILIATE', 'HUMILIATING',
  'HUMILIATION', 'HUSH', 'HYBRID', 'HYGIENE', 'HYPERBOLE', 'HYPHEN', 'ICEMAN', 'ICON', 'ICY', 'IDENTICAL',
  'IDENTIFICATION', 'IDENTIFY', 'IDEOLOGY', 'IDIOT', 'IDLE', 'IGNORANCE', 'IGNORANT', 'ILLUSION', 'ILLUSTRATE', 'ILLUSTRATION',
  'IMAGERY', 'IMITATION', 'IMMERSE', 'IMMIGRANT', 'IMMORAL', 'IMMORTAL', 'IMMORTALITY', 'IMPARTIAL', 'IMPERATIVE', 'IMPERMANENT',
  'IMPLEMENT', 'IMPLICATION', 'IMPLY', 'IMPOLITE', 'IMPORT', 'IMPOSE', 'IMPOSSIBILITY', 'IMPRACTICAL', 'IMPRESSED', 'IMPRESSIONISM',
  'IMPRESSIONIST', 'IMPRISON', 'IMPRISONMENT', 'IMPROBABLE', 'IMPROVED', 'IMPULSE', 'IMPULSIVE', 'INACCURATE', 'INADEQUATE', 'INANIMATE',
  'INBORN', 'INCENSE', 'INCENTIVE', 'INCUR', 'INCURABLE', 'INDEBTED', 'INDENT', 'INDESCRIBABLE', 'INDEX', 'INDIFFERENT',
  'INDIGNITY', 'INDISPENSABLE', 'INDULGE', 'INDULGENT', 'INEFFECTIVE', 'INERT', 'INEXPERIENCED', 'INFECT', 'INFECTED', 'INFECTIOUS',
  'INFER', 'INFERENCE', 'INFLAMMATION', 'INFLAMMATORY', 'INFLATE', 'INFLATION', 'INFLUENTIAL', 'INFLUENZA', 'INFORMAL', 'INFRINGE',
  'INFRINGEMENT', 'INHABIT', 'INHERIT', 'INITIATIVE', 'INJECTION', 'INJURED', 'INNATE', 'INNOVATION', 'INNOVATIVE', 'INPUT',
  'INSEPARABLE', 'INSIDE', 'INSPECT', 'INSPECTOR', 'INSPIRATIONAL', 'INSTINCT', 'INSTITUTION', 'INSTRUCT', 'INSUFFICIENT', 'INSULT',
  'INTEGRATE', 'INTELLECTUAL', 'INTENT', 'INTERACTIVE', 'INTERFERE', 'INTERIOR', 'INTERPERSONAL', 'INTERPRET', 'INTERPRETATION', 'INTERPRETER',
  'INTERRUPTION', 'INTERSECTION', 'INTIMATE', 'INTRANSITIVE', 'INTRAVENOUS', 'INTRUDE', 'INTRUDER', 'INTRUSION', 'INVARIABLE', 'INVESTIGATE',
  'INVESTIGATOR', 'INVESTMENT', 'INVESTOR', 'INVISIBLE', 'INVOKE', 'INVOLVEMENT', 'IRONY', 'IRRATIONAL', 'IRRESISTIBLE', 'IRRESPONSIBLE',
  'IRRITATED', 'IRRITATING', 'IRRITATION', 'ISLANDER', 'ITCH', 'JAW', 'JOURNALISM', 'JUDO', 'JUROR', 'JURY',
  'JUSTIFY', 'KARAOKE', 'KEEPER', 'KEROSENE', 'KEYSTROKE', 'KNEEL', 'KNOT', 'KNOWN', 'LABEL', 'LABYRINTH',
  'LAME', 'LANCE', 'LANDING', 'LANDLADY', 'LAP', 'LAPTOP', 'LARK', 'LASER', 'LATER', 'LATTER',
  'LAUNDRY', 'LAVA', 'LAWMAKER', 'LAWN', 'LAWSUIT', 'LAYABOUT', 'LEAFLET', 'LEAK', 'LEARNING', 'LEASE',
  'LEASH', 'LECTURER', 'LEEK', 'LEGEND', 'LEGENDARY', 'LEGISLATE', 'LEGISLATION', 'LEGISLATIVE', 'LEGISLATOR', 'LEGISLATURE',
  'LEGITIMATE', 'LENGTHEN', 'LENGTHY', 'LEOPARD', 'LIBERAL', 'LICK', 'LID', 'LIFELESS', 'LIFETIME', 'LIGHTEN',
  'LIGHTING', 'LIMB', 'LIMBO', 'LINEN', 'LINER', 'LING', 'LINGER', 'LISTENER', 'LITERAL', 'LITTER',
  'LOAN', 'LOBBY', 'LONELINESS', 'LOUSY', 'LOWER', 'LOWLAND', 'LUCRATIVE', 'LUSH', 'LUXURIOUS', 'LYRICS',
  'MADAM', 'MADAME', 'MADNESS', 'MAESTRO', 'MAGNETISM', 'MAGNIFY', 'MALADY', 'MALARIA', 'MANIFESTO', 'MANIPULATE',
  'MANUAL', 'MANUFACTURE', 'MANUFACTURER', 'MANUFACTURING', 'MARGIN', 'MARKETING', 'MASK', 'MASSAGE', 'MASSEUR',
  'MASTER', 'MASTERPIECE', 'MASTERY', 'MATE', 'MATHEMATICAL', 'MATURE', 'MEANS', 'MEDIA', 'MEDICATION', 'MEDIOCRE',
  'MELANCHOLY', 'MELODY', 'MEMORIAL', 'MENTOR', 'MERCHANDISE', 'MERCY', 'MERGE', 'MERGER', 'MESSENGER', 'METAMORPHOSIS',
  'METAPHOR', 'METRIC', 'MICRO', 'MICROBE', 'MICROCOMPUTER', 'MICROORGANISM', 'MICROPHONE', 'MICROSCOPE', 'MICROSCOPIC', 'MICROSCOPY',
  'MICROWAVE', 'MIDST', 'MIGHTY', 'MIGRATION', 'MILL', 'MILLIONAIRE', 'MIMIC', 'MINE', 'MINIATURE', 'MINISTER',
  'MIRAGE', 'MISCONCEPTION', 'MISFORTUNE', 'MISLEADING', 'MISSILE', 'MISTREAT', 'MISTRUSTFUL', 'MISUNDERSTAND', 'MIXTURE', 'MOBILITY',
  'MOCK', 'MODEST', 'MODIFICATION', 'MOGUL', 'MOMENTARY', 'MOMENTUM', 'MONASTERY', 'MOODY', 'MOONLIGHT', 'MOONSCAPE',
  'MORALITY', 'MORTAL', 'MORTGAGE', 'MORTIFY', 'MOTION', 'MOTIVATED', 'MOTORBIKE', 'MOTORIST', 'MOURNFUL', 'MOVER',
  'MOVING', 'MUDDY', 'MULTIPLE', 'MULTIPLY', 'MUMBLE', 'MURMUR', 'MUSE', 'MUTABILITY', 'MUTABLE', 'MUTTER',
  'MUTTON', 'MYSTIFY', 'NANO', 'NARCISSISTIC', 'NARRATOR', 'NATIONWIDE', 'NAVAL', 'NAVIGATE', 'NAVIGATION', 'NAVY',
  'NECESSITY', 'NEEDLESS', 'NEEDY', 'NEGLECT', 'NERVE', 'NERVES', 'NEUROSIS', 'NEWSCASTER', 'NEWSWORTHY', 'NEXUS',
  'NIGHTCLUB', 'NIGHTMARE', 'NOBILITY', 'NOBLE', 'NOBLEMAN', 'NOMAD', 'NOMINATION', 'NOMINEE', 'NONPROFESSIONAL', 'NOSTRIL',
  'NOUGHT', 'NOURISH', 'NOURISHMENT', 'NOVELTY', 'NUANCE', 'NUISANCE', 'NUMERICAL', 'NURSERY', 'NUT', 'NUTSHELL',
  'OATH', 'OBEDIENCE', 'OBEDIENT', 'OBEY', 'OBITUARY', 'OBLIGATION', 'OBLIVION', 'OBSERVER', 'OBSESS', 'OBSESSION',
  'OBSESSIVE', 'ODD', 'OFFEND', 'OFFENDER', 'OFFSHORE', 'OINTMENT', 'OLYMPIA', 'OLYMPIAD', 'OMEN', 'OPERATOR',
  'OPPONENT', 'OPTIMISM', 'OPTIMIST', 'OPTIMISTIC', 'OPTIONAL', 'ORACLE', 'ORATOR', 'ORCHESTRAL', 'ORCHID', 'ORIGINALITY',
  'ORIGINATE', 'ORNAMENT', 'OUNCE', 'OUTBACK', 'OUTBREAK', 'OUTCOME', 'OUTDISTANCE', 'OUTDO', 'OUTFIT', 'OUTGROW',
  'OUTING', 'OUTLET', 'OUTLIVE', 'OUTLOOK', 'OUTPATIENT', 'OUTPUT', 'OUTRAGE', 'OUTRAGEOUS', 'OUTSHINE', 'OUTSIDE',
  'OUTSIDER', 'OUTSKIRTS', 'OVAL', 'OVERALL', 'OVERBOOK', 'OVERCOAT', 'OVERESTIMATE', 'OVERHEAR', 'OVERLAP', 'OVERLOOK',
  'OVERSEAS', 'OVERSHADOW', 'OVERSIZE', 'OVERSTEP', 'OVERTAKE', 'OVERTHROW', 'OVERTIME', 'OVERTURN', 'OZONE', 'PACKED',
  'PACKET', 'PAD', 'PALLET', 'PANDEMIC', 'PANEL', 'PAPAYA', 'PAPERLESS', 'PAPERWORK', 'PARADOX', 'PARALYSIS',
  'PARAMEDIC', 'PARATROOPER', 'PARLIAMENT', 'PARODY', 'PARTICIPATION', 'PARTICLE', 'PARTICULAR', 'PARTISAN', 'PARTNERSHIP', 'PASSIONATE',
  'PASTOR', 'PASTORAL', 'PATCH', 'PATRIOT', 'PATRIOTIC', 'PATRIOTISM', 'PATRON', 'PAVE', 'PAVEMENT', 'PAW',
  'PAWNBROKER', 'PAWNSHOP', 'PAYMENT', 'PEAK', 'PEARL', 'PEDAL', 'PEDANTIC', 'PEDESTRIAN', 'PEE', 'PEEL',
  'PEEP', 'PEER', 'PEG', 'PENALTY', 'PENETRATE', 'PENICILLIN', 'PENSION', 'PENTAGON', 'PERCEIVE', 'PERCENTAGE',
  'PERCEPTION', 'PERMANENCE', 'PERMEATE', 'PERSEVERANCE', 'PERSIST', 'PERSISTENCE', 'PERSISTENT', 'PERSONIFICATION', 'PERSONIFY', 'PERSONNEL',
  'PERSPECTIVE', 'PERSPIRATION', 'PERSUASION', 'PESSIMIST', 'PESSIMISTIC', 'PETRIFIED', 'PETTY', 'PHARAOH', 'PHARMACIST', 'PHASE',
  'PHILOSOPHICAL', 'PHYSICIAN', 'PICKY', 'PICTURESQUE', 'PILLOWCASE', 'PINNACLE', 'PINT', 'PIRACY', 'PITCH', 'PLACEBO',
  'PLAGUE', 'PLANNING', 'PLAYMATE', 'PLAYWRIGHT', 'PLEAD', 'PLOT', 'PLUCK', 'PLUS', 'PNEUMONIA', 'POINTLESS',
  'POLARITY', 'POLIO', 'POLISH', 'POLITENESS', 'POLITY', 'PONDER', 'POPULARITY', 'PORCH', 'PORTION', 'POSE',
  'POSH', 'POSSESSED', 'POSTAL', 'POSTPONE', 'POTENT', 'PRACTICALITY', 'PRANCE', 'PRAWN', 'PRECEDE', 'PREDICAMENT',
  'PREDICATE', 'PREDICATIVE', 'PREDICTABLE', 'PREDICTIVE', 'PREDICTOR', 'PREFECT', 'PREFERABLE', 'PREHISTORIC', 'PREHUMAN', 'PREINDUSTRIAL',
  'PREJUDGE', 'PRELIMINARY', 'PREOCCUPY', 'PRESCRIBE', 'PRESENTER', 'PRESIDENCY', 'PRESIDENTIAL', 'PRESTIGE', 'PRESTIGIOUS', 'PREVAIL',
  'PREVENTION', 'PREVENTIVE', 'PRICELESS', 'PRICK', 'PRIMARY', 'PRIME', 'PRIOR', 'PRIORITY', 'PRIVILEGE', 'PROBABLE',
  'PROBE', 'PROCEDURE', 'PROFILE', 'PROFIT', 'PROFITABLE', 'PROGRAMMER', 'PROGRAMMING', 'PROHIBIT', 'PROJECT', 'PROJECTION',
  'PROMINENCE', 'PROMPT', 'PROPAGANDA', 'PROPHECY', 'PROPONENT', 'PROPOSED', 'PROSE', 'PROSECUTE', 'PROSPECT', 'PROSPER',
  'PROVEN', 'PROVINCE', 'PROVISION', 'PROXIMITY', 'PSYCHOLOGY', 'PUBLICATION', 'PUBLICITY', 'PUDDING', 'PULSE', 'PUNCH',
  'PUNCTUAL', 'PUNCTUALITY', 'PURCHASE', 'PURPOSEFUL', 'PURSUIT', 'PUZZLED', 'QUALIFICATION', 'QUANTIFY', 'QUARANTINE', 'QUARREL',
  'QUARRELSOME', 'QUERY', 'QUOTABLE', 'QUOTATION', 'QUOTE', 'RACK', 'RADAR', 'RADIATE', 'RADICAL',
  'RADIUM', 'RAFTER', 'RAG', 'RAINSTORM', 'RAMP', 'RASH', 'RATTLE', 'RAVAGE', 'REACTION',
  'REAR', 'REBEL', 'REBELLION', 'REBELLIOUS', 'RECESSION', 'RECIPE', 'RECKON', 'RECOGNITION', 'RECOLLECT', 'RECOLLECTION',
  'RECOMMENDABLE', 'RECOMMENDATION', 'RECONSIDER', 'RECREATION', 'RECRUIT', 'RECTANGULAR', 'REDEMPTION', 'REDO', 'REDUNDANT', 'REED',
  'REFERENCE', 'REFERENT', 'REFINERY', 'REFLECTIVE', 'REFORM', 'REFRAIN', 'REFRESH', 'REFUGE', 'REFUGEE', 'REFUTE',
  'REGGAE', 'REGIME', 'REGULATE', 'REINFORCE', 'REINFORCEMENT', 'REJECTION', 'REJOIN', 'RELATED', 'RELATIVITY', 'RELAXATION',
  'RELAY', 'RELEVANT', 'RELIC', 'RELIEF', 'RELIEVE', 'RELIEVED', 'RELUCTANT', 'REMAINING', 'REMAINS', 'REMINDER',
  'REMNANT', 'RENTAL', 'REPAINT', 'REPERTOIRE', 'REPETITION', 'REPLACEMENT', 'REPLICA', 'REPRESS', 'REPRESSION', 'REPRINT',
  'REPROVE', 'RESIDENCE', 'RESIGN', 'RESIGNATION', 'RESISTANCE', 'RESOLUTION', 'RESONANCE', 'RESONANT', 'RESPECTED', 'RESPIRATION',
  'RESPIRATORY', 'RESTRICTION', 'RESUME', 'RETAILER', 'RETINA', 'RETIREMENT', 'RETREAT', 'RETRIEVE', 'REVELATION',
  'REVENGE', 'REVENUE', 'REVERENCE', 'REVERSE', 'REVIVAL', 'REVIVE', 'REVOLUTION', 'REVOLUTIONARY', 'REVOLVE', 'RHINOCEROS',
  'RHYME', 'RHYTHMIC', 'RIB', 'RIDER', 'RIDGE', 'RIGHTEOUSNESS', 'RIM', 'RIP', 'RISKY', 'RITE',
  'RITUAL', 'RIVAL', 'ROAM', 'ROAR', 'ROCKY', 'ROOMMATE', 'ROSY', 'ROUTE', 'ROYALTY', 'RUB',
  'RUBBLE', 'RUINOUS', 'RURAL', 'RUSTY', 'SACK', 'SAG', 'SAGE', 'SAIL', 'SALARY', 'SALESMANSHIP',
  'SALESPERSON', 'SALESWOMAN', 'SALSA', 'SALTY', 'SANCTUARY', 'SANDSTONE', 'SANITARY', 'SANITATION', 'SARCASM', 'SATIRE',
  'SATISFACTORY', 'SCANDAL', 'SCAR', 'SCARLET', 'SCENT', 'SCHADENFREUDE', 'SCHEDULED', 'SCHEME', 'SCHOLASTICISM', 'SCHOOLGIRL',
  'SCRAMBLE', 'SCRIBBLE', 'SCROOGE', 'SCUBA', 'SCYTHE', 'SEASONAL', 'SECONDARY', 'SECTOR', 'SEESAW', 'SEGMENT',
  'SELFLESS', 'SELLER', 'SEMICOLON', 'SEMINAR', 'SENATOR', 'SENSIBLE', 'SENSITIVE', 'SERENDIPITY', 'SERENE', 'SERENITY',
  'SERIAL', 'SERVANT', 'SETBACK', 'SHABBY', 'SHAKEN', 'SHAKESPEAREAN', 'SHAKY', 'SHATTER',
  'SHED', 'SHIELD', 'SHIPPING', 'SHIPWRECK', 'SHOOTING', 'SHOPKEEPER', 'SHOPLIFT', 'SHOPLIFTER', 'SHOPLIFTING', 'SHORTNESS',
  'SHOWBIZ', 'SHOWCASE', 'SHRINK', 'SHRUG', 'SIGNIFY', 'SILVERWARE', 'SIMPLIFICATION', 'SIMULTANEOUS', 'SINCERE', 'SINCERITY',
  'SKATEBOARDER', 'SKETCH', 'SKILLED', 'SKIM', 'SKIP', 'SKYLARK', 'SLAM', 'SLANG', 'SLAP', 'SLASH',
  'SLAUGHTER', 'SLIVER', 'SLOPPY', 'SMASH', 'SMOKESTACK', 'SNAP', 'SNEAK', 'SNEER', 'SNIFF', 'SNORE',
  'SNOWBALL', 'SOAK', 'SOAKED', 'SOAKING', 'SOAR', 'SOB', 'SOCIABLE', 'SOFTNESS', 'SOLAR', 'SOLIDITY',
  'SOLILOQUY', 'SOLITUDE', 'SOLO', 'SOLVENT', 'SONNET', 'SOPHISTICATED', 'SOUNDTRACK', 'SOVEREIGNTY', 'SOVIET', 'SOYBEAN',
  'SPAN', 'SPARE', 'SPARERIB', 'SPARK', 'SPARKLING', 'SPECIALTY', 'SPECIES', 'SPECIFY', 'SPECTACLE', 'SPECTER',
  'SPECTRUM', 'SPEEDER', 'SPELLBOUND', 'SPIN', 'SPITE', 'SPLATTER', 'SPOKESMAN', 'SPOKESWOMAN', 'SPRAY', 'SPREADSHEET',
  'SPRINT', 'SPUR', 'SQUAD', 'SQUASH', 'SQUEEZE', 'STAB', 'STABILITY', 'STACK', 'STAGGER', 'STAGNATION',
  'STAIN', 'STAKE', 'STAMMER', 'STANDBY', 'STANDSTILL', 'STANZA', 'STARTLE', 'STARVATION', 'STARVE', 'STARVING',
  'STATESMAN', 'STATISTICS', 'STEELY', 'STEER', 'STEPFATHER', 'STEPMOTHER', 'STEREOTYPE', 'STERN', 'STEW', 'STIFF',
  'STIMULANT', 'STIMULATE', 'STIMULATION', 'STINGY', 'STINK', 'STITCH', 'STOCK', 'STOCKPILE', 'STOICISM', 'STONEWORK',
  'STOOL', 'STOPOVER', 'STOPWATCH', 'STRAIGHTEN', 'STRAIGHTFORWARD', 'STRAIT', 'STRAND', 'STRANGLE', 'STRIDE', 'STRIKING',
  'STRIVE', 'STROKE', 'STYLIST', 'SUBCONTINENT', 'SUBCULTURE', 'SUBDIVISION', 'SUBJUNCTIVE', 'SUBMIT', 'SUBPLOT', 'SUBSIDE',
  'SUBSTANCE', 'SUBTEXT', 'SUBTITLE', 'SUBTLE', 'SUBTRACT', 'SUBURB', 'SUCCESSIVE', 'SUCK', 'SUE', 'SUFFERING',
  'SUNBEAM', 'SUPERB', 'SUPERINTENDENT', 'SUPERVISE', 'SUPERVISION', 'SUPERVISOR', 'SUPPLEMENT', 'SUPPLIER', 'SUPPRESS', 'SURGE',
  'SURRENDER', 'SURROUNDINGS', 'SURVEILLANCE', 'SUSPEND', 'SUSPENSE', 'SUSPICIOUS', 'SUSTAIN', 'SWEEP', 'SWIFT', 'SWING',
  'SYLLABLE', 'SYMBOLIC', 'SYMPATHETIC', 'SYNONYM', 'TABLECLOTH', 'TABLOID', 'TACK', 'TACKLE', 'TACTILE', 'TAG',
  'TAIL', 'TAME', 'TAN', 'TANNED', 'TATTER', 'TATTOO', 'TAUNT', 'TEASPOON', 'TECHNICAL', 'TELESCOPE',
  'TEMPERATE', 'TEMPTATION', 'TENDERNESS', 'TERRACE', 'TERRIFYING', 'TERRITORY', 'TESTIFY', 'TESTIMONY', 'THEME', 'THEORIST',
  'THERAPY', 'THERMOMETER', 'THESIS', 'THICKNESS', 'THIGH', 'THINKER', 'THOUGHTFUL', 'THOUGHTLESS', 'THREAD', 'THREATEN',
  'THRESHOLD', 'THRILL', 'THRILLED', 'THRILLING', 'THROAT', 'TIGHTROPE', 'TIMELESS', 'TIMELINESS', 'TIMING', 'TIPTOE',
  'TIREDNESS', 'TIRESOME', 'TOENAIL', 'TOIL', 'TOLERANT', 'TOLERATE', 'TOLL', 'TOMB', 'TON', 'TORCH',
  'TORTOISESHELL', 'TOUGH', 'TOXIC', 'TRADER', 'TRAILER', 'TRAINEE', 'TRAINER', 'TRAIT', 'TRAITOR',
  'TRAJECTORY', 'TRAMP', 'TRAMPLE', 'TRANSCENDENCE', 'TRANSCRIPT', 'TRANSFUSION', 'TRANSISTOR', 'TRANSITION', 'TRANSITIVE', 'TRANSLATION',
  'TRANSLATOR', 'TRANSMISSION', 'TRANSMIT', 'TRANSPARENT', 'TRAVERSE', 'TREAD', 'TREATY', 'TREK', 'TREMOR', 'TRIAL',
  'TRIANGLE', 'TRIBE', 'TRICKY', 'TRIO', 'TRIVIAL', 'TROLLEY', 'TROOP', 'TROPIC', 'TROUBLESOME', 'TRUNK',
  'TRUSTY', 'TRUTHFUL', 'TRUTHFULNESS', 'TUB', 'TUBERCULOSIS', 'TUG', 'TUITION', 'TUNNEL', 'TURBULENT', 'TUTOR',
  'TWINKLE', 'TWISTED', 'TYPHOID', 'TYRANNY', 'TYRANT', 'ULTIMATE', 'UNACCEPTABLE', 'UNATTRACTIVE', 'UNAVAILABLE', 'UNAWARE',
  'UNBEARABLE', 'UNBEATABLE', 'UNCHANGED', 'UNCHARACTERISTIC', 'UNCOMMON', 'UNCONCERNED', 'UNCONSCIOUS', 'UNDERESTIMATE', 'UNDERGRADUATE', 'UNDERGROUND',
  'UNDERSEA', 'UNDERSTANDABLE', 'UNDERSTANDING', 'UNDERTAKE', 'UNDERWEAR', 'UNDREAMED', 'UNDRESSED', 'UNEASE', 'UNENTHUSIASTIC', 'UNEVEN',
  'UNFAMILIAR', 'UNFASHIONABLE', 'UNFORESEEN', 'UNGODLY', 'UNHAPPINESS', 'UNHELPFUL', 'UNIMAGINABLE', 'UNITED', 'UNIVERSAL', 'UNKIND',
  'UNLIMITED', 'UNLOAD', 'UNLOCK', 'UNMISTAKABLE', 'UNNATURAL', 'UNOFFICIAL', 'UNPOPULAR', 'UNREALISTIC', 'UNREASONABLE', 'UNRELIABLE',
  'UNREST', 'UNSAFE', 'UNSATISFACTORY', 'UNSELFISH', 'UNSUCCESSFUL', 'UNSUITABLE', 'UNSURE', 'UNTALENTED', 'UNTIE', 'UNTREATED',
  'UNTRIMMED', 'UNUSUALNESS', 'UNWILLING', 'UNWISE', 'UNWORLDLY', 'UPBRINGING', 'UPGRADE', 'UPRIGHT', 'URBAN', 'USER',
  'USHER', 'UTILITY', 'UTOPIA', 'UTTER', 'VACANT', 'VACCINE', 'VALENTINE', 'VALID', 'VANISH', 'VANITY',
  'VARIATION', 'VARIED', 'VELOCITY', 'VENTURE', 'VENUE', 'VERBAL', 'VERSE', 'VERSION', 'VERTIGO', 'VERY',
  'VESTIGE', 'VETERAN', 'VIBRATE', 'VIBRATION', 'VIEWER', 'VIGOROUS', 'VILLA', 'VILLAGER', 'VINEGAR', 'VIOLATE',
  'VIRTUE', 'VITAL', 'VITAMIN', 'VOCALIST', 'VOID', 'VOMIT', 'VORTEX', 'VOTER', 'VOW', 'WAGE',
  'WAIST', 'WAISTCOAT', 'WALKABOUT', 'WALKER', 'WALLBOARD', 'WANDERLUST', 'WARSHIP', 'WARTIME', 'WASP', 'WATERPROOF',
  'WAVELENGTH', 'WEAKEN', 'WEALTHY', 'WEARISOME', 'WEARY', 'WEAVE', 'WED', 'WEED', 'WELFARE', 'WESTERN',
  'WHEAT', 'WHIMSY', 'WHIP', 'WIDEN', 'WIDOW', 'WIDTH', 'WILDERNESS', 'WILL', 'WILLING', 'WINDING',
  'WINDSHIELD', 'WINK', 'WIPE', 'WIT', 'WITHDRAW', 'WITHDRAWAL', 'WITTY', 'WONDROUS', 'WOODCARVING', 'WORKAHOLIC',
  'WORKBENCH', 'WORKMAN', 'WORKTABLE', 'WORLDLY', 'WORLDVIEW', 'WORLDWIDE', 'WORM', 'WORRYING', 'WORSEN', 'WORSHIP',
  'WORTHLESS', 'WRECK', 'YACHT', 'YAWN', 'YEARN', 'YIELD', 'YOUTHFUL', 'YUMMY', 'ZEITGEIST', 'ZENITH',
  'ZIP', 'ZOOM',
]

// Money round pool — distinct high-energy phrases for the final screen.
export const moneyWords: string[] = [
  'AIR GUITAR', 'ALIEN ABDUCTION', 'BACKSTAGE PASS', 'BALLOON DROP', 'BATTLE OF THE BANDS', 'BEACH BONFIRE', 'BIGFOOT SIGHTING', 'BIRTHDAY CAKE', 'BLACK LIGHT', 'BLANKET FORT',
  'BLOW UP POOL', 'BOARD GAME NIGHT', 'BOBA TEA', 'BOTTLE ROCKET', 'BRAIN FREEZE', 'BRUNCH BUFFET', 'BUBBLE MACHINE', 'CAMPUS LEGEND', 'CAR CHASE', 'CEREAL MASCOT',
  'CHAMPAGNE TOWER', 'CHEESE FOUNTAIN', 'CLASS GROUP CHAT', 'CLOWN CAR', 'COFFEE RUN', 'CONFETTI CANNON', 'COSTUME PARTY', 'COUNTDOWN CLOCK', 'CRASH PAD', 'DANCE BATTLE',
  'DORM ROOM', 'DOUBLE DATE', 'DRAMA QUEEN', 'ESCAPE ROOM', 'FANTASY DRAFT', 'FAST FOOD DRIVE THRU', 'FILM PREMIERE', 'FINAL EXAM', 'FIRE DRILL', 'FOAM FINGER',
  'FOOD TRUCK', 'FRAT HOUSE', 'FREE SAMPLE', 'FRIEND ZONE', 'GAME DAY', 'GHOST STORY', 'GLITTER BOMB', 'GROUP PROJECT', 'HALL PASS', 'HAUNTED HOUSE',
  'HIDDEN TALENT', 'HIGH FIVE', 'HOT SAUCE', 'HOUSE PARTY', 'ICE CREAM TRUCK', 'INSIDE JOKE', 'INSTANT RAMEN', 'JUMP SCARE', 'KARAOKE NIGHT', 'KITCHEN SINK',
  'LASER TAG', 'LAST CALL', 'LAUNDRY DAY', 'LIP SYNC', 'LIVE STREAM', 'LOCKER ROOM', 'LOST AND FOUND', 'MASCOT SUIT', 'MIDNIGHT SNACK', 'MOVIE TRAILER',
  'MUSIC FESTIVAL', 'NERF WAR', 'OPEN MIC', 'PARTY BUS', 'PEP RALLY', 'PHOTO BOOTH', 'PILLOW FIGHT', 'PIZZA DELIVERY', 'PODCAST HOST', 'POOL FLOAT',
  'POP QUIZ', 'POWER NAP', 'PRANK CALL', 'RAFFLE TICKET', 'RED CARPET', 'ROAD TRIP', 'ROOFTOP PARTY', 'ROOMMATE CODE', 'SCAVENGER HUNT', 'SECRET MENU',
  'SELFIE STICK', 'SHOPPING CART', 'SLEEPOVER STORY', 'SNOW DAY', 'SOAP OPERA', 'SODA FOUNTAIN', 'SPACE CAMP', 'SPIRIT WEEK', 'SPORTS BAR', 'STAGE DIVE',
  'STUDY BREAK', 'SUMMER CAMP', 'TACO TRUCK', 'TAILGATE PARTY', 'TALENT SHOW', 'TEXT MESSAGE', 'THEME SONG', 'THRIFT STORE', 'TIKTOK DANCE', 'TOGA PARTY',
  'TRIVIA NIGHT', 'UGLY SWEATER', 'VENDING MACHINE', 'VIDEO GAME BOSS', 'VIP SECTION', 'VOICE MEMO', 'WATER BALLOON', 'WEEKEND PLANS', 'WIFI PASSWORD', 'YEARBOOK PHOTO',
  'YOGA POSE', 'ZIP LINE', 'ZOOM CALL', 'AWARD SHOW', 'BACKYARD BBQ', 'BLOCK PARTY', 'CARD TRICK', 'DANCE FLOOR', 'DESSERT TABLE', 'ENERGY DRINK',
  'FAKE ID', 'FASHION SHOW', 'FOOD COMA', 'FREE THROW', 'GAME CONTROLLER', 'HOMECOMING DANCE', 'ICE BREAKER', 'JELLO SHOT', 'JUKEBOX HERO', 'LIGHT SABER',
  'MAGIC SHOW', 'MARCHING BAND', 'MIC DROP', 'NERVOUS LAUGH', 'PARTY HAT', 'PHONE CHARGER', 'PROM PHOTO', 'QUARTERBACK SNEAK', 'RAIN CHECK', 'ROLLER RINK',
  'SCHOOL SPIRIT', 'SILENT DISCO', 'SNACK TABLE', 'SPRING BREAK', 'STUDENT SECTION', 'SURPRISE PARTY', 'TEAM PHOTO', 'TEXT THREAD', 'VICTORY SONG', 'WATER PARK',
]

const WORD_POOLS: WordPools = {
  bidding: Array.from(new Set([...greenWords, ...yellowWords])),
  green: greenWords,
  yellow: yellowWords,
  red: redWords,
  money: moneyWords,
}

export function getWordPools(): WordPools {
  return {
    bidding: [...WORD_POOLS.bidding],
    green: [...WORD_POOLS.green],
    yellow: [...WORD_POOLS.yellow],
    red: [...WORD_POOLS.red],
    money: [...WORD_POOLS.money],
  }
}

export function getWordsForDeck(deckId: WordDeckId, count: number, usedWords: string[] = []): string[] {
  return pickWords(WORD_POOLS[deckId], count, usedWords)
}

export function getBiddingWords(usedWords: string[] = []): string[] {
  return getWordsForDeck('bidding', 5, usedWords)
}

export function getColorWords(difficulty: Difficulty, usedWords: string[] = []): string[] {
  return getWordsForDeck(difficulty, 5, usedWords)
}

export function getMoneyWords(usedWords: string[] = []): string[] {
  return getWordsForDeck('money', 10, usedWords)
}

export const WORD_BANK_TAGS: WordTag[] = [
  'campus',
  'party',
  'sports',
  'movies',
  'music',
  'internet',
  'food',
  'relationships',
  'travel',
  'jobs',
  'slang',
  'history',
  'science',
  'games',
  'brands',
  'places',
  'phrases',
]

const BLOCKED_WORDS = new Set([
  'GOOK',
  'RAPE',
  'RETARD',
  'SLAVE',
  'SLAVERY',
  'HOLOCAUST',
  'MASSACRE',
  'TORTURE',
])

const VALID_WORD_DECK_IDS = new Set<WordDeckId>(['bidding', 'green', 'yellow', 'red', 'money'])
const VALID_DIFFICULTIES = new Set<WordDeck['difficulty']>(['green', 'yellow', 'red', 'money'])
const WORD_ENTRY_PATTERN = /^[A-Z0-9][A-Z0-9 ]*$/
const SOURCE_ID_PATTERN = /^[a-z0-9][a-z0-9-]*$/

function canonicalWordEntry(word: string): string {
  return word.trim().replace(/\s+/g, ' ')
}

function spacingInsensitiveKey(word: string): string {
  return canonicalWordEntry(word).replace(/\s/g, '')
}

function isIsoDateOnly(value: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false
  const date = new Date(`${value}T00:00:00.000Z`)
  if (Number.isNaN(date.getTime())) return false
  return date.toISOString().slice(0, 10) === value
}

export function getWordDecks(): WordDeck[] {
  return [
    {
      id: 'green',
      difficulty: 'green',
      tags: ['campus', 'food', 'sports', 'music', 'places', 'games'],
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: greenWords,
    },
    {
      id: 'yellow',
      difficulty: 'yellow',
      tags: ['campus', 'party', 'sports', 'movies', 'music', 'internet', 'jobs', 'travel'],
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: yellowWords,
    },
    {
      id: 'red',
      difficulty: 'red',
      tags: ['science', 'history', 'phrases', 'slang', 'games'],
      sourceIds: ['cefr-j-olp'],
      words: redWords,
    },
    {
      id: 'bidding',
      difficulty: 'yellow',
      tags: ['campus', 'party', 'food', 'sports', 'movies', 'music'],
      sourceIds: ['cefr-j-olp', 'curated-party'],
      words: WORD_POOLS.bidding,
    },
    {
      id: 'money',
      difficulty: 'money',
      tags: ['party', 'sports', 'movies', 'food', 'places', 'games'],
      sourceIds: ['curated-party'],
      words: moneyWords,
    },
  ]
}

export function getWordBankSummary(
  decks: WordDeck[] = getWordDecks(),
  sources: WordSource[] = WORD_BANK_SOURCES
): WordBankSummary {
  const deckCounts: Record<WordDeckId, number> = {
    bidding: 0,
    green: 0,
    yellow: 0,
    red: 0,
    money: 0,
  }
  const deckSummaries = decks.map(deck => {
    deckCounts[deck.id] = deck.words.length
    return {
      id: deck.id,
      difficulty: deck.difficulty,
      count: deck.words.length,
      tags: [...deck.tags],
      sourceIds: [...deck.sourceIds],
    }
  })

  return {
    totalPlayableWords: deckSummaries
      .filter(deck => deck.id !== 'bidding')
      .reduce((total, deck) => total + deck.count, 0),
    deckCounts,
    sourceCount: sources.length,
    decks: deckSummaries,
  }
}

export function validateWordBank(
  decks: WordDeck[] = getWordDecks(),
  sources: WordSource[] = WORD_BANK_SOURCES
): string[] {
  const errors: string[] = []
  const sourceIds = new Set(sources.map(source => source.id))
  const validTags = new Set(WORD_BANK_TAGS)
  const seenSourceIds = new Set<string>()
  const seenDeckIds = new Set<string>()
  const playableWordOwners = new Map<string, string>()
  const playableNearDuplicateOwners = new Map<string, { deckId: string; word: string }>()

  if (!sources.length) errors.push('word bank must include at least one source')
  sources.forEach(source => {
    const sourceId = source.id || '(missing id)'
    if (!source.id || !source.name || !source.url || !source.licenseNote || !source.importedAt || !source.transform) {
      errors.push(`source ${sourceId} is missing attribution metadata`)
    }
    if (source.id) {
      if (seenSourceIds.has(source.id)) errors.push(`source ${source.id} is duplicated`)
      seenSourceIds.add(source.id)
      if (!SOURCE_ID_PATTERN.test(source.id)) errors.push(`source ${source.id} has invalid id`)
    }
    if (source.importedAt && !isIsoDateOnly(source.importedAt)) {
      errors.push(`source ${sourceId} has invalid import date ${source.importedAt}`)
    }
    if (source.url && !/^(https?:\/\/|local:)/.test(source.url)) {
      errors.push(`source ${sourceId} has invalid url ${source.url}`)
    }
  })

  decks.forEach(deck => {
    const deckId = typeof deck.id === 'string' && deck.id ? deck.id : '(missing id)'
    if (seenDeckIds.has(deckId)) errors.push(`${deckId} deck id is duplicated`)
    seenDeckIds.add(deckId)
    if (!VALID_WORD_DECK_IDS.has(deck.id)) errors.push(`${deckId} deck has invalid id`)
    if (!VALID_DIFFICULTIES.has(deck.difficulty)) errors.push(`${deckId} deck has invalid difficulty ${deck.difficulty}`)
    if (!Array.isArray(deck.sourceIds) || deck.sourceIds.length === 0) errors.push(`${deckId} deck must include source attribution`)
    if (!Array.isArray(deck.tags) || deck.tags.length === 0) errors.push(`${deckId} deck must include at least one tag`)
    if (!Array.isArray(deck.words) || !deck.words.length) errors.push(`${deckId} deck is empty`)

    const deckSourceIds = new Set<string>()
    ;(Array.isArray(deck.sourceIds) ? deck.sourceIds : []).forEach(sourceId => {
      if (deckSourceIds.has(sourceId)) errors.push(`${deck.id} deck repeats source ${sourceId}`)
      deckSourceIds.add(sourceId)
      if (!sourceIds.has(sourceId)) errors.push(`${deck.id} deck references unknown source ${sourceId}`)
    })
    ;(Array.isArray(deck.tags) ? deck.tags : []).forEach(tag => {
      if (!validTags.has(tag)) errors.push(`${deck.id} deck has invalid tag ${tag}`)
    })

    const seen = new Set<string>()
    const nearSeen = new Map<string, string>()
    ;(Array.isArray(deck.words) ? deck.words : []).forEach((word, index) => {
      const label = `${deckId}[${index}]`
      if (typeof word !== 'string' || !word.trim()) {
        errors.push(`${label} is empty`)
        return
      }
      const canonical = canonicalWordEntry(word)
      if (word !== canonical) errors.push(`${label} must use normalized spacing: ${word}`)
      if (canonical.length > 32) errors.push(`${label} is too long: ${canonical}`)
      if (canonical !== canonical.toUpperCase()) errors.push(`${label} must be uppercase: ${canonical}`)
      if (!WORD_ENTRY_PATTERN.test(canonical)) errors.push(`${label} has invalid characters: ${canonical}`)
      if (BLOCKED_WORDS.has(canonical)) errors.push(`${label} is blocked by safety filter: ${canonical}`)
      if (seen.has(canonical)) errors.push(`${deckId} contains duplicate word: ${canonical}`)
      seen.add(canonical)

      const nearKey = spacingInsensitiveKey(canonical)
      const previousNearWord = nearSeen.get(nearKey)
      if (previousNearWord && previousNearWord !== canonical) {
        errors.push(`${deckId} contains near-duplicate word: ${canonical} matches ${previousNearWord}`)
      } else {
        nearSeen.set(nearKey, canonical)
      }

      if (deck.id !== 'bidding') {
        const previousDeck = playableWordOwners.get(canonical)
        if (previousDeck && previousDeck !== deckId) {
          errors.push(`${deckId} duplicates ${canonical} from ${previousDeck}`)
        } else {
          playableWordOwners.set(canonical, deckId)
        }

        const previousNearOwner = playableNearDuplicateOwners.get(nearKey)
        if (previousNearOwner && previousNearOwner.word !== canonical) {
          errors.push(`${deckId} near-duplicates ${canonical} from ${previousNearOwner.deckId} (${previousNearOwner.word})`)
        } else {
          playableNearDuplicateOwners.set(nearKey, { deckId, word: canonical })
        }
      }
    })
  })

  return errors
}
